### ISSUE TITLE
basic example fails to build on macOS

### ISSUE THREAD

**Issue by amatuni** [LaurentMazare/tch-rs#101]
running this command:

```
cargo run --example basics
```

results in this linking error:

```
dyld: Library not loaded: @rpath/libmklml.dylib
  Referenced from: /Users/andrei/code/third_party/tch-rs/target/debug/build/torch-sys-3302c22306cc5a9b/out/libtorch/libtorch/lib/libtorch.dylib
  Reason: image not found
[1]    52829 abort      cargo run --example basics
```

is tch-rs supposed to also download libmklml in addition to libtorch?

**Comment by vegapit** [comment]
Yes, on OSX, you need to copy `libmklml.dylib` to the `libtorch\lib` folder

**Comment by vegapit** [comment]
Since the `LIBTORCH` variable is set before building starts, it is possible to check and download if required in the `torch-sys/build.rs` script. But since this step is totally OSX specific and since you would still have to do the manual setup before hand, it is not really a game changer to add this functionality.

**Comment by LaurentMazare** [comment]
Fwiw in the ocaml equivalent of these torch bindings, we automatically [download and install](https://github.com/ocaml/opam-repository/blob/master/packages/libtorch/libtorch.1.2.0/opam) libmklml. The main advantage is that it makes the CI setup a bit easier. We don't have a CI for macOS yet but this would probably be useful and I would have nothing against adding the libmklml download/install to `torch-sys/build.rs`.

**Comment by vegapit** [comment]
As I am not familiar with library linking processes, the reasoning below could be nonsense, but I share it just in case. 

After a quick glance at `build.rs`, I realised that the functionality to download and extract the correct version of `libtorch` already exists. To avoid the manual modification to `LD_LIBRARY_PATH`, has anyone tried to write a `Rust` function (called `register_library` for example) that would do a local modification of `PATH` from the user's `main` function? Could it theoretically work?

```rust
fn main() {
     tch::register_library();
     // ... Fancy torch neural net calibration .... 
}
```

**Comment by LaurentMazare** [comment]
My understanding of the linking process is also somewhat limited but I think it's already too late when reaching the `main` function, your library should already have been found by the loader at this point.
Alternatively you could call `dlopen` from `main` and get the symbols from there but then you probably lose most of the advantages of dyn linking the library (I would say that it's mostly that symbols are checked for at compile time).

**Comment by vegapit** [comment]
I have updated to Libtorch 1.3 and the basic examples are now failing on Osx with a very cryptic error message:
```
Running `target/debug/examples/basics`
Illegal Instruction 4
```
Any idea on why that could be?

Libtorch library used: [https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.3.0.zip](https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.3.0.zip)

**Comment by LaurentMazare** [comment]
I'm afraid this is related to this issue: https://github.com/pytorch/pytorch/issues/27627 which as far as I understand won't be fixed until 1.3.1.

**Comment by vegapit** [comment]
Oh dear, the content of the thread is not reassuring at all. Anyway, thank you for the quick response, I will use another OS in the meantime.

**Comment by LaurentMazare** [comment]
Closing this as tch-rs now uses 1.3.1 which hopefully fixes this. I haven't tested it though so feel free to reopen if it's still problematic.
