### ISSUE TITLE
BoolTensor support

### ISSUE THREAD

**Issue by jean-airoldie** [LaurentMazare/tch-rs#102]
I want to compare the equality of the content of two tensors. To do so, I use the following:
```rust
#[test]
test_eq() {
    let first = Tensor::from(0i64).one_hot(3);
    let second = Tensor::of_slice(&[1i64, 0i64, 0i64]);
    assert!(first.eq1(&second).all());
}
```
From the documentation `eq1` returns a `torch.BoolTensor`. Then `all` returns another `BoolTensor` with a single `bool` element.

How can I retrieve this `bool` element since `From<Tensor>` is not implemented for `bool`? Moreover, the `bool` data type seems to be missing from the `Kind`.

~~As an aside, what do you think of implementing `Eq<&Tensor> for Tensor` this way?~~

edit: I know that I could convert the tensor unto a `u8` and compare it with zero, but that seems inconvenient.

**Comment by LaurentMazare** [comment]
In this case when trying to check equality, what about:
```rust
assert!(first == second);
```
This relies on the tensor type implementing `PartialEq` in `src/tensor/mod.rs`.

**Comment by jean-airoldie** [comment]
Right this would work.

But how are `BoolTensors` handled by `tch-rs`? Are there no use cases were you would want to retrieve the content of a `BoolTensor`?

**Comment by LaurentMazare** [comment]
I've added some basic support for bool tensors, you can see some examples of how to use them in the [tests](https://github.com/LaurentMazare/tch-rs/blob/4e78503ce351fa4cfd018d3824de430f2f1fbe2a/tests/tensor_tests.rs#L248-L263).
Let me know if there are more functionalities that you would want to have for this (or feel free to make a PR).

**Comment by jean-airoldie** [comment]
Nice, that was exactly what I was looking for.

**Comment by LaurentMazare** [comment]
Cool I haven't done much that running the tests on it, so any feedback is very welcome.
