### ISSUE TITLE
trained variables set at .build or at .step ?

### ISSUE THREAD

**Issue by zeroexcuses** [LaurentMazare/tch-rs#106]
I wrote some code of the form:

```
let vs = VarStore::new();
let opt = ... .build(&vs);
let model = Model::new(&vs);
while ... {
  loss = model.forward(...);
  opt.backward_step(loss);
}
```

The problem is, because or https://github.com/LaurentMazare/tch-rs/blob/master/src/nn/optimizer.rs#L25-L26 ,
the optimizer gets an empty Vec for the list of trainable tensors.

I found this confusing because based on the code, I got the impression that the optimizer is attached to the VarStore. However, the optimizer is attached to _trainable variables in the varstore at the time .build is called_.

Is this intended behavior?

**Comment by LaurentMazare** [comment]
It's certainly not set in stone. I would have to think more about it but I don't dislike the current semantics, I find that it's a bit more functional this way rather than having the optimizer being modified when the var-store changes.

**Comment by zeroexcuses** [comment]
I think we have three choices here:

```
(A) fn build(self, vs: &VarStore, lr: f64) // current, get trainable vars at .build time
(B) fn build(self, vs: &VarStore, lr: f64) // get trainable vars at .step time
(C) fn build(self, vs: Vec<Tensor>, lr: f64) // pass trainable vars
```
Currently, tch-rs uses (A). I was arguing for (B). You also suggested (C) above.

===

I have no problem with (C) -- it looks clear to me.

I think (A) is counter-intuitive _and_ ANTI-FUNCTIONAL.

Note that VarStore::add takes `&self` not `&mut self` at https://github.com/LaurentMazare/tch-rs/blob/master/src/nn/var_store.rs#L225

Consider the following code:

```
let vs = VarStore::new(); // note lack of mut
let opt_a = ... .build(&vs); //
vs.add(...)
let opt_b = ... .build(&vs); //
```

Under `A / bind at .build`, opt_a and opt_b behave differently.
Under `B / bind at .step`, opt_a and opt_b behave the same.

I would argue that it is MORE FUNCTIONAL for opt_a and opt_b to behave the same for the following reason:

  1. They are being constructed with the same arguments.
  2. They are being passed the same ref &vs / pointer to the same VarStore
  3. Sure, there was a VarStore::add call in between, but VarStore::add takes &self not &mut self, so we're implying that "we're not changing things"

===

I strongly believe that (A) is confusing. I don't have a strong preference of (B) vs (C).
