### ISSUE TITLE
Tensor::copy_data is very unsafe

### ISSUE THREAD

**Issue by andersk** [LaurentMazare/tch-rs#107]
`Tensor::copy_data` is not marked `unsafe`, but it has no checks on the return type or the length of the target slice. Thus, for example, it can be used to overwrite a Rust reference with null:

```rust
let mut s = ["foo"];
Tensor::zeros(&[1], (Kind::Int64, Device::Cpu)).copy_data(&mut s, 1);
println!("{}", s[0]);
// Segmentation fault
```

or overflow a slice entirely.

```rust
let mut s: [u8; 0] = [];
Tensor::zeros(&[10000], (Kind::Int8, Device::Cpu)).copy_data(&mut s, 10000);
// → Segmentation fault
```

**Comment by LaurentMazare** [comment]
Thanks for pointing this out, I just pushed some changes to forbid the first case at compile time and turn the second case into a proper panic rather than a segfault (note that you can use `f_copy_data` rather than `copy_data` if you want the fallible version).

**Comment by LaurentMazare** [comment]
Closing as this should hopefully be fixed now, feel free to re-open if you run into further issues.
