### ISSUE TITLE
Remove cuda version check in build.rs?

### ISSUE THREAD

**Issue by mwilliammyers** [LaurentMazare/tch-rs#109]
Are you cool with removing the CUDA version check at [build.rs#L75](https://github.com/LaurentMazare/tch-rs/blob/dfe4eef0724a0e5b6e1d53a29ffdc4c4f28e6a68/torch-sys/build.rs#L75)? I think it will get annoying to keep up to date and we should just skip it and let the URL not resolve.

We can keep the Linux check though.

**Comment by LaurentMazare** [comment]
This would seem reasonable to me yes, want to craft a PR for this or should I have a go at it ?

**Comment by mwilliammyers** [comment]
I can open one.
