### ISSUE TITLE
Add a continuous integration

### ISSUE THREAD

**Issue by ehsanmok** [LaurentMazare/tch-rs#11]
Hi

As different contributors are showing interests, having a CI becomes critical.

**Comment by paddyhoran** [comment]
What is the preference for the CI system?  Azure pipelines seems interesting and can support all major platforms in one solution.

**Comment by LaurentMazare** [comment]
Very good point, I certainly have this on my radar. I was thinking on using travis-ci as it interacts well with github. Hopefully I'll go over this in the next few days (I'm not familiar at all with azure but if it's easy to setup with github I'm happy to give it a try too).

**Comment by ehsanmok** [comment]
I don't have any preference. Travis CI or AppVeyor are common in Rust projects. We can use the templates from [trust](https://github.com/japaric/trust) for example.

**Comment by LaurentMazare** [comment]
Setting up travis-ci ended up being straightforward, there is now a compilation status badge on the main readme page.
I haven't set up anything to test PRs for now but I may add some bors hooks for this at some point.

**Comment by ehsanmok** [comment]
Great! Should be enough for now. bors is great :)
