### ISSUE TITLE
Separating Sequential add/add_fn from initialization

### ISSUE THREAD

**Issue by JonBoyleCoding** [LaurentMazare/tch-rs#116]
I'm trying to port over some of my python code; however coming across some issues due to the way a Sequential currently works.

The current way it's programmed is doesn't allow to add tensors after it's initialization. I'm wanting to dynamically create a model via loops, so I have no idea of the input size or number of layers as it's set dynamically. A bare-bones example:

```
let mut model = tch::nn::seq();

model.add(tch::nn::linear(var_store / "layer_final", input_feature_size, output_size, Default::default()));;
model.add_fn(|xs| xs.sigmoid());
```

Comes up with the error:

```
error[E0382]: use of moved value: `model`
  --> src/main.rs:20:5
   |
17 |     let mut model = tch::nn::seq();
   |         --------- move occurs because `model` has type `tch::nn::sequential::Sequential`, which does not implement the `Copy` trait
18 | 
19 |     model.add(tch::nn::linear(var_store / "layer_final", input_feature_size, output_size, Default::default()));;
   |     ----- value moved here
20 |     model.add_fn(|xs| xs.sigmoid());
   |     ^^^^^ value used here after move
```

Looking at the [source](https://github.com/LaurentMazare/tch-rs/blob/master/src/nn/sequential.rs), the reason this happens is that due to Copy not being implemented, when it returns 'Self' that moves everything meaning that it is no longer accessible further down the line if you're using it this way.

My first thoughts are to either:

- Make Sequential copyable (probably not a valid option, due to variable stores etc.)
- Adding separate non-builder functions that don't return 'Self'

I'm happy to work on putting something together and submit a PR, but thought it would be worth the discussion first as to the best way forward (if it's even wanted). I would think it would be better to add separate functions but I don't know how one would best differentiate them by name. I know some libraries have separate builder classes but that would create quite a breaking change to the API.

**Comment by LaurentMazare** [comment]
Sorry I don't have access to a computer this week so cannot comment into details or test my suggestion but what about doing the following ?
```rust
let mut model = tch::nn::seq();

model = model.add(tch::nn::linear(var_store / "layer_final", input_feature_size, output_size, Default::default()));;
model = model.add_fn(|xs| xs.sigmoid())
```
This is actually used for a bunch of examples e.g. mobilenet so that we can build the sequence through a for loop.
https://github.com/LaurentMazare/tch-rs/blob/81f6215c8f7a374b89591abbbd61ac3bfe24dc14/src/vision/mobilenet.rs#L59

**Comment by JonBoyleCoding** [comment]
Sorry for the lack of response. I've done a few tests.

In my particular case this doesn't work it seems as the actual modification is done inside an iterator's for_each method (after numerous other processes). While I can re-organise my code to not work with iterators, seems a bit of a shame that this can't be done with them.

```
error[E0507]: cannot move out of `model`, a captured variable in an `FnMut` closure
  --> src/main.rs:27:12
   |
19 |     let mut model = tch::nn::seq();
   |         --------- captured outer variable
...
27 |             model = model.add(tch::nn::linear(
   |                     ^^^^^ move occurs because `model` has type `tch::nn::sequential::Sequential`, which does not implement the `Copy` trait
``` 

For my own purposes for the time-being I just created my own sequential model that removed the return of self and used &mut for self to stop the move from occurring. I realise that this isn't necessarily going to work in the actual repository though.

**Comment by LaurentMazare** [comment]
Closing for now, feel free to re-open if you still have issues with this.
