### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by Bekovmi** [LaurentMazare/tch-rs#118]
Could you add benchmark of speed training and interference resnet50 on your rust library and python library on this dataset https://www.dropbox.com/s/ffzfpbwzwdo9qp8/ants_bees_cleared_190806.tar.gz.

**Comment by LaurentMazare** [comment]
This hasn't caught much attention in the last year so closing it for now.
Fwiw I wouldn't expect any significant difference in the training benchmark as it would be mostly GPU bounded. For inference it may make more of a difference - if anyone wants to give it a go and write a blog post/medimu/... about it that would be great.
