### ISSUE TITLE
examples/jit :: Error: TorchError { c_error: "can\'t fopen" }

### ISSUE THREAD

**Issue by tyfarnan** [LaurentMazare/tch-rs#119]
Hi! Awesome package you've got here. I'm running into some trouble trying to run 
cargo run --example jit model.pt image.jpg
cargo run --example pretrained-models -- resnet18.ot tiger.jpg

Any thoughts on how I can resolve? Thanks!

<img width="842" alt="Screen Shot 2019-11-09 at 1 31 00 AM" src="https://user-images.githubusercontent.com/29440317/68524344-ded26580-0293-11ea-8a57-89b2a271ba0d.png">

**Comment by LaurentMazare** [comment]
I'm on mobile so cannot check but the fopen in the error message may mean that there is no model.pt or resnet18.ot file in the current directory ?

**Comment by tyfarnan** [comment]
aha! I was indeed missing the .jpg file. I should go to sleep now, thanks a bunch!!
