### ISSUE TITLE
IValue causes memory leak

### ISSUE THREAD

**Issue by L1AN0** [LaurentMazare/tch-rs#121]
The following program causes memory leak (with tch-rs on master branch):

Example:

```rust
use tch::IValue;

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_ivalue() {
        let model = tch::CModule::load("test_model.zip").unwrap();
        loop {
            let ivalue = IValue::Tensor(tch::Tensor::rand(&[1000, 1000], (tch::Kind::Float, tch::Device::Cpu)));
            dbg!(model.forward_is(&[ivalue]).unwrap());
        }
    }
}
```

where "test_model.zip" is created by

```rust
import torch


@torch.jit.script
def test_model(a):
    return a.sum()


if __name__ == "__main__":
    test_model.save("test_model.zip")
```

**Comment by LaurentMazare** [comment]
Thanks for catching this, I can reproduce the issue and it seems to come from the `to_c` function in `src/wrappers/jit.rs` that creates new C++ ivalues but never release them. I'm a bit unsure what the best way is to fix this but I'll work on it.

**Comment by LaurentMazare** [comment]
I just pushed some changes that should release the leaked ivalue in this case, let me know if this doesn't fix your issue.
That said it's a work in progress as there is probably still a leak when using tuples or other nested ivalues.

**Comment by LaurentMazare** [comment]
Should be fully fixed now, let me know if you encounter further issues.
