### ISSUE TITLE
DLL error : Status Ordinal Not Found

### ISSUE THREAD

**Issue by ykafia** [LaurentMazare/tch-rs#126]
I'm getting this error : 

```powershell
error: process didn't exit successfully: `target\debug\neural1.exe` (exit code: 0xc0000138, STATUS_ORDINAL_NOT_FOUND)
```

From what i understood it might come from my installation of LibTorch so here's the steps i've followed : 

1. Download LibTorch for c++, CPU, release
2. Unzip the libtorch folder somewhere
3. Added an environment variable called LIBTORCH with the path of the libtorch folder
4. Added the libtorch folder to the PATH

**Comment by ykafia** [comment]
After some tests the full error is 
```powershell
The ordinal 901 could not be located in the dynamic link library D:/Programs/libtorch/lib/torch.dll
```

Code : 

```rust
use tch;
use tch::Scalar;
fn main() {
    println!("Hello, world!");
    let x = Scalar::float(5f64);
}
```

If i create a Tensor instead of a Scalar, the ordinal number changes.
So from what i understand it's not an installation problem.

**Comment by LaurentMazare** [comment]
From what I understand after some very quick googling, this could be caused by having version conflicts between some dlls (I didn't get this error while building on a windows box).
I would try removing all the dlls, re-extracting them from the libtorch release, checking LIBTORCH and running `cargo clean`. That said you probably already ran these steps, sorry I can't offer more advice.

**Comment by vegapit** [comment]
I can confirm that both libtorch version 1.3.0 and 1.3.1 work on my Windows 10 machine. I would also recommend deleting the `Cargo.lock` file of your test project after a `cargo clean` before building it with your new libtorch folder.

**Comment by ykafia** [comment]
@vegapit 

I'd like to know what you did to install everything !

The crate from crates.io ( i guess it's version 0.1.1 ) gave me a "-Wl, -rpath flags not recognized" error.
So i cloned the repo and referenced it by path in my TOML. (Which i guess is version 0.1.3)

I'll try installing it in another machine as soon as i get one on my hands.

**Comment by vegapit** [comment]
@ykafia 

I link up to the github version directly in my `Cargo.toml`:
```
tch = { git = "https://github.com/LaurentMazare/tch-rs" }
```
Does this solve the issue?

**Comment by ykafia** [comment]
Nope,

Doesn't seem so. I've cleaned everything rebuilt everything. did a little rustup.
@vegapit i installed torchlib like so  :
I used the release version of torchlib.
added LIBTORCH as path/to/libtorch
and in the PATH i added path/to/libtorch/bin

**Comment by vegapit** [comment]
@ykafia 

So if here is my set up:
1. Unzipped **libtorch-win-shared-with-deps-1.3.1.zip** and extracted the inner libtorch folder to an appropriate drive location.
2. Added **path/to/libtorch** in an environment variable called LIBTORCH
3. Added **path/to/libtorch/lib** to PATH

You have added the **bin** and **lib** to your PATH so could this be the problem?

**Comment by clouds56** [comment]
Same here, added `lib` to my PATH, (if not the error would be STATUS_DLL_NOT_FOUND but not STATUS_ORDINAL_NOT_FOUND)
I'm using libtorch-win-shared-with-deps-1.4.0.zip with `tch = { git = "https://github.com/LaurentMazare/tch-rs" }`

**Comment by clouds56** [comment]
I found out the reason.
I've got LLVM in my path which has libiomp5md.dll in PATH.
Not sure why rustc or VS linker would take this dll but after delete LLVM, it works.

**Comment by ykafia** [comment]
This worked for me too ! Should i create an issue on the rust compiler's repo ?

**Comment by Stvchm9703** [comment]
it works after remove LLVM , should it mark it to readme ?

**Comment by dskkato** [comment]
I encountered a similar issue because incompatible dll might be used. I could avoid it without uninstalling LLVM or other packages with the following command:

```
$Env:Path = "X:\path\to\libtorch\lib;" + $Env:Path 
```

instead of a command in the README.md

```
$Env:Path += ";X:\path\to\libtorch\lib"
```

Here, the order is important. Perhaps. the same rule can be applied when the `Path` is set via Control Panel.
