### ISSUE TITLE
Expand IValue to all TorchScript Supported Types

### ISSUE THREAD

**Issue by ArmenAg** [LaurentMazare/tch-rs#127]
Current tch-rs IValue which is used as the input to TorchScript models covers the following input:
- ``Tensor(crate::Tensor)``
- ``Int(i64)``
- ``Double(f64)``
- ``Tuple(Vec<IValue>)``

Taking a look at [TorchScript supported types](https://pytorch.org/docs/stable/jit.html#supported-type) we still need to support:
- [x] `bool` | A boolean value: (https://github.com/LaurentMazare/tch-rs/commit/0e4ecff8fbb73e6151ce2bade5a0857a324d8fe5)
- [x] `str` | A string (https://github.com/LaurentMazare/tch-rs/commit/7d3e9cb445a72608789271c0d3735ca43eaf6edf)
- [x] `List[T]` | A list of which all members are type T
- [ ] `Optional[T]` | A value which is either None or type T
- [x] `Dict[K, V]` | A dict with key type K and value type V. Only str, int, and float are allowed as key 
types.
- [ ] `NamedTuple[T0, T1, ...]`

Are there plans to add support for these types anytime soon?

**Comment by LaurentMazare** [comment]
Happy to add support for some of the missing ivalue types, I just pushed some changes to support `None` and `bool`. We should aim at supporting all of them but let me know if some are more interesting to you and we'll push on these first.

**Comment by ArmenAg** [comment]
Thanks for the quick response @LaurentMazare! It'd be great if List[T] could be implemented. List[str] is especially useful for dealing with language based models.

FYI we're using this library to implement a production server for TorchScript written in Rust.

**Comment by LaurentMazare** [comment]
There is now some support for monomorphic lists (IntList, DoubleList, TensorList, BoolList) as detailed in this [enum](https://github.com/pytorch/pytorch/blob/v1.3.1/aten/src/ATen/core/ivalue.h#L39-L58). I'm not sure how exactly this relates to `List[T]`, `Optional[T]` but I think this should cover it.
GenericList should also be supported and can be used to get a list of string. E.g. I also added a new test where a python jit module is used to remove the last letter of each string in a list ([python code](https://github.com/LaurentMazare/tch-rs/blob/master/tests/create_jit_models.py#L64-L73), [rust test](https://github.com/LaurentMazare/tch-rs/blob/master/tests/jit_tests.rs#L52-L70)).


You can see some other tests using this with the `into` trait at the end of [jit.rs](https://github.com/LaurentMazare/tch-rs/blob/master/src/wrappers/jit.rs#L258-L285).

**Comment by ArmenAg** [comment]
Looks great! Thanks for the pointers!

**Comment by LaurentMazare** [comment]
Just to mention that Dict should now be supported. The rust is equivalent is a vector of pairs of IValues for now as IValues cannot be used as a key for maps in a straightforward way (as they include a float case).

**Comment by LaurentMazare** [comment]
Closing this for now as the main types should be supported, feel free to re-open if there are some missing bits that would be useful to you.
