### ISSUE TITLE
Manual installation of Libtorch on Windows

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#128]
Hello,

I am having issues installing Libtorch with CUDA support on Windows. The automatic installation without providing a Libtorch target folder works fine, but unfortunately only supports CPU for windows.

I downloaded the CUDA 10.1 version of Libtorch and set-up my environment variable as given in the installation guide:
```
LIBTORCH=C:\path\to\libtorch;
Path=C:\path\to\libtorch
```
Where C:\path\to\libtorch is the root directory containing \bin, \cmake \include...

The library compiles fine with this manual installation of Libtorch. Unfortunately calling the library from Rust then causes an error

`error: process didn't exit successfully: `target\debug\main.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)`

It seems the Path is not used to look for the required DLL. I believe the automated installation does not have this issue because it stores the Libtorch library directly in the build directory of the tch-rs dependency.

Could you please help me understand if I do anything wrong? Alternatively, could you please add the CUDA binaries for Windows (they are available on the Pytorch official website at https://download.pytorch.org/libtorch/cu101/libtorch-win-shared-with-deps-1.3.1.zip

**Comment by LaurentMazare** [comment]
Have you followed the steps mentioned by @vegapit in this [other issue](https://github.com/LaurentMazare/tch-rs/issues/126#issuecomment-560840888)?
I don't use PyTorch on Windows myself so cannot be really helpful but hopefully his setup will work for you too.

**Comment by guillaume-be** [comment]
Thank you for the prompt response. I haven't seen the other issue. I forked the library and successfully ran on GPU by slightly modifying your build process (see related PR)

**Comment by LaurentMazare** [comment]
Closing as this seems solved now.
