### ISSUE TITLE
failing to build the examples

### ISSUE THREAD

**Issue by simdimdim** [LaurentMazare/tch-rs#130]
Hello, 
trying a `cargo +stable run --example basics`  with freshly downloaded libtorch lands me at: 

> ...
> Compiling synstructure v0.12.3
> Compiling failure v0.1.6
> Compiling torch-sys v0.1.4 (/home/thisuser/Coding/tch-rs/torch-sys)
> error: failed to run custom build command for `torch-sys v0.1.4 (/home/thisuser/Coding/tch-rs/torch-sys)`
> 
> Caused by:
> process didn't exit successfully: `/home/thisuser/Coding/tch-rs/target/debug/build/torch-sys-5da9e57de85a42c7/build-script-build` (exit code: 1)
> --- stdout
> cargo:rustc-link-search=native=/home/thisuser/libtorch/lib
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("0")
> HOST = Some("x86_64-unknown-linux-gnu")
> CXX_x86_64-unknown-linux-gnu = None
> CXX_x86_64_unknown_linux_gnu = None
> HOST_CXX = None
> CXX = None
> CXXFLAGS_x86_64-unknown-linux-gnu = None
> CXXFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CXXFLAGS = None
> CXXFLAGS = None
> CRATE_CC_NO_DEFAULTS = None
> DEBUG = Some("true")
> CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
> running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/thisuser/libtorch/include" "-I" "/home/thisuser/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/home/thisuser/libtorch/lib" "-std=c++11" "-D_GLIBCXX_USE_CXX11_ABI=1" "-o" "/home/thisuser/Coding/tch-rs/target/debug/build/torch-sys-2720fb9a1edc3bdf/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp"
> cargo:warning=In file included from /home/thisuser/libtorch/include/c10/util/ArrayRef.h:19,
> cargo:warning= from /home/thisuser/libtorch/include/c10/core/MemoryFormat.h:5,
> cargo:warning= from /home/thisuser/libtorch/include/ATen/core/TensorBody.h:5,
> cargo:warning= from /home/thisuser/libtorch/include/ATen/Tensor.h:11,
> cargo:warning= from /home/thisuser/libtorch/include/ATen/Context.h:4,
> cargo:warning= from /home/thisuser/libtorch/include/ATen/ATen.h:5,
> cargo:warning= from /home/thisuser/libtorch/include/torch/csrc/autograd/profiler.h:12,
> cargo:warning= from /home/thisuser/libtorch/include/torch/csrc/autograd/function.h:6,
> cargo:warning= from /home/thisuser/libtorch/include/torch/csrc/autograd/engine.h:9,
> cargo:warning= from libtch/torch_api.cpp:1:
> cargo:warning=/home/thisuser/libtorch/include/c10/util/C++17.h:20:2: error: #error You need C++14 to compile PyTorch
> cargo:warning= 20 | #error You need C++14 to compile PyTorch
> cargo:warning= | ^~~~~
> cargo:warning=In file included from libtch/torch_api.cpp:6:
> cargo:warning=libtch/torch_api.cpp: In function ‘void at_load_callback(char*, void*, void (*)(void*, char*, tensor))’:
> cargo:warning=libtch/torch_api.cpp:236:33: error: ‘struct torch::jit::script::Module’ has no member named ‘get_parameters’; did you mean ‘parameters’?
> cargo:warning= 236 | for (const auto &p : module.get_parameters()) {
> cargo:warning= | ^~~~~~~~~~~~~~
> cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
> cargo:warning= 16 | x \
> cargo:warning= | ^
> cargo:warning=libtch/torch_api.cpp: In function ‘void at_run_backward(at::Tensor**, int, at::Tensor**, int, at::Tensor**, int, int)’:
> cargo:warning=libtch/torch_api.cpp:346:69: error: ‘using Variable = class at::Tensor’ {aka ‘class at::Tensor’} has no member named ‘gradient_edge’
> cargo:warning= 346 | roots.push_back(torch::autograd::as_variable_ref(*tensors[i]).gradient_edge());
> cargo:warning= | ^~~~~~~~~~~~~
> cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
> cargo:warning= 16 | x \
> cargo:warning= | ^
> cargo:warning=libtch/torch_api.cpp:350:70: error: ‘using Variable = class at::Tensor’ {aka ‘class at::Tensor’} has no member named ‘gradient_edge’
> cargo:warning= 350 | inputs_.push_back(torch::autograd::as_variable_ref(*inputs[i]).gradient_edge());
> cargo:warning= | ^~~~~~~~~~~~~
> cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
> cargo:warning= 16 | x \
> cargo:warning= | ^
> cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_cudnn_batch_norm_backward(at::Tensor**, tensor, tensor, tensor, tensor, tensor, tensor, tensor, double)’:
> cargo:warning=libtch/torch_api_generated.cpp.h:2264:277: error: too few arguments to function ‘std::tuple<at::Tensor, at::Tensor, at::Tensor> at::cudnn_batch_norm_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, double, const at::Tensor&)’
> cargo:warning= 2264 | auto outputs__ = torch::cudnn_batch_norm_backward(*input, *grad_output, *weight, (running_mean ? *running_mean : torch::Tensor()), (running_var ? *running_var : torch::Tensor()), (save_mean ? *save_mean : torch::Tensor()), (save_var ? *save_var : torch::Tensor()), epsilon);
> cargo:warning= | ^
> cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
> cargo:warning= 16 | x \
> cargo:warning= | ^
> cargo:warning=In file included from /home/thisuser/libtorch/include/ATen/ATen.h:12,
> cargo:warning= from /home/thisuser/libtorch/include/torch/csrc/autograd/profiler.h:12,
> cargo:warning= from /home/thisuser/libtorch/include/torch/csrc/autograd/function.h:6,
> cargo:warning= from /home/thisuser/libtorch/include/torch/csrc/autograd/engine.h:9,
> cargo:warning= from libtch/torch_api.cpp:1:
> cargo:warning=/home/thisuser/libtorch/include/ATen/Functions.h:3245:48: note: declared here
> cargo:warning= 3245 | static inline std::tuple<Tensor,Tensor,Tensor> cudnn_batch_norm_backward(const Tensor & input, const Tensor & grad_output, const Tensor & weight, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_var, double epsilon, const Tensor & reserveSpace) {
> cargo:warning= | ^~~~~~~~~~~~~~~~~~~~~~~~~
> exit code: 1
> 
> --- stderr
> 
> 
> error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/thisuser/libtorch/include" "-I" "/home/thisuser/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/home/thisuser/libtorch/lib" "-std=c++11" "-D_GLIBCXX_USE_CXX11_ABI=1" "-o" "/home/thisuser/Coding/tch-rs/target/debug/build/torch-sys-2720fb9a1edc3bdf/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp" with args "c++" did not execute successfully (status code exit code: 1).

am I missing something or is this the expected result for the current commit ( 83fb3e9ac82853dfdf80593fd47f3d79dffd3b55 ) ?

**Comment by LaurentMazare** [comment]
This is certainly not expected: the current tip compiles well locally for me and in CI.
Maybe it's related to the "error: #error You need C++14 to compile PyTorch" message in your stacktrace and your C++ compiler is too old ?
Also another thing to double check is that you downloaded the PyTorch version using the cxx11 abi (but a mismatch there usually produces a different kind of error about missing symbols).

**Comment by simdimdim** [comment]
I'm running all latest packages on arch, and got this one https://download.pytorch.org/libtorch/nightly/cu101/libtorch-cxx11-abi-shared-with-deps-latest.zip from pytorch.org tried botch stable and nighly rust, same result, now trying to edit the cmakelists file, but with little success so far (as in it might not be paying attention to it at all).
also thanks for the lightning fast response :)

**Comment by simdimdim** [comment]
Changing the flag in torch-rs/build.rs from std=c++11 to std=c++14 gets rid of the C14 error but there's still some stuff left:

> Caused by:
>   process didn't exit successfully: `/home/thedoctor/Coding/pappy/tch-rs/target/debug/build/torch-sys-5da9e57de85a42c7/build-script-build` (exit code: 1)
> --- stdout
> cargo:rustc-link-search=native=/home/thedoctor/libtorch/lib
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("0")
> HOST = Some("x86_64-unknown-linux-gnu")
> CXX_x86_64-unknown-linux-gnu = None
> CXX_x86_64_unknown_linux_gnu = None
> HOST_CXX = None
> CXX = None
> CXXFLAGS_x86_64-unknown-linux-gnu = None
> CXXFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CXXFLAGS = None
> CXXFLAGS = None
> CRATE_CC_NO_DEFAULTS = None
> DEBUG = Some("true")
> CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
> running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/thedoctor/libtorch/include" "-I" "/home/thedoctor/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/home/thedoctor/libtorch/lib" "-std=c++14" "-D_GLIBCXX_USE_CXX11_ABI=1" "-o" "/home/thedoctor/Coding/pappy/tch-rs/target/debug/build/torch-sys-2720fb9a1edc3bdf/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp"
> cargo:warning=In file included from libtch/torch_api.cpp:6:
> cargo:warning=libtch/torch_api.cpp: In function ‘void at_load_callback(char*, void*, void (*)(void*, char*, tensor))’:
> cargo:warning=libtch/torch_api.cpp:236:33: error: ‘struct torch::jit::script::Module’ has no member named ‘get_parameters’; did you mean ‘parameters’?
> cargo:warning=  236 |     for (const auto &p : module.get_parameters()) {
> cargo:warning=      |                                 ^~~~~~~~~~~~~~
> cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
> cargo:warning=   16 |     x \
> cargo:warning=      |     ^
> cargo:warning=libtch/torch_api.cpp: In function ‘void at_run_backward(at::Tensor**, int, at::Tensor**, int, at::Tensor**, int, int)’:
> cargo:warning=libtch/torch_api.cpp:346:69: error: ‘using Variable = class at::Tensor’ {aka ‘class at::Tensor’} has no member named ‘gradient_edge’
> cargo:warning=  346 |       roots.push_back(torch::autograd::as_variable_ref(*tensors[i]).gradient_edge());
> cargo:warning=      |                                                                     ^~~~~~~~~~~~~
> cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
> cargo:warning=   16 |     x \
> cargo:warning=      |     ^
> cargo:warning=libtch/torch_api.cpp:350:70: error: ‘using Variable = class at::Tensor’ {aka ‘class at::Tensor’} has no member named ‘gradient_edge’
> cargo:warning=  350 |       inputs_.push_back(torch::autograd::as_variable_ref(*inputs[i]).gradient_edge());
> cargo:warning=      |                                                                      ^~~~~~~~~~~~~
> cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
> cargo:warning=   16 |     x \
> cargo:warning=      |     ^
> cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_cudnn_batch_norm_backward(at::Tensor**, tensor, tensor, tensor, tensor, tensor, tensor, tensor, double)’:
> cargo:warning=libtch/torch_api_generated.cpp.h:2264:277: error: too few arguments to function ‘std::tuple<at::Tensor, at::Tensor, at::Tensor> at::cudnn_batch_norm_backward(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, double, const at::Tensor&)’
> cargo:warning= 2264 |     auto outputs__ = torch::cudnn_batch_norm_backward(*input, *grad_output, *weight, (running_mean ? *running_mean : torch::Tensor()), (running_var ? *running_var : torch::Tensor()), (save_mean ? *save_mean : torch::Tensor()), (save_var ? *save_var : torch::Tensor()), epsilon);
> cargo:warning=      |                                                                                                                                                                                                                                                                                     ^
> cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
> cargo:warning=   16 |     x \
> cargo:warning=      |     ^
> cargo:warning=In file included from /home/thedoctor/libtorch/include/ATen/ATen.h:12,
> cargo:warning=                 from /home/thedoctor/libtorch/include/torch/csrc/autograd/profiler.h:12,
> cargo:warning=                 from /home/thedoctor/libtorch/include/torch/csrc/autograd/function.h:6,
> cargo:warning=                 from /home/thedoctor/libtorch/include/torch/csrc/autograd/engine.h:9,
> cargo:warning=                 from libtch/torch_api.cpp:1:
> cargo:warning=/home/thedoctor/libtorch/include/ATen/Functions.h:3245:48: note: declared here
> cargo:warning= 3245 | static inline std::tuple<Tensor,Tensor,Tensor> cudnn_batch_norm_backward(const Tensor & input, const Tensor & grad_output, const Tensor & weight, const Tensor & running_mean, const Tensor & running_var, const Tensor & save_mean, const Tensor & save_var, double epsilon, const Tensor & reserveSpace) {
> cargo:warning=      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~
> exit code: 1
> 
> --- stderr
>

**Comment by LaurentMazare** [comment]
The currently supported version of PyTorch for this crate is the stable 1.3.1 release. Maybe you should install this one rather than the nightly build (which is very likely to be broken).

**Comment by simdimdim** [comment]
I knew I had something that's too new... thanks, (running bleeding edge habits die hard xD)

**Comment by simdimdim** [comment]
It is fine now. Thanks o/
