### ISSUE TITLE
[question] Implement simple LSTM for forecasting

### ISSUE THREAD

**Issue by lykhouzov** [LaurentMazare/tch-rs#141]
I am trying to implement LSTM model for time series forecasting.
Actually i am trying to port examples from pyton to rust
for example there is a vanilla LSTM looks like following
```python
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
```
this code uses Keras.
As I understood correctly, In Pytorch alternative of `Dense` is `Linear`. 
So, I've done following code
```rust
#[derive(Debug)]
pub struct LSTM {
    hidden_dim: i64,
    window_size: i64,
    lstm: nn::LSTM,
    linear: nn::Linear,
}
impl LSTM {
    pub fn new(p: &Path, in_dim: i64, hidden_dim: i64, out_dim: i64, window_size: i64) -> Self {
        let c = RNNConfig {
            dropout: 0.5,
            ..RNNConfig::default()
        };
        let lstm1 = nn::lstm(&(p / "lstm"), in_dim, hidden_dim, c);
        let linear = nn::linear(
            p / "linear",
            hidden_dim,
            out_dim,
            LinearConfig::default(),
        );
        LSTM {
            hidden_dim,
            window_size,
            lstm: lstm1,
            linear,
        }
    }
}
impl Module for LSTM {
    fn forward(&self, input_seq: &Tensor) -> Tensor {
        let (x, _state) = self.lstm.seq(&input_seq);
        let x = self.linear.forward(&gelu(&x));
        let x = gelu(&x);
        x
    }
}
fn gelu(x: &Tensor) -> Tensor {
    use std::f64::consts::PI;
    0.5 * x * (1.0 + (2.0 / PI).sqrt().tanh() * (x + 0.044715 * x.pow(3)))
}
```
and then I have in main
```rust
mod lstm;
fn main() {
    let in_dim: i64 = 9; 
    let window_size = 3; 
    let hidden_dim: i64 = 32;
    let batch_size = 10;
    let out_dim: i64 = 1;
    let vs = VarStore::new(Device::cuda_if_available());
    let rnn = lstm::LSTM::new(&vs.root(), in_dim, hidden_dim, out_dim, window_size);
}
```
So, I am expecting to feed a sample of time series like `[10, 12, 9]` and get output of `forward` as one number. But I am getting a tensor with dimension `[10, 12, 1]`

What I am doing wrong?
PS: example of python code I take from [here](https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/)

**Comment by LaurentMazare** [comment]
The first output of `lstm.seq()` is a tensor of shape `[batch_size, seq_len, outputs]` so `[10, 12, 1]` seems reasonable in your case: you get the lstm output for each time step.
If you only care about the final timestep, maybe you want to do something `x.i((.., -1, ..))` ?

**Comment by lykhouzov** [comment]
Thank you @LaurentMazare  for the response. Maybe it make sense.
But in this case I a bit confused, because I was thinking as following.

we have a sequence like
```
1 3 3
2 2 3
3 1 3
4 0 3
```
I take a tensor of first 3 rows (i have tensor `[3,3]`)
```
1 3 3
2 2 3
3 1 3
```
to predict next number `4`

but as I understood you'r saying that it predicts me whole row, that is `4, 0, 3` and if I need only one number i just need to take proper index of tensor.
Is it correct?

**Comment by LaurentMazare** [comment]
Sorry I don't understand what are the dimensions in your examples. Your input should be a tensor with 3 dimensions, `[batch_size, seq_len, features]` and the output of `lstm.seq` will also have 3 dimensions `[batch_size, seq_len, lstm_hidden_size]`. Then applying the linear layer results in a tensor with again 3 dimensions `[batch_size, seq_len, outputs]` where `outputs` is 1 in your case.
So if you just want the final output of the lstm, you want to get the last index for the second dimension, hence the `tensor.i((.., -1, ..))`.

**Comment by lykhouzov** [comment]
I am sorry. my fault to be not enough clear.
what I've tried to explain is that `[3,3]` tensor is actually `[1, 3, 3]`, so lets say i have already pre-trained model and now i want to predict my number.
so I have data like 
```
1 3 3
2 2 3
3 1 3
```
where rows is a time step and columns is features for a time step.
I convert it to `[batch_size, seq_len, features]` that is `[1, 3, 3]`.

So, then if do a `rnn.forward(data)` and get a tensor with  `[1,3,1]`, that is let say it is supposed to be ( if I understood it correctly)
```
2
3
4
```
and you suggest just take last row that is `x.i((.., -1, ..))` in this case i will get just `4`
It is not how it is in real but it is how it supposed to be, is it correct?

If yes, then it is not what exactly what i expected, and what I expect is `input_tensor[3,3] -> model.forward -> output_scalar_tensor`

PS: i am sorry, maybe I am completely wrong and misunderstood how LSTM should work

**Comment by lykhouzov** [comment]
Hello.
So, after testing and investigation of python code, i found that you are totally right,
so the action of `x.i((.., -1, ..))` is the same as in python is usually does `return_sequence = False`, if i understood it correctly.

so in my case it looks like following
```rust
impl Module for LSTM {
    fn forward(&self, input_seq: &Tensor) -> Tensor {
        let (x, _) = self.lstm1.seq(&input_seq);
        let x = x.i((.., -1, ..));
        let x = gelu(&x);
        let x = self.linear.forward(&x);
        let x = gelu(&x);

        x
    }
}
```
which give the same output as 
```python
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
```

The only question remains not clear for me, is this `50` units is the same as `num_layers: 2,` in `RNNConfig` ?

Thank you.

**Comment by LaurentMazare** [comment]
> The only question remains not clear for me, is this `50` units is the same as `num_layers: 2,` in `RNNConfig` ?

I don't think so. 50 units is the same as setting `hidden_dim` to 50 in the following bit of your code. You should probably keep using the default of `num_layers: 1` except if you want to stack multiple LSTM layers.
```rust
let lstm1 = nn::lstm(&(p / "lstm"), in_dim, hidden_dim, c);
```

**Comment by lykhouzov** [comment]
Hi, @LaurentMazare 
Thank you for responses.
Reading pytorch version of LSTM, I found that `num_layers` is used to build stacked LSTM model.
And inside rust code it looks like its true.
so, if I am not wrong these two peace of code are equal
```rust
let c = RNNConfig {
            num_layers: 1,
            ..RNNConfig::default()
        };
let lstm1 = nn::lstm(&(p / "lstm1"), in_dim, hidden_dim*2, c);
let lstm2 = nn::lstm(&(p / "lstm2"), hidden_dim*2, hidden_dim, c);

let seq = ...;
let (x, _) = lstm1.forward(seq);
let (x, _) = lstm1.forward(x);
```
and
```rust
let c = RNNConfig {
            num_layers: 2,
            ..RNNConfig::default()
        };
let lstm = nn::lstm(&(p / "lstm"), in_dim, hidden_dim, c);
let seq = ...;
let (x, _) = lstm.forward(x);
```
So, in both cases final `x` should be the same.

And `units` it is equal to `hidden_dim`
Anyway, Thank you to help me understand all of these.
I will close the ticket.
