### ISSUE TITLE
Decouple code generated from the implementation

### ISSUE THREAD

**Issue by ehsanmok** [LaurentMazare/tch-rs#15]
It seems that changing something like `Device` implementation that is used in `c_wrapper_generated.rs` cannot be made automatic due to none existent code generation setup in the crate, so it's a greater barrier for further developments and improvements. 

Could you remove the generated codes from the crate and make them available only when the crate is built as artifacts? (This is possible with `torch-sys` though)

**Comment by ehsanmok** [comment]
I found a workaround #16. But I still I think I should be addressed.

**Comment by LaurentMazare** [comment]
Closing as I don't think this is relevant anymore.
