### ISSUE TITLE
tch::CModule::load support for loading from bytes.

### ISSUE THREAD

**Issue by bminixhofer** [LaurentMazare/tch-rs#150]
Hi! Thanks for this library!

In PyTorch, it is possible to load a `ScriptModule` from bytes like so:

```python
import torch
import io

raw_bytes = open("module.pt", "rb").read() # or some other source of bytes
data = io.BytesIO(raw_bytes)

model = torch.jit.load(data)
```

In torch-rs, CModules can only be loaded directly from a path:

```rust
// https://github.com/LaurentMazare/tch-rs/blob/master/src/wrappers/jit.rs#L256
impl CModule {
    /// Loads a PyTorch saved JIT model from a file.
    pub fn load<T: AsRef<std::path::Path>>(path: T) -> Fallible<CModule> {
        let path = path_to_cstring(path)?;
        let c_module = unsafe_torch_err!({ atm_load(path.as_ptr()) });
        Ok(CModule { c_module })
    }
    // ...
}
```

Would it be possible to also implement loading from bytes, or maybe from a [`BufRead`](https://doc.rust-lang.org/std/io/trait.BufRead.html) for more flexibility?

I want to distribute some pretrained models along with my library. In this case, it would help a lot because I could just inline the pretrained models with i. e. [`include_bytes!`](https://doc.rust-lang.org/std/macro.include_bytes.html).

As a workaround, it would work right now to inline the bytes, and create a temporary named file at runtime from which the model is loaded. However, a cleaner solution would be great.

Thanks!

**Comment by LaurentMazare** [comment]
I just added a new function that should hopefully do the trick. There is an associated test in `jit_tests.rs` but let me know if you run into any issues with this.
```rust
impl CModule {
    /// Loads a PyTorch saved JIT model from a read instance.
    pub fn load_data<T: std::io::Read>(f: &mut T) -> Fallible<CModule> {
        ...
```

**Comment by bminixhofer** [comment]
Thanks for the fast fix! I wasn't aware of `std:io::Read`, that is surely the best way to implement it.

The function works for me. For future reference, I accomplished inlining a pretrained model this way:

```rust
use std::io::Cursor;

static MODULE: &'static [u8] = include_bytes!("module.pt");

// create a cursor when loading so that MODULE can be read from multiple times
let mut cursor = Cursor::new(MODULE);
let model = tch::CModule::load_data(&mut cursor);
```
I am not that confident in Rust yet but I think this is the best way.

Note that my model is very small, larger models should probably be distributed as separate files, unless they are absolutely necessary for the application.
