### ISSUE TITLE
Consider tracking Declarations.yaml in git

### ISSUE THREAD

**Issue by de-vri-es** [LaurentMazare/tch-rs#157]
I was planning to make some changes to code generation to work around #146. However, it appears I would need to compile pytorch manually to obtain a usable `Declarations.yaml` file.

I think it could make sense to track the `Declarations.yaml` file that was used for code generation. Then, anyone can make changes to the code generation and re-run it without compiling the right version of pytorch manually. That would save a lot of time and effort.

Do you think this would make sense?

**Comment by LaurentMazare** [comment]
It would certainly be helpful to have this file tracked in the git repo. The main reason why I haven't added it is that I don't really know what license would apply to it and how ok that would be with the current tch-sys double licensing (apache/mit).
If you have any pointers that makes you think this would be ok, I would be happy to add the file!

**Comment by de-vri-es** [comment]
I think it would be fine to just add the file and clarify somehow that a difference license applies to that file. It could be done by embedding the license in the file, or by adding the license right next to the file under a descriptive name (maybe `Declarations.yaml.LICENSE`). The second option has the advantage that the file can be copied verbatim every time you want to update it.

The yaml file doesn't end up in binary releases, so it only needs to be transferred with source copies. That's why I think it would be fine if the license file isn't at the root of the repository. If the license did have to be copied with binary releases, it would be too easy for packagers to miss the license in a subdirectory.

Another option could be to add a file called torch.LICENSE with a note at the top that explains for which files that license applies.

**Comment by LaurentMazare** [comment]
Closed via some variant of #160
