### ISSUE TITLE
[question] load saved in python model 

### ISSUE THREAD

**Issue by lykhouzov** [LaurentMazare/tch-rs#162]
Hello.
Is it possible to train model in pytorch and save the model and then load it in rust?

Thank you.

**Comment by LaurentMazare** [comment]
Yes, there are two different ways of doing so.
- The easiest way is to write a torch script module from python then load it and run it from rust. Some details on how to do this as well as some examples can be found in the [github repo](https://github.com/LaurentMazare/tch-rs/tree/master/examples/jit). In this case you don't even need an actual rust implementation of your model.
- All the models in the src/vision directories have a rust implementation but use some weights that were trained in python. This was done by outputting the weights in a npz file from python then importing them in rust via `examples/tensor-tools cp src.npz dst.ot`, I can give more details if you want to give this a try.

**Comment by lykhouzov** [comment]
Thank you, @LaurentMazare 
I am going to give a try to both options and will see what exact better works for me.

**Comment by LaurentMazare** [comment]
Closing this issue for now, feel free to re-open if you run into any issues.

**Comment by liebkne** [comment]
Hi @LaurentMazare ,

Can you provide more detail about the second way? I'd like to convert a pretrained model of my native language to `.ot` and use `rust-bert` to load it. Thank you!

**Comment by LaurentMazare** [comment]
Sure, so the idea there is to train the model in python and then to convert the weight to a `.ot`, you can:
- Write the weights out as a `npz` file, you can see an example of this for PyTorch vision model [here](https://github.com/LaurentMazare/ocaml-torch/blob/master/src/vision/export_model.py).
- Then run the examples I mentioned e.g. `cargo run --example tensor-tools cp resnet18.npz resnet18.ot`.
- The `.ot` file can then be loaded from Rust, via `vs.load("resnet18.ot")` where `vs` is a `VarStore` used to create the variables for your model.
- The names of the variables have to match on both sides for this to work properly.
- 
I'm not sure about specificities of `rust-bert` though so you may probably want to ask on their repo if they have some different setup.

**Comment by liebkne** [comment]
@LaurentMazare 

That helps a lot! Thank you! I've successfully converted my own BERT model using `tch-rs` and `rust-bert`!
