### ISSUE TITLE
data_ptr

### ISSUE THREAD

**Issue by pbridger** [LaurentMazare/tch-rs#163]
Hi,

Many thanks for this library - I really appreciate your work here.

I am doing some high-throughput video processing and would love for the Tensor::data_ptr function to be exposed so I can do some GPU->GPU copy to create a new Tensor. Any plans to add/expose this in the near term?

Cheers,
Paul

**Comment by pbridger** [comment]
Added a pull request.

**Comment by LaurentMazare** [comment]
Closing now that #164 has been merged, thanks again for the PR.
