### ISSUE TITLE
einsum

### ISSUE THREAD

**Issue by danieldk** [LaurentMazare/tch-rs#166]
I fear my OCaml knowledge is too outdated to appreciate the full details of the binding generator, but is there any particular reason why no binding for `einsum` is created? There is an entry for it in the declarations YAML file. I guess that this would be a nice function to have.

**Comment by LaurentMazare** [comment]
I just pushed some changes that add supports for einsum, thanks for suggesting this.
The changeset includes some [basic tests](https://github.com/LaurentMazare/tch-rs/commit/c631fc4b8bb22df1e10e2c1468e6302ffec8c870#diff-e75f2687d0f869be7557e55819187359) but let me know if you run into any issues.

**Comment by danieldk** [comment]
Thanks a lot! I was implementing a batched pairwise bilinear layer and this makes the implementation much simpler and far easier to read. Seems to work great so far!
