### ISSUE TITLE
cc unhappy

### ISSUE THREAD

**Issue by rustrust** [LaurentMazare/tch-rs#178]
probably related to https://github.com/pytorch/pytorch/issues/36437

i'm on a fresh install of ubuntu 20.04 LTS and have made an earlier version of tch-rs work on this system previously (prior to the fresh install) i've installed cuda using ```apt install nvidia-cuda-toolkit``` which is version 10.1 (verified with ```nvcc --version```) . i installed pytorch 1.5 for cuda 10.1 using pip3 via the command generated by the pytorch.org website. i checked not only that pytorch is installed and working on python3 but also that it can identify and name my GPU as a cuda device, and i also wrote a small snippet to allocate a cuda array using pytorch to verify all of that is working well. 

```
$nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
```
Python 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> x = torch.tensor([1., 2.]).cuda()
>>> y = torch.tensor([1., 2.]).cuda()
>>> x+y
tensor([2., 4.], device='cuda:0')
```

here are my paths:
```
$ echo $LIBTORCH
/home/u/.local/lib/python3.8/site-packages/torch
$ echo $LD_LIBRARY_PATH
/home/u/.local/lib/python3.8/site-packages/torch/lib:
```
curiously, i had forgotten to define these paths earlier and the compile worked but at runtime the gpu mode of the memory_test would fail at runtime. for the below, ```LIBTORCH``` and ```LD_LIBRARY_PATH``` are defined as above.

```cargo run --example memory_test cpu``` 

i get this wonderfully long error :
   Compiling torch-sys v0.1.7 (/home/u/src/rust/tch-rs/torch-sys)
   Compiling tch v0.1.7 (/home/u/src/rust/tch-rs)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.1ba9n1o7z6ejxk3x.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.1d9w531rvgp5ovco.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.1hzn4qqke3v9l62b.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.1y8ylkuw0khofna1.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.21jg7cmimljacd56.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.23hnvqw0i8ha67om.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.2557vhl121knxrfq.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.2g4i9gwk049v2zh5.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.2h3rlfym3xnw9u0k.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.2p8lplc7b4es5lpb.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.2rfbwnacttzx2sgn.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.2wdmjh1u1j863pm2.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.3n4xkz51rluoleda.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.3xwwwb06zb8p5fb7.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.4c0wabya8ko9qtey.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.4djjtuo79yjp6sn3.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.4jdsit20hx55v4ow.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.4rqtuj36ybyn0vx1.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.4tmidr2b2t37dz35.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.4zneslmkrno5lx2s.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.559vruqoj3ikr8fq.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.55ihc7j3340i2v30.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.5gj4m8k9r2v18bw9.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.69g9iodpduf8x1s.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.765dtzl7puo2bo.rcgu.o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.9f7oamasg6i8trh.rcgu.o" "-o" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539" "/home/u/src/rust/tch-rs/target/debug/examples/memory_test-8b10cedec6bf9539.583jmsul7xt84bub.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/u/src/rust/tch-rs/target/debug/deps" "-L" "/home/u/src/rust/tch-rs/target/debug/build/backtrace-sys-e64032bf80474062/out" "-L" "/home/u/.local/lib/python3.8/site-packages/torch/lib" "-L" "/home/u/src/rust/tch-rs/target/debug/build/torch-sys-82cd753269887489/out" "-L" "/home/u/src/rust/tch-rs/target/debug/build/bzip2-sys-9e51ea0a2c648812/out/lib" "-L" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/u/src/rust/tch-rs/target/debug/deps/libtch-6b87e11210aee552.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libndarray-56b380f3fc7bcd92.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libmatrixmultiply-c93b1d853ac778a4.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libnum_complex-4ab3f11a0d7607a2.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libnum_integer-fbbfbcd809e9f956.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libnum_traits-7de0e66da3207489.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librawpointer-6b2559903c793d0b.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand-39627070798af18f.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_xorshift-2d95acb918217269.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_pcg-5c7bb81ec5858109.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_hc-05b4e3aaa3ca7597.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_chacha-f6d6d133d1e2429f.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_isaac-87a3522d9899e447.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_core-fcae997235aac929.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_os-1ef5e147429785cb.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_jitter-1aa1f0cfd8878962.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librand_core-28bc7bb875414cbf.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libzip-398123a3f286fc14.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libtime-00f027bc8d88bc7f.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libbzip2-ce6ddddd402e7b22.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libbzip2_sys-4a131468d8c15f57.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libflate2-8a5a3fdfe561003c.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libminiz_oxide-f802c988852ccde4.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libadler32-94317d95f9e018d9.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libcrc32fast-fcfcbb1b8ea11568.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libpodio-e4a36d0bf2c86dd9.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libfailure-b71f99c80c93ecd0.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libbacktrace-e6663a176aa01a3d.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libbacktrace_sys-84f50c728ff418f5.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/liblibc-4eb3f80340108ae4.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/libcfg_if-587b52c05fffdc3c.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/librustc_demangle-8af209dc1f9ceaaf.rlib" "/home/u/src/rust/tch-rs/target/debug/deps/liblazy_static-5390404b369a64d3.rlib" "-Wl,--start-group" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7c5e456310a1373c.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-b981d9b2a408308f.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-43d0ea1b5ae34d0d.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-09e7f22e773899cd.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-aa74f166651adf6e.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-22c386707b639611.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-db04c9c5cd3bcf45.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bb27492f721492e8.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-6b95245dbf686e20.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-287409d75db2ecd3.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-a93f70ee2006b6e3.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-566cdfbcc94b4360.rlib" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-7bb8dddc7ce34e92.rlib" "-Wl,--end-group" "/home/u/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b117658e17259aa6.rlib" "-Wl,-Bdynamic" "-lstdc++" "-ltorch_cuda" "-ltorch" "-ltorch_cpu" "-lc10" "-lgomp" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil" "-Wl,--allow-shlib-undefined" "-fno-lto"
  = note: /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `c10::Device::validate()':
          /home/u/.local/lib/python3.8/site-packages/torch/include/c10/core/Device.h:96: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/.local/lib/python3.8/site-packages/torch/include/c10/core/Device.h:98: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `c10::dispatchKeyToBackend(c10::DispatchKey)':
          /home/u/.local/lib/python3.8/site-packages/torch/include/c10/core/Backend.h:98: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `c10::backendToDeviceType(c10::Backend)':
          /home/u/.local/lib/python3.8/site-packages/torch/include/c10/core/Backend.h:153: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/.local/lib/python3.8/site-packages/torch/include/c10/core/Backend.h:155: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o):/home/u/.local/lib/python3.8/site-packages/torch/include/c10/core/Layout.h:37: more undefined references to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `torch::zeros(c10::ArrayRef<long>, c10::TensorOptions const&)':
          /home/u/.local/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/generated/variable_factories.h:1625: undefined reference to `c10::Symbol::fromQualString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::retain_()':
          /home/u/.local/lib/python3.8/site-packages/torch/include/c10/util/intrusive_ptr.h:188: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> >::retain_()':
          /home/u/.local/lib/python3.8/site-packages/torch/include/c10/util/intrusive_ptr.h:188: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `c10::intrusive_ptr<c10::detail::ListImpl, c10::detail::intrusive_target_default_null_type<c10::detail::ListImpl> >::retain_()':
          /home/u/.local/lib/python3.8/site-packages/torch/include/c10/util/intrusive_ptr.h:188: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `c10::intrusive_ptr<c10::detail::DictImpl, c10::detail::intrusive_target_default_null_type<c10::detail::DictImpl> >::retain_()':
          /home/u/.local/lib/python3.8/site-packages/torch/include/c10/util/intrusive_ptr.h:188: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o): in function `c10::intrusive_ptr<c10::ivalue::ConstantString, c10::detail::intrusive_target_default_null_type<c10::ivalue::ConstantString> >::retain_()':
          /home/u/.local/lib/python3.8/site-packages/torch/include/c10/util/intrusive_ptr.h:188: undefined reference to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          /usr/bin/ld: /home/u/src/rust/tch-rs/target/debug/deps/libtorch_sys-bf3e1aa40e05ae5e.rlib(torch_api.o):/home/u/.local/lib/python3.8/site-packages/torch/include/c10/util/intrusive_ptr.h:188: more undefined references to `c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `tch`.

**Comment by LaurentMazare** [comment]
Could you try installing the C++ version of PyTorch as per the main readme of tch-rs to see if this improve things ? (I'm not sure whether the pip directory structure is close enough to the C++ one to get things to work)

**Comment by rustrust** [comment]
i installed libtorch C++ 1.5 for CUDA 10.1 and updated ```$LIBTORCH```. it works brilliantly now, thanks!

for others, i think the phrasing of the main readme could make that slightly more explicit, it looks like C++ is used as a descriptive modifier for pytorch (e.g. "pytorch is software which has been written in C++" rather than "install specifically libtorch, the C++ library for pytorch, and not pytorch itself"). the python install has shared object and header files so one expects it to include the C++ dependencies.
