### ISSUE TITLE
Serde support

### ISSUE THREAD

**Issue by elaye** [LaurentMazare/tch-rs#179]
Hello,

Thank you for this library, it's amazing to be able to use PyTorch in Rust!

I had to implement (de)serialization of `Tensor` / `Variables` for one of my projects using `serde`.
If it's something that you would be interested in adding to `tch-rs`, I could propose a PR.

**Comment by LaurentMazare** [comment]
Glad to hear that this crate is useful to you.
Not sure whether we would want to add a dependency to serde, but maybe making a small crate for this that would depend on both tch and serde would be nicer?

**Comment by elaye** [comment]
I understand your reluctance to add a dependency, however it can be put behind a feature flag so it becomes optional. That's what I did on my branch actually.
Also, making a separate crate to provide serde support for tch is harder because of the orphan rule.

**Comment by jerry73204** [comment]
Perhaps the [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html) could come in? We could make `serde` an optional dep regarding to your concern.

**Comment by jerry73204** [comment]
This is a `serde` example that is recently used in my project.
https://gist.github.com/jerry73204/09a74b92635ff954fde5a47adddc780c 

You can test the example against with the JSON text.
```json
{
    "tensor": {
        "requires_grad": true,
        "device": "cuda(0)",
        "shape": [2, 3],
        "data": {
            "float": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
        }
    },
    "kind": "uint8",
    "device": "cpu"
}
```

**Comment by jerry73204** [comment]
@elaye The feature is made into the [tch-serde crate](https://crates.io/crates/tch-serde). It might fit your needs.

**Comment by elaye** [comment]
Thank you @jerry73204 ! Actually I forked the repo and added the `Serialize` / `Deserialize` traits for Tensor, behind a feature flag. It doesn't cover all the use cases but it suits my needs. It's there if you're interested:
https://github.com/elaye/tch-rs/blob/master/src/wrappers/serde.rs

**Comment by LaurentMazare** [comment]
Closing this as handling it in a different crate seems to be a reasonable alternative for the time being.

**Comment by dbsxdbsx** [comment]
I wonder how is the status of Serilazation of Tensor at present? I 've a similar issue: https://github.com/LaurentMazare/tch-rs/issues/410, and I realized this feature when trying to save a vector of many tensors to disk:https://github.com/avl/savefile/issues/23.
