### ISSUE TITLE
Convert Tensor to Vec

### ISSUE THREAD

**Issue by cpcdoy** [LaurentMazare/tch-rs#180]
Hi,

I've been using your awesome lib for a few days now and I've been wondering what's the most efficient way to convert a Tensor of several dimensions `Tensor[n, m]` into a `Vec<Vec<f32>>`, or a similar form.

For reference, my use-case involves computing embeddings stored as Tensors using my library [rust-sbert](https://github.com/cpcdoy/rust-sbert) and then converting them into a more raw form to be able to send them through the network, for example using gRPC.

**Comment by LaurentMazare** [comment]
Thanks for your feedback, your rust-sbert crate seems pretty cool.
Re converting a tensor to `Vec<Vec<f32>>`, this should work with `Vec::<Vec::<f32>>::from(tensor)`, let me know if you have some issues using this.
Fwiw I just added a test to illustrate this in this [commit](https://github.com/LaurentMazare/tch-rs/commit/f88590adae54f2a861276bfc6a30965a7fe9bbaf).

Note that we also support conversion to/from ndarray which may be more efficient depending on your use case.

**Comment by cpcdoy** [comment]
Thanks for the feedback and the quick reply, this worked perfectly. I'll have to stick with Vecs for the library that I am using for now though
