### ISSUE TITLE
Pretrained Models examples generates incorrect labels for inception-v3

### ISSUE THREAD

**Issue by mhuttner** [LaurentMazare/tch-rs#188]
https://github.com/LaurentMazare/tch-rs/blob/master/examples/pretrained-models/main.rs

I tried running the example above, and it works as expected for resnet-18. 
```sh
Running `target/debug/pretrained-example resnet18.ot tiger.jpg`
tiger, Panthera tigris                             67.66%
tiger cat                                          31.50%
tabby, tabby cat                                    0.18%
zebra                                               0.08%
tarantula                                           0.06%
```
But running it with inception-v3 returns incorrect labels
```sh
     Running `target/debug/pretrained-example inception-v3.ot tiger.jpg`
mongoose                                           100.00%
great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias  0.00%
hammerhead, hammerhead shark                        0.00%
tench, Tinca tinca                                  0.00%
goldfish, Carassius auratus                         0.00%
```

I tried changing the image size to 299x299 (required by inception) by replacing
```rust
//let image = imagenet::load_image_and_resize224(image)?;
let image = imagenet::load_image_and_resize(image, 299, 299)?;
```
this changes the labels but they are still incorrect. 

I can also send the image if you want to reproduce this, but i tried multiple different example images and they are all correct using the resnet and incorrect using inception-v3. 

Thanks in advance, 
Michael

**Comment by LaurentMazare** [comment]
Thanks for catching this issue and reporting it, indeed I introduced a bug there a while back. I just pushed some fix for this to the master branch.
I get the following on my tiger image (I wonder if everyone actually uses tiger images for testing) with inception-v3 pretrained weights:
```
tiger, Panthera tigris                             98.86%
tiger cat                                           1.14%
jaguar, panther, Panthera onca, Felis onca          0.00%
leopard, Panthera pardus                            0.00%
lynx, catamount                                     0.00%
```

**Comment by mhuttner** [comment]
Can confirm this works correctly for me now.  
Thanks a lot for the quick response!
