### ISSUE TITLE
CPU and GPU profiling

### ISSUE THREAD

**Issue by cpcdoy** [LaurentMazare/tch-rs#190]
Hi,

I've been working on optimizing the inference speed of a PyTorch model that I ported to your crate and wanted to know your opinion on what's the recommended way of profiling the CPU and GPU part of code using `tch-rs`.

I'm fairly new to Rust and found a few different profiling libraries, for example, the Rust port of `Remotery` that can profile CUDA calls on GPU but actually needs the underlying CUDA context, etc, that Libtorch uses. But it's probably not a good idea to try extracting CUDA contexts, etc from Libtorch and doesn't seem safe.

**Maybe you know of some CPU and GPU profiling tools that work well in combination with your crate that you could recommend?**

Also, I've noticed that in Libtorch v1.5.0, the automatic profiling and optimization of the model graph have been disabled by default, but can be enabled again using `getProfilingMode() = true`, it can be found [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/graph_executor.h#L86) in Libtorch. This is all mentioned on the release [page of PyTorch](https://github.com/pytorch/pytorch/releases).

**Could it be possible to provide this function in your crate?**

Thank you

**Comment by LaurentMazare** [comment]
Sorry for the delay, somehow I only noticed this issue now. This would be fairly straightforward to add so I'm happy to make the change if you want. Would that still be useful to you?

**Comment by cpcdoy** [comment]
Sounds good to me

**Comment by LaurentMazare** [comment]
Ok, I just pushed some changes that should expose the `tch::jit::get_profiling_mode` and `tch::jit::set_profiling_mode` functions.
Let me know if you run into any issues using them.

**Comment by LaurentMazare** [comment]
Closing now that the change has been there for some time.
