### ISSUE TITLE
Tensor Indexing with Cuda/GPU Device

### ISSUE THREAD

**Issue by rustrust** [LaurentMazare/tch-rs#191]
I'm running a chunk of code taken from the tests and it looks like indexing isn't supported on the GPU backend.

I'd like to be able to use a Tensor to index into another Tensor with on a GPU device. That is to say, if tensor A = [3.0, 5.0], I would like to be able to access the 3rd and 5th elements of tensor B. Bonus points if I can increment B at those locations. Is there an option for this? I'm having trouble finding this in the documentation. Thanks!

```
extern crate tch;
use tch::{Tensor, Device};
use tch::{IndexOp};

fn main() {
    slice_index((tch::Kind::Float, Device::Cpu));
    slice_index((tch::Kind::Float, Device::Cuda(0)));
}

fn slice_index(opt: (tch::Kind, tch::Device)) {
    let tensor = Tensor::arange1(0, 6 * 2, opt).view([6, 2]);
    let index: &[_] = &[1, 3, 5];
    let result = tensor.i(index);
    result.print();
    assert_eq!(result.size(), &[3, 2]);
    assert_eq!(Vec::<i64>::from(result), &[2, 3, 6, 7, 10, 11]);

    let tensor = Tensor::arange1(0, 3 * 4, opt).view([3, 4]);
    let index: &[_] = &[3, 0];
    let result = tensor.i((.., index));
    result.print();
    assert_eq!(result.size(), &[3, 2]);
    assert_eq!(Vec::<i64>::from(result), &[3, 0, 7, 4, 11, 8]);
}
```
yields the following results:

   Compiling index_test_tch v0.1.0 (/home/username/src/rust/index_test_tch)
    Finished release [optimized] target(s) in 1.37s
     Running `target/release/index_test_tch`
  2   3
  6   7
 10  11
[ CPUFloatType{3,2} ]
  3   0
  7   4
 11   8
[ CPUFloatType{3,2} ]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TorchError { c_error: "Expected object of device type cuda but got device type cpu for argument #3 \'index\' in call to _th_index_select (checked_dense_tensor_unwrap at ../aten/src/ATen/Utils.h:72)\nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f4e3e69faaa in /home/username/src/deps/libtorch/lib/libc10.so)\nframe #1: <unknown function> + 0x39f5a19 (0x7f4e514d4a19 in /home/username/src/deps/libtorch/lib/libtorch_cuda.so)\nframe #2: <unknown function> + 0x39fbc03 (0x7f4e514dac03 in /home/username/src/deps/libtorch/lib/libtorch_cuda.so)\nframe #3: <unknown function> + 0x396877a (0x7f4e5144777a in /home/username/src/deps/libtorch/lib/libtorch_cuda.so)\nframe #4: <unknown function> + 0x39aa327 (0x7f4e51489327 in /home/username/src/deps/libtorch/lib/libtorch_cuda.so)\nframe #5: <unknown function> + 0x2c93c2a (0x7f4e41554c2a in /home/username/src/deps/libtorch/lib/libtorch_cpu.so)\nframe #6: <unknown function> + 0x11b2687 (0x7f4e3fa73687 in /home/username/src/deps/libtorch/lib/libtorch_cpu.so)\nframe #7: <unknown function> + 0x2a92a (0x55ef07edc92a in target/release/index_test_tch)\nframe #8: <unknown function> + 0x18edc (0x55ef07ecaedc in target/release/index_test_tch)\nframe #9: <unknown function> + 0x15ad7 (0x55ef07ec7ad7 in target/release/index_test_tch)\nframe #10: <unknown function> + 0x159f5 (0x55ef07ec79f5 in target/release/index_test_tch)\nframe #11: <unknown function> + 0x169d3 (0x55ef07ec89d3 in target/release/index_test_tch)\nframe #12: <unknown function> + 0x56883 (0x55ef07f08883 in target/release/index_test_tch)\nframe #13: <unknown function> + 0x58a07 (0x55ef07f0aa07 in target/release/index_test_tch)\nframe #14: <unknown function> + 0x572dc (0x55ef07f092dc in target/release/index_test_tch)\nframe #15: <unknown function> + 0x160b2 (0x55ef07ec80b2 in target/release/index_test_tch)\nframe #16: __libc_start_main + 0xf3 (0x7f4e3e41e0b3 in /lib/x86_64-linux-gnu/libc.so.6)\nframe #17: <unknown function> + 0x158be (0x55ef07ec78be in target/release/index_test_tch)\n" }', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.1.7/src/wrappers/tensor_generated.rs:3890:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by LaurentMazare** [comment]
Thanks for reporting this. Indeed the index tensors were only available on the cpu side, I just pushed a fix for this that should make your code work fine.
Re incrementing, the following seems to work fine but maybe I'm missing something?
```rust
    let tensor = Tensor::arange1(0, 3 * 4, opt).view([3, 4]);
    let index: &[_] = &[3, 0];
    let mut result = tensor.i((.., index));
    result += 1;
    result.print();
```

**Comment by rustrust** [comment]
Thanks, the fix worked!

However, regarding what I want to accomplish with the indexing, your example allows access to specific columns I don't see how to make it modify specific (row, column) entries. (I don't care about row/column ordering conventions here).

Suppose X is a 4x3 matrix containing entries {{9, 8, 7}, {6, 5, 4}, {3, 2, 1}, {0, -1, -2}}
Suppose Y is a 3x2 matrix containing entries {{3, 0}, {4, 1}, {0, 2}}
I would like to make the entries within X at (row, column) locations Y increment (or perform some other operation on them).
I suppose I need to flatten X or can I do this without flattening?
The entries of X located at Y are then {3, -1, 8}, so if I increment those entries I obtain:
incremented_X, a 4x3 matrix containing entries {{9, 9, 7}, {6, 5, 4}, {4, 2, 1}, {0, 0, -2}}

**Comment by LaurentMazare** [comment]
I'm actually unsure how to do this. `index_select` which the `.i` operator uses behind the hood only works with a single dimension at a time. Maybe some smart usage of [masked_select](https://pytorch.org/docs/master/generated/torch.masked_select.html) could do the trick but I don't see how.
Anyway if you find a way to do it with the python version of PyTorch, it should be easy to adapt to rust.

**Comment by rustrust** [comment]
I chekced the libtorch documents and they specify, for masked_select, that "The returned tensor does not use the same storage as the original tensor". This code is in a hot loop so I am looking to avoid reallocation.

**Comment by rustrust** [comment]
I'm marking this as closed but might open another issue for the ability to use one tensor to index another tensor for performing some operation or documentation on how to do that. Thanks for the quick fix!
