### ISSUE TITLE
Tensor index operation with reference to indices

### ISSUE THREAD

**Issue by rustrust** [LaurentMazare/tch-rs#193]
Currently I need to do this:
my_tensor_0.i(my_indices.clone());
my_tensor_1.i(my_indices.clone());

but I would like to avoid copying memory, so it would be nice if I could do something like this instead:
my_tensor_0.i(&my_indices);
my_tensor_1.i(&my_indices);

However I am having trouble finding how to do this in the tests etc. If it is indeed not possible to use a reference to the indices, is this a limitation of libtorch, or can the rust API be changed to make this possible?

Thanks!

**Comment by spebern** [comment]
> However I am having trouble finding how to do this in the tests etc
If I understand correctly you might be looking for `tests/tensor_indexing.rs`

Inside of the text index slices slices seem to work:
```rust
    let index: &[_] = &[1, 3, 5];
    let result = tensor.i(index);
```
Are you indexing with a tensor?
Could you provide a full code snippet?

**Comment by rustrust** [comment]
Here is a code snippet which should provide an adequate extraction of the problem from my codebase:

```
let opt = (tch::Kind::Float, Device::Cuda(0));
let my_indices = (0..100).collect::<Vec<_>>();
let mut my_tensor = Tensor::randn(&[100], opt);

for i in 0 .. 1000 {
    //my_tensor = my_tensor.i(first_third_index.clone()); // this compiles
    my_tensor = my_tensor.i(&my_indices); // this does not compile

    // ... 
}
```
I am getting this error when compiling:
```

error[E0277]: the trait bound `tch::TensorIndexer: std::convert::From<&std::vec::Vec<i64>>` is not satisfied
   --> src/main.rs:159:17
    |
159 |         my_tensor = my_tensor.i(&my_indices); // this does not compile
    |                     ^ the trait `std::convert::From<&std::vec::Vec<i64>>` is not implemented for `tch::TensorIndexer`
    |
    = help: the following implementations were found:
              <tch::TensorIndexer as std::convert::From<&[i64]>>
              <tch::TensorIndexer as std::convert::From<&tch::Tensor>>
              <tch::TensorIndexer as std::convert::From<i64>>
              <tch::TensorIndexer as std::convert::From<std::ops::Range<i64>>>
            and 7 others
    = note: required because of the requirements on the impl of `std::convert::Into<tch::TensorIndexer>` for `&std::vec::Vec<i64>`
    = note: required because of the requirements on the impl of `tch::IndexOp<&std::vec::Vec<i64>>` for `tch::Tensor`
```

**Comment by LaurentMazare** [comment]
What about trying to convert the `Vec` to a slice? e.g.:
```rust
my_tensor = my_tensor.i(&my_indices[..]);
```
or
```rust
my_tensor = my_tensor.i(my_indices.as_slice());
```
