### ISSUE TITLE
libtorch error when LD_LIBRARY_PATH is not set

### ISSUE THREAD

**Issue by lumost** [LaurentMazare/tch-rs#201]
When the LD_Library path isn't setup to point to a local pytorch install ( such as during clion builds/runs ) cuda calls fail with an error message such as 
```
TorchError { c_error: "Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason. .... 
```
From the docs it seems like a copy of pytorch is getting downloaded which isn't cuda compatible.  Is this intentional?

**Comment by LaurentMazare** [comment]
I'm not sure to understand what exactly the setup is in this case. Is `LIBTORCH` set?
If no local install of libtorch is found, the c++ library will indeed be downloaded from the pytorch servers. Though it could be a cuda version of it if `TORCH_CUDA_VERSION` is set.

**Comment by rustrust** [comment]
I still think that the wording of the README.md is confusing and leading people to install PyTorch (but not libtorch) and expect that libtorch was already included as a dependency. Please consider wording similar to this:

Rust bindings for libtorch, the C++ API of PyTorch. The goal of the tch crate is to provide some thin wrappers around the C++ libtorch api. 

This crate requires the C++ libtorch library (from PyTorch) in version v1.5.0 to be available on your system, which must be installed separately from PyTorch and is not included in the PyTorch distribution.

**Comment by rustrust** [comment]
Alternatively,

https://docs.rs/crate/vcpkg/0.2.9

https://github.com/microsoft/vcpkg/issues/5209

**Comment by lumost** [comment]
The other challenge when using this library is that the build may not present  deterministic behaviors if it does not receive the right environment variable during the right phase of the build and test process.  Would it be reasonable to set the automatic download behind a cargo feature flag? And or download a cuda enabled library?

**Comment by LaurentMazare** [comment]
This bit is certainly clunky, though I find that it works reasonably well as beginner users get things working out of the box and advanced users can set it up to use the exact libtorch they care about.
Did you encounter specific issues because of this?

**Comment by lumost** [comment]
aye - the behavior I found

1) Install libtorch following documentation
2) Setup project in CLion setting runtime environmental variables
3) Test with CPU
4) Switch to GPU and get missing cuda links
5) cargo clean/cargo run and get working code
6) retest in clion and get failures


Clion doesn't allow setting build time environmental variables, and the error is rather inscruitable.  This only affects testing with Cuda at present as the downloaded lib works fine with CPU.

**Comment by LaurentMazare** [comment]
When was this actually? I would have thought that #184 should trigger some automatic rebuild of the code if the environment variables changes so would have hoped for your step (5) not to be necessary anymore (this was released at the beginning of May).

**Comment by lumost** [comment]
This issue is still present today.  Would it be possible to have it auto-download a cuda enabled lib?

**Comment by LaurentMazare** [comment]
Is there a specific environment variable that does not trigger a rebuild? I don't have clion so having a repro that does not use this would certainly help.
It's possible to auto-download a cuda based version by setting the `TORCH_CUDA_VERSION` environment variables. You can try values like `cu92`, `cu101`, or `cu102` for cuda 9.2, 10.1, and 10.2 respectively (see `torch-sys/build.rs` for details).

**Comment by rustrust** [comment]
I think this issue can be closed. tch-rs works fine as long as libtorch is installed.

Special methods of handling the dependencies can be left for a post-1.0 version of tch-rs
