### ISSUE TITLE
upsample_* functions are not generated properly

### ISSUE THREAD

**Issue by SunDoge** [LaurentMazare/tch-rs#206]
Hi, when playing around with tch `0.1.7`, I found that all upsample_* functions are not generated properly.

Take `upsample_bilinear2d` as an example. According to python version,

```python
torch.nn.functional.upsample_bilinear(input, size=None, scale_factor=None)
```

and the cpp header:

```c
Tensor upsample_bilinear2d(const Tensor & self, IntArrayRef output_size, bool align_corners, c10::optional scales_h, c10::optional scales_w);
```

output size and scale hw should be nullable. But the generated rust code:

```rust
pub fn upsample_bilinear2d(
        &self,
        output_size: &[i64],
        align_corners: bool,
        scales_h: f64,
        scales_w: f64,
    ) -> Tensor
```

does not allow users to use `scales_h` and `scales_w`. There are two ways to fix it, by splitting it into `upsample_bilinear2d_size` and `upsample_bilinear_scales`, or changing the signature to 

```rust
pub fn upsample_bilinear2d(
        &self,
        output_size: Option<&[i64]>,
        align_corners: bool,
        scales_h: Option<f64>,
        scales_w: Option<f64>,
    ) -> Tensor
```

**Comment by LaurentMazare** [comment]
Right, I've just pushed some changes that turn the `scales_h` and `scales_w` parameters to `Option<f64>` as per your suggestion.
The case of `output_size` is a bit more involved: the rust api is automatically generated from this [yaml file](https://github.com/LaurentMazare/tch-rs/blob/master/third_party/pytorch/Declarations-v1.5.0.yaml) which is part of the build artifacts of pytorch. In this file, `scales_h` and `scales_w` are properly marked with `is_nullable: true` so we can easily convert these to options on the rust side. However this is not the case for `output_size` so it's a bit harder to know if we should allow that.

**Comment by SunDoge** [comment]
One possible workaround is to regard empty array `&[]` as `ptr::null()`, but I don't know if it is a good idea.

**Comment by SunDoge** [comment]
I checked the cpp and python code, the behavior is really confusing. The output size is computed using `scale_w` and `scale_h` if provided. My suggestion is not a good idea. Marking `scale_w` and `scale_h` as optional is enough. 

Thanks.
