### ISSUE TITLE
macos support

### ISSUE THREAD

**Issue by LaurentMazare** [LaurentMazare/tch-rs#21]
This may work out of the box but we should probably test this, fix if necessary, and add some specific CI integration if this starts becoming important.

**Comment by nilday** [comment]
--allow-shlib-undefined option is not defined on mac
remove it or you will get "note: ld: unknown option: --allow-shlib-undefined" error
simply remove it from .cargo/config, it work for me. 
I don't know if there is a better option.

**Comment by LaurentMazare** [comment]
Thanks for pointing this out. I added this `--allow-shlib-undefined` flag in order to get things to compile on some gpu configurations. Things have changed a bit since then so maybe it's not needed any more, I'll give it a try and remove the flags if not necessary.
Were you able to run the tests via `cargo test`, it would be pretty amazing if it just end up working with this small tweak on macos.

**Comment by nilday** [comment]
@LaurentMazare I think I can pass `cargo test`. It works well for me.

**Comment by LaurentMazare** [comment]
Fyi I just tweaked the cargo config file so that the `--allow-shlib-undefined` flag only applies to linux - this should hopefully make the default build work on mac.
