### ISSUE TITLE
`argmax` failes the test

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#210]
The `argmax` test passes with `cargo test` but fails with `cargo test --release` on my laptop, making it an interesting case for me. You can see the [screenshot](https://imgur.com/fDzr2Hp) for the line number. To recap, `argmax(None, false)` admits distinct results under debug or release mode.

**Comment by LaurentMazare** [comment]
Thanks for reporting this, this seems very odd indeed and a bit scary.
The handling of `None` has been added in the last few days as well as this test. Looking at the output of your screenshot, it's as if it was not using `None`.
I ran the test on a couple computer locally today without hitting this issue. Could you try re-running the tests after a `cargo clean`? (I weakly suspect that incremental compilation is not working properly when the generated c++ files change)

**Comment by jerry73204** [comment]
Yes, `cargo clean` effectively eliminates the error. So the crate does not regard the version of C++ API?

**Comment by LaurentMazare** [comment]
Yes, this was actually something that has been overlooked in the compilation process (rust gets the rust dependencies for you but doesn't help on the c++ dependencies), I just pushed some changes that should help with this by triggering a recompilation when needed.

**Comment by jerry73204** [comment]
Thanks! Let's close this issue.
