### ISSUE TITLE
Illegal Instruction 4 with Tensor::sum on OSX

### ISSUE THREAD

**Issue by vegapit** [LaurentMazare/tch-rs#212]
Hello,

I am encountering some brand new problems with `Tensor::sum` on MacOSX. 

```rust
extern crate tch;

use tch::{Tensor, Kind};

fn main() {
    let v = vec![1f64,2f64,3f64];

    let t_v = Tensor::of_slice( &v.as_slice() ).to_kind( Kind::Float );

    &t_v.pow(2).print();
    &t_v.sum( Kind::Float ).print();
}
```

The code above generates this:
```
   Compiling tchtut v0.1.0 (/Users/vegapit/dev/tchtut)
    Finished release [optimized] target(s) in 0.62s
     Running `target/release/examples/test`
 1
 4
 9
[ CPUFloatType{3} ]
Illegal instruction: 4
```

I am using the latest libtorch for mac (1.5.0) and the current git repository for tch.

**Comment by LaurentMazare** [comment]
As usual with macos issues, it's a bit hard for me to debug as I don't have access to a mac and this works fine on my linux. There are a couple entries on the pytorch repo about "Illegal instruction: 4", maybe some of them are related ([github link](https://github.com/pytorch/pytorch/issues?q=%22illegal+instruction+4%22))?
If you want to try and investigate this, running it under gdb would probably be a good first step.

**Comment by vegapit** [comment]
Oh dear, This is a pickle. The nightly mac version does not compile with `torch-sys v0.1.7` while the stable mac library comes up with runtime errors. 

The only thing left is to look into debugging libtorch and compile it from source, but this does not sound like a lot of fun. Thanks for the pointers in any case.
