### ISSUE TITLE
How to troubleshoot CUDA not working with tch (when it does under python)?

### ISSUE THREAD

**Issue by jdoig** [LaurentMazare/tch-rs#213]
I'm using a VM with a TeslaT4 and pytorch + tensorflow are working fine under python with the GPU and CUDA

    In [2]: torch.cuda.is_available()                                                                                                                                                                                            
    Out[2]: True

I can also see the GPU some under load via `nvidia-smi` and `gpustat` when I use tensorflow.

Switching over to rust and tch and I get

    println!("Cuda available: {:?}", Cuda::is_available());
    > false

How can I go about trouble shooting this?

Versions:
     NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2

**Comment by LaurentMazare** [comment]
How did you install libtorch? The automatic install is cpu only (unless you set some specific environment variables), if you want the gpu version you should probably follow these [steps](https://github.com/LaurentMazare/tch-rs#libtorch-manual-install) and download the appropriate gpu enabled libtorch.

**Comment by jdoig** [comment]
Thank you I was using the default install.

**Comment by jdoig** [comment]
My apologies, I had a typo in my paths to the libtorch library :(

**Comment by jdoig** [comment]
Ahh right I think I have sorted this: It needed to be the `(cxx11 ABI)` version. Thank you
