### ISSUE TITLE
How to implement ReLU and self.relu(self.bn(self.conv(x)))

### ISSUE THREAD

**Issue by lynkxyz** [LaurentMazare/tch-rs#216]
I want to implement this class in Python, but I don't know how to implement this in Rust. I also can't find `ReLU` in Rust.
```
classRebConv(nn.Module):
    def __init__(self):
        super(REBNCONV, self).__init__()

        self.conv= nn.Conv2d(3, 3, 3, padding=1 * dirate, dilation=1 * dirate)
        self.bn = nn.BatchNorm2d(3)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        return self.relu(self.bn(self.conv(x)))
```

**Comment by LaurentMazare** [comment]
Maybe you should start by looking at some of the existing examples, either in the `examples` directory, or in `src/vision`. There are also a bunch of tutorials that the main readme refers too.
E.g. a typical use of relu can be seen in the [resnet model](https://github.com/LaurentMazare/tch-rs/blob/master/src/vision/resnet.rs#L121).

**Comment by lynkxyz** [comment]
Thank you so much :D

**Comment by LaurentMazare** [comment]
Closing the issue for now, feel free to re-open if you have further questions.
