### ISSUE TITLE
Where is torch.nn.functional

### ISSUE THREAD

**Issue by lynkxyz** [LaurentMazare/tch-rs#217]
Is `torch.nn.functional` has implemented in Rust. I want to use the function `functional.interpolate`, but I can't find in the document. If it doesn't exist then how I can use this function. Thank you

**Comment by LaurentMazare** [comment]
If you look at the [pytorch implementation](https://pytorch.org/docs/stable/_modules/torch/nn/functional.html#interpolate), depending on its `mode` argument, `interpolate` ends up calling `upsample_nearestXd`, `avg_poolXd`, or some other variants. These functions are actually exposed (`avg_poolXd` is used in a bunch of the vision models, whereas the [yolo example](https://github.com/LaurentMazare/tch-rs/blob/master/examples/yolo/darknet.rs#L161) uses `upsample_nearestXd`) so you can probably call them directly.

**Comment by lynkxyz** [comment]
Thank you very much. I will try :D

**Comment by LaurentMazare** [comment]
Closing the issue for now, feel free to re-open if you have further questions.
