### ISSUE TITLE
reinforcement-learning  --features=python pg

### ISSUE THREAD

**Issue by intelligentnet** [LaurentMazare/tch-rs#220]
Example problem :

cargo run --example reinforcement-learning  --features=python pg
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/reinforcement-learning pg`
action space: 2
observation space: [4]
Error: PyErr { ptype: <class 'AssertionError'>, pvalue: Some(AssertionError("[1] (<class 'list'>) invalid")), ptraceback: Some(<traceback object at 0x7f7de394d7c0>) }

**Comment by LaurentMazare** [comment]
Thanks for reporting the issue, this was due to some openai gym python api changes, I've pushed some fixes which should get it to work with the latest version.

**Comment by intelligentnet** [comment]
Excellent, that works thank you
