### ISSUE TITLE
tensor.kind() panics when the tensor is returned from run_backward()

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#228]
It turns out that the tensor can report a dtype number that is not expected by tch's `Kind`.
I witness this issue when I setup a model on a `VarStore`, and fed the tensors to `VarStore` to `Tensor::run_backward`  as inputs.
Then, `dbg!` the gradients and the panic was triggered. ([screenshot](https://imgur.com/a/PkAMT7f))

It calls the `kind()` beneath and it panics on unexpected reported dtype number ([code](https://github.com/LaurentMazare/tch-rs/blob/c1049b06890ff1e5794b7cdc426e893651d94edf/src/wrappers/kind.rs#L40-L56)). Suppose we could add a variant to prevent the panic.

**Comment by LaurentMazare** [comment]
Thanks for reporting this issue, this seems pretty bad indeed.
Would you have a small repro to trigger this? Looking at the PyTorch C++ code, I don't see dtype 16 being used (only numbers up to 15 seem to be), so I would like to understand better where this comes from.

**Comment by jerry73204** [comment]
I attempted to reproduce this error on `tch::vision` but nothing bad happened. Actually, I encountered this issue on my [gqnrs](https://github.com/jerry73204/gqnrs), which is undergoing great refactoring. So let me present the minimal input/output that trigger this issue.


The `Cargo.toml`.
```toml
[package]
name = "issue"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
tch = "0.1"
gqnrs = { git = "https://github.com/jerry73204/gqnrs.git" }
```

The `main.rs`.

```rust
use tch::{kind::FLOAT_CUDA, nn, Device, Tensor};

fn main() {
    let bsize = 1;
    let param_channels = 7;

    let device = Device::cuda_if_available();
    let vs = nn::VarStore::new(device);
    let root = vs.root();
    let model = gqnrs::model::GqnModel::<gqnrs::model::TowerEncoder>::new(&root, 3, 7);
    let input = gqnrs::model::GqnModelInput {
        context_frames: Tensor::randn(&[bsize, 7, 3, 224, 224], FLOAT_CUDA),
        target_frame: Tensor::randn(&[bsize, 3, 224, 224], FLOAT_CUDA),
        context_params: Tensor::randn(&[bsize, 7, param_channels], FLOAT_CUDA),
        query_params: Tensor::randn(&[bsize, param_channels], FLOAT_CUDA),
        step: 0,
    };
    let output = model.forward_t(input, true);
    dbg!();

    let grads = Tensor::run_backward(
        &[&output.elbo_loss],
        &vs.trainable_variables(),
        false,
        false,
    );

    grads.iter().for_each(|tensor| {
        println!("{:?}", tensor);
    });
}
```

**Comment by jerry73204** [comment]
I guess some specific operation leads to this error. I would dig into the model layer by layer. For now I cannot give the actual cause. I guess `Tensor::normal_out2()` does the mess.

**Comment by LaurentMazare** [comment]
Thanks for the details, I also gave a try to using `normal_out2` without being able to reproduce the issues easily. Anyway I just pushed some tweaks that would prevent this from panicking in the `Debug` trait, instead the tensor shape and the error should be reported.
Even if this is not ideal, hopefully this will make things easier when debugging models involving such tensors. The error is also handled in a more gentle way at a couple other places now.

**Comment by jerry73204** [comment]
After hours of hard work, I figured out the hassle. By computing the gradient of y with x that never reaches y, the corresponding grad tensor will have an eerie dtype. In my gqnrs case, I take the weights from the last LSTM cell, which output never reaches to the loss. It effectively kills my program. Below is the minimal reproduction.

```rust
mod tests {
    use super::*;

    #[test]
    fn grad_test() {
        let vs = VarStore::new(Device::cuda_if_available());
        let root = vs.root();
        let x = root.var("x", &[], Init::KaimingUniform);
        let y = root.var("y", &[], Init::KaimingUniform);
        let z = root.var("z", &[], Init::KaimingUniform);
        let w = &x * &y;
        let grads = Tensor::run_backward(&[&w], &[&x, &y, &z], true, true);
        dbg!(grads);
    }
}
```

I previously expected `dy/dx` turns to zero if y has nothing to do with x. I wonder how builtin optimizer reads the `VarStore` and does not suffer from this issue.

**Comment by LaurentMazare** [comment]
Ah that certainly explains it, the tensor is actually undefined. I tweaked the debug function so that it actually checks for that and return an appropriate representation when this happens, this should make this kind of things easier to investigate.

**Comment by jerry73204** [comment]
`Tensor::to_device()` also panics on undefined tensor, and it can be handled by existing `f_to_device()`.
Making `Tensor::kind()` return a result will introduce great changes on existing code. We could instead have `f_kind()` and let `kind()` do as it is.
