### ISSUE TITLE
Can `Optimizer` be `Send`?

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#229]
Seen in [docs.rs](https://docs.rs/tch/0.1.7/tch/nn/struct.Optimizer.html#impl-Send), the `Optimizer` type does not implement `Send`. It could be if the optimizer does not owns nothing that is local to thread.

There is a simple workaround is by wrapping the mutex `Arc<Mutex<Optimizer>>`. Rather, I'm in a more complicated situation that I place the optimizer in an asynchronous block. For example,

```rust
let (tx, rx) = tokio::sync::mpsc::channel(CHANNEL_SIZE);
// suppose a separate worker feeding data into tx 
// omit...

// here rx is owned by the training worker
tokio::spawn(async move {
    let vs = VarStore::new();
    let model = some_model(vs.root());
    let mut opt = Adam::default().build(&vs, 1e-3);

    while let Ok(input) = rx.recv().await {  // rx is the receiver side of a channel
        let output = mode.forward_t(&input, true);
        opt.backward_step(&output);
    }
}).await;
```

The compiler complains that the future block `async move { ... }` is not `Send`. That's because `rx.recv().await` could cause the thread to do a (userspace) context switch, then the future maybe picked up by another thread later. In this situation, `Arc<Mutex<_>>` will not work. It's required that every local variable to the future is `Send`.

**Comment by LaurentMazare** [comment]
I've made the coptimizer struct send, which should result in Optimizer being send too.
Not sure about what your `Arc<Mutex<T>>` thing, my understanding was that this is useful to get something `Sync` but doesn't help with `Send` as it requires the underlying type `T` to be `Send`, but maybe I'm missing something here.

**Comment by jerry73204** [comment]
I got confused it a bit from the [std doc](https://doc.rust-lang.org/std/sync/struct.Mutex.html#impl-Send) and realized `Mutex<T>` is conditionally `Send` on `T`. So please dismiss my erroneous statement.

BTW, thanks for your changes. We could close the issues.
