### ISSUE TITLE
TensorLike derive macro

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#230]
I recently worked on [tch-tensor-like](https://github.com/jerry73204/tch-tensor-like) that encapsulates custom types with `.to_device()` and `.shallow_clone()`, which recursively applies on member tensor types. Do you consider adding this feature to tch?

```rust
use tch_tensor_like::TensorLike;

#[derive(TensorLike)]
struct ModelInput {
    pub images: Vec<Tensor>,
    pub kind: Tensor,
    pub label: Option<Tensor>,
}

let input: ModelInput = fetch_data();
let input = input.to_device(Device::cuda_if_available())
                 .to_kind(Kind::Float)
                 .shallow_clone();
```

**Comment by LaurentMazare** [comment]
I'm not sure, I would be a bit afraid of craming more functionalities like this without knowing if they will end up being used (as it's hard to remove them after that). Is there any reason not to do this in a small separate crate? (and if it ends up being a problem for some users that it's separate somehow we can revisit)

**Comment by jerry73204** [comment]
I agree. It could be fine to let users import this crate only when needed. It would be convenient for those working with complex inputs/output types like [this](https://docs.rs/rust-bert/0.7.10/rust_bert/bert/struct.BertModel.html#method.forward_t) in rust-bert.

Perhaps we could set up an _awesome-tch_ page that help visitors discover useful crates, and enumerate others' works on tch?

**Comment by LaurentMazare** [comment]
Closing this for now, feel free to re-open depending on how the external crate implementation goes.
