### ISSUE TITLE
On optional paramters API

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#231]
I noticed the recent generated binding has `Option<T>` type for optional arguments ([example](https://imgur.com/VZrWICx)). I think it's a good move toward clean API. Let me put some retrospection on the change.

It can be further improved by the `impl T` rust feature. For example,
```rust
pub fn upsample_nearest2d(
    &self,
    output_size: &[i64],
    scales_h: impl Into<Option<f64>>,
    scales_w: impl Into<Option<f64>>
) -> Tensor
```
In this way, user can call either by `upsample_nearest2d(size, None, None)` or `upsample_nearest2d(size, 1.5, 1.5)`. We can avoid the writing of `Some(1.5)` in arguments.

**Comment by LaurentMazare** [comment]
Right, that sound like a reasonable change. I just pushed some tweaks to the code generation to enable this, overall it feels indeed a bit nicer.

**Comment by LaurentMazare** [comment]
Closing this as this has now been released.
