### ISSUE TITLE
Breaking changes in upcoming tch-rs version

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#236]
Hello,

I noticed in your latest commit to master (https://github.com/LaurentMazare/tch-rs/pull/235) that you have increased the version of `tch-rs` to 0.1.8. Since 0.1.7, a number of breaking changes have been introduced (addition of optional fields) that would be breaking changes for the libraries using `tch`.

This commit for example changes the input type for a number of basic operations: https://github.com/LaurentMazare/tch-rs/commit/eeb12a562a21c760e4b5f0e15ae7559bc860d806

Could you please increase the version to 0.2.x for the next release of the library on crates.io to avoid breaking dependent crates?

**Comment by LaurentMazare** [comment]
Sure, I've bumped the version number to 0.2.0.

**Comment by guillaume-be** [comment]
Thank you, looking forward to the next release!
