### ISSUE TITLE
Grad enabled closure?

### ISSUE THREAD

**Issue by GigglingRagdoll** [LaurentMazare/tch-rs#239]
First off, thanks for the great work! I just happened to see a Reddit post about tch-rs and it convinced me to start learning Rust! I started porting RevTorch as a means of learning but I've hit a snag. Since reversible architectures don't need to preserve activations in the forward pass, a lot of the computations are done within the no_grad closure and thus have no gradient. This makes it necessary to temporarily enable gradients as needed for backpropagation. The problem is, there doesn't seem to be a convenient way to wrap code in a block to temporarily enable gradients like there is one for disabling gradients. Is there a better way than having to manually enable and then re-disable gradients on variables?

**Comment by LaurentMazare** [comment]
I just added an equivalent to `no_grad` called `with_grad` that enables gradient tracking to run a closure. So you can in a closure called within `no_grad` call `with_grad` to temporarily enable gradient tracking. Hopefully this will help for your use case.

**Comment by GigglingRagdoll** [comment]
Thanks, that should do nicely!
