### ISSUE TITLE
LSTM options

### ISSUE THREAD

**Issue by a-rodin** [LaurentMazare/tch-rs#24]
Hi Laurent!

In `libtorch` it is possible to [provide options to an `LSTM` object](https://pytorch.org/cppdocs/api/classtorch_1_1nn_1_1_l_s_t_m_impl.html#classtorch_1_1nn_1_1_l_s_t_m_impl), such as [`with_bias`](https://pytorch.org/cppdocs/api/structtorch_1_1nn_1_1detail_1_1_r_n_n_options_base.html#_CPPv4N5torch2nn6detail14RNNOptionsBase9with_biasERKb).

However, it is not clear how to do the same in `tch`: [constructor for `LSTM`](https://docs.rs/tch/0.0.7/tch/nn/struct.LSTM.html?search=#method.new) seems to have a config parameter, but the config type is generic and doesn't seem to support setting RNN-specific options.

**Comment by LaurentMazare** [comment]
Hi,
Thanks for reporting this, the `with_bias` field was present but not exposed publicly. I've just pushed some changes to fix this so if you use the latest github tip, you should be able to do the following:
```rust
    let cfg = tch::nn::RNNConfig {                                                                                                      
        has_biases: false,                                                                                                              
        ..Default::default()                                                                                                            
    };                                                                                                                                  
    let lstm = nn::LSTM::new(&vs.root(), labels, HIDDEN_SIZE, cfg);                                                                     
```
(this is adapted from the [char-rnn example](https://github.com/LaurentMazare/tch-rs/blob/master/examples/char-rnn/main.rs))
Let me know if you find further issues.

**Comment by a-rodin** [comment]
Now it works, thank you!
