### ISSUE TITLE
Train a model defined in Torchscript?

### ISSUE THREAD

**Issue by MichaelBurge** [LaurentMazare/tch-rs#242]
Hello,

Is there a way to train a Torchscript model in Rust? Specifically:
1. Define a model in Python and export to Torchscript using `torch.jit.script(module).save("something.pt")`.
2. Load the exported arch/weights in Rust using `tch::CModule::load`. This allocates tensors on the device and also loads them with weights.
3. Train the module in Rust.
4. Save the weights into a similar .pt file while otherwise keeping the same architecture.

It looks like `tch::nn::VarStore` might be useful for this, but I'm not sure if it tracks all exported variable names or only variables defined using helpers in the `tch::nn` namespace.

Also, separately, Torchscript lets you define multiple entry-point functions on an exported module, and `tch` uses the `forward` method by default. Is there a way to specify an alternate entry-point?

**Comment by LaurentMazare** [comment]
I don't training a torchscript model is possible at the moment and a bit unsure on how easy this would be to add. https://github.com/pytorch/pytorch/issues/17614 tends to indicate that this can be done as the module embeds all the information on the backward pass, we would just need to add wrappers around calling backward for such modules - I'll give this a try when I get a chance (saving the output to the .pt file would also requires some wrappers but shouldn't be hard).

On multiple entry-points, I just added two new functions `method_ts` and `method_is` on `CModule` that should let you access arbitrary entry points by specifying their names. Let me know if you run into any issues using these.

**Comment by MichaelBurge** [comment]
Thanks! This is for reinforcement learning, where I want to do inference + environment + training all in Rust, but I also want the ability to export the Torchscript modules to ONNX for inference which supports many exotic hardware devices.

I think it's more complicated to export an architecture defined in Rust, but also unnecessary if I can define it in Python and just change the weights from Rust.

**Comment by LaurentMazare** [comment]
#278 has added a tutorial showing how to train a TorchScript based model from Rust, the example can be found [here](https://github.com/LaurentMazare/tch-rs/tree/master/examples/jit-train). Hopefully this can be adapted to fit your use case too!

**Comment by LaurentMazare** [comment]
Closing this for now, feel free to re-open if you still run into some issues.
