### ISSUE TITLE
Confusing error message when loading weights

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#247]
Hello,

When loading weights using a VarStore's `load` method I received an error which I believe may be misleading. The file I attempted to load did not contain all of the weights registered in the varstore, therefore triggering the Error creation at https://github.com/LaurentMazare/tch-rs/blob/8e6d15aefec9856d1d57fc8bae0e813095672ca6/src/nn/var_store.rs#L130 

This error is a `TchError::FileFormat` with an error message "Error: invalid file format: cannot find X in Y". At first I was not sure if this was an issue of corrupted file (e.g. missing headers) or a mismatch in the variables to load.

Would you be open to create a error type for these (common) variable loading mismatches to make it more clear that the file format is correct, but not all required variables are present? Pytorch returns a `RuntimeError`, which is also not ideal - maybe a `ValueError` of some sort would be more adequate?

**Comment by LaurentMazare** [comment]
Right, an "invalid file format" error here indeed seems confusing. I've added a new error type to cover this case with a more appropriate error message.

**Comment by guillaume-be** [comment]
Thank you this is great!
