### ISSUE TITLE
Using Einsum with references

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#248]
Hello,

I'd like to implement a layer relying on an einsum operation, as defined here:
https://github.com/LaurentMazare/tch-rs/blob/4d27ba89c52e08bd440e4f2be4c2e8e6068b893c/src/wrappers/tensor_generated.rs#L2924

I'd like to perform the operation on references to tensors, instead of tensors themselves. The reason is that one of the tensor of the einsum will be a field of a layer, and I don't want to copy it for every operation. I do not manage to perform the einsum operation

```rust
let ef = Tensor::einsum("ibnd,snd->ibns", &[&input, &self.parameter]);
```

where `parameter` is a `Tensor` in a layer, and input a `Tensor` passed to the layer as an input.

Is there a reason the einsum function requires actual tensors as an input rather than references? Am I missing an obvious workaround avoiding the copy of `&self.parameter`?

Thanks!

**Comment by LaurentMazare** [comment]
Hello,
I'm not sure to understand what the issue is here, if I try compiling the following code it works fine:
```rust
struct Foo {
    parameter: Tensor,
}

impl Foo {
    fn go(self, input: Tensor) -> Tensor {
        let ef = Tensor::einsum("ibnd,snd->ibns", &[&input, &self.parameter]);
        return ef;
    }
}
```

Maybe I'm missing something here?
Fwiw tensors being a slice of `T` where `T` is a `Borrow<Tensor>`, using a slice of tensor references should work fine. What is not supported is having a slice that contains both tensor references and tensors.

**Comment by guillaume-be** [comment]
Hello,

You are absolutely right, I guess got confused by the compiler who was indicating I can only pass tensors (and not references) to the method - while the issue was to pass a combination of tensors and references.

Thank you for the fast answer - apologies for the issue that was trivial!
