### ISSUE TITLE
Obsolete example in README.md

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#25]
Hi I'm new to tch, and the Rust implementation is amazing. I took some time to write tch code, and found the  example in "Writing a Simple Neural Network" section cannot compile. Simply the argument list of `nn::linear` is wrong. It expects additional LinearConfig type parameter, and first argument should have nn::Path type instead of nn::VarStore.

Another mild suggestion is that please make the example complete. At least include the `extern crate tch;` and a very simple main function. That would be a great help for newbies.

**Comment by LaurentMazare** [comment]
Thank you for your feedback, I've tweaked the readme to include both a very simple example of tensor manipulation and a fixed/standalone version of this example.

**Comment by jerry73204** [comment]
Nice! The issue can be closed.
