### ISSUE TITLE
Allow multiple input on forward() function

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#26]
The [forward](https://docs.rs/tch/0.0.8/tch/nn/trait.Module.html#tymethod.forward) function only allows single tensor. It cannot fit the need of multiple input models. I looked [PyTorch example](https://discuss.pytorch.org/t/multiple-input-model-architecture/19754/2) and it allows to pass a list of tensors. For example, we can provide `forward(&[&Tensor])` for this purpose.

**Comment by LaurentMazare** [comment]
I actually feel that this restriction is ok: the `forward` method for the `Module` trait has this signature, however there is no need for your model to actually implement this trait. E.g. you can do something like the following for your example (I haven't tried compiling the code so it's likely that you will have to tweak some bits, the dimensions are quite clearly wrong too).

```rust
struct Net {
    conv1: nn::Conv2D,
    conv2: nn::Conv2D,
    fc1: nn::Linear,
    fc2: nn::Linear,
}

impl Net {
    fn new(vs: &nn::Path) -> Net {
        let conv1 = nn::conv2d(vs, 1, 32, 5, Default::default());
        let conv2 = nn::conv2d(vs, 1, 32, 5, Default::default());
        let fc1 = nn::linear(vs, 1024, 1024, Default::default());
        let fc2 = nn::linear(vs, 1024, 10, Default::default());
        Net {
            conv1,
            conv2,
            fc1,
            fc2,
        }
    }

    fn forward(&self, x1: &Tensor, x2: &Tensor) -> Tensor {
        let x1 = x1.view(&[-1, 1, 28, 28])
            .apply(&self.conv1)
            .max_pool2d_default(2);
        let x2 = x2.view(&[-1, 1, 28, 28])
            .apply(&self.conv2)
            .max_pool2d_default(2);
        Tensor::cat(&[x1, x2])
            .view(&[-1, 1024])
            .apply(&self.fc1)
            .relu()
            .apply(&self.fc2)
    }
}
```

**Comment by jerry73204** [comment]
After looking into the docs, tch's Module is quite different from PyTorch's interface, so I agree your statement.
I see PyTorch provides some module level functionalities, such as `[parameters()](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.parameters)`. I don't need this in short future. Maybe we can keep it in the radar if it's needed some day.

**Comment by LaurentMazare** [comment]
Yes the api are a bit different here. `tch` tries to be a bit more explicit, you should use a `VarStore` to group your parameters. Making the api closer to python may actually not be very idiomatic in rust as it relies quite a bit on inheritance/object oriented aspects.

**Comment by LaurentMazare** [comment]
Closing this one for now as I don't see any immediate actionable point. If you can think on way to improve the documentation for this, or generic ways to handle multiple tensors as inputs, happy to get more issues/PRs on this.

**Comment by jackhhchan** [comment]
Hi, does this mean we can't use pytorch nn.Modules where it expects 2 arguments in the forward() function when it's compiled into a TorchScript module?

**Comment by LaurentMazare** [comment]
Multiple values for input or output of TorchScript modules should be supported, you can find some examples in the tests, e.g. [the python function definition](https://github.com/LaurentMazare/tch-rs/blob/e18648b69e53c8a7803e3d5d25381d358202a692/tests/create_jit_models.py#L21) and [call from rust](https://github.com/LaurentMazare/tch-rs/blob/e18648b69e53c8a7803e3d5d25381d358202a692/tests/jit_tests.rs#L32) (returning multiple  tensors from the TorchScript function should also be supported).

**Comment by jackhhchan** [comment]
that works, thank you!
