### ISSUE TITLE
Mismatched type error regression

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [LaurentMazare/tch-rs#264]
When compiling on an arm arch I am getting:

```rust
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1285ae84e5963aae/tch-0.2.1/src/wrappers/jit.rs:312:13
    |
312 |             buffer_ptr,
    |             ^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
```

I believe this is a regression of #175 and that this line:

https://github.com/LaurentMazare/tch-rs/blob/ca49ae0b8de28f49144c97c559aa050ba8184d19/src/wrappers/jit.rs#L310

Should read:

```rust
let buffer_ptr = buffer.as_ptr() as *const libc::c_char;
```

As it does on https://github.com/LaurentMazare/tch-rs/blob/ca49ae0b8de28f49144c97c559aa050ba8184d19/src/wrappers/jit.rs#L295

Git blame suggests that this line was introduced shortly after the fix in this [commit](https://github.com/LaurentMazare/tch-rs/commit/fb218a15132dfe7de3712bb62a992bea92222404) and was therefore missed.

**Comment by LaurentMazare** [comment]
Ah right, thanks for catching this, I just pushed a fix as per your suggestion.
