### ISSUE TITLE
Implement Tensor::chunk

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#27]
tch-rs does not provide [torch.chunk](https://pytorch.org/docs/stable/torch.html#torch.chunk). Look like it's missing in `f_*` functions. The backend seems to be generated by automated means and I would like to follow the convention, so I don't know how to make proper patches for this. Can you implement it or tell me how to make contributions?

**Comment by LaurentMazare** [comment]
Indeed *chunk* is not handled properly by the code generation part as it only supports functions that return a fixed number of tensors - whereas *chunk* is one of the rare function from the C++ backend that can return an arbitrary number of tensor.
The relevant bit in the ocaml code generator can be seen [here](https://github.com/LaurentMazare/tch-rs/blob/03c514f065cf7696cca8f58d40878836f64627a9/gen/gen.ml#L304-L316).
It's not entirely straightforward to support as currently the array of returned tensor is allocated on the rust side hence knowing the proper size helps and it's probably the most complicated part of the bindings, I'll give it a try today or tomorrow and will let you know.

**Comment by jerry73204** [comment]
Thanks a lot!
