### ISSUE TITLE
VarStore loading from file

### ISSUE THREAD

**Issue by vegapit** [LaurentMazare/tch-rs#280]
I have just upgraded to Pytorch 1.7 and I can not load VarStore from files:

```rust
let mut vs = nn::VarStore::new( Device::Cpu );
vs.load( "./model.tch" ).expect("VarStore load failed"); // Previously saved using vs.save method
println!("{:?}", vs.len()); // returns 0
println!("{:?}", vs.is_empty()); // returns true
```

Am I doing something wrong or is that a genuine issue?

**Comment by LaurentMazare** [comment]
That's weird, the tests run fine and they include saving a varstore then loading it. I was also able to run some pre-trained models loading a varstore that was saved using an older version of pytorch.

Also running the following code based on yours worked fine for me.
```rust
    let mut vs = nn::VarStore::new(Device::Cpu);
    let _v = vs.root().sub("a").sub("b").ones("t2", &[3]);
    vs.save("./model.tch");
    vs.load("./model.tch").expect("VarStore load failed"); // Previously saved using vs.save method
    println!("{:?}", vs.len()); // returns 0
    println!("{:?}", vs.is_empty()); // returns true
```

**Comment by vegapit** [comment]
It is very strange and very frustrating indeed. In your example the same instance of the `Varstore` struct is being called so you are not relying on the `load` method to work. Best to assign the loading and saving to 2 different scopes like such:

```rust
fn saver() {
    let mut vs = nn::VarStore::new(Device::Cpu);
    let _v = vs.root().sub("a").sub("b").ones("t2", &[3]);
    vs.save("./model.tch");
    println!("Saver: {:?}", vs.len());
}

fn loader() {
    let mut vs = nn::VarStore::new( Device::Cpu );
    vs.load("./model.tch").expect("VarStore load failed");
    println!("Loader: {:?}", vs.len());
}

fn main() {
    saver();
    loader();
}
```

When I run this, I am getting the following output which suggests the loading stage is not working:
```
Saver: 1
Loader: 0
```

This is done on OSX with libtorch 1.7 and the current git repo. I am also using with the nightly release of the Rust compiler. It could be a very sneaky problem in my config if it is working fine on Linux.

**Comment by LaurentMazare** [comment]
The output you're getting is expected and the same thing happens on linux. When you load a varstore, only the values for variables that have been added to it are updated, no new variable is created, as per the [documentation](https://docs.rs/tch/0.2.1/tch/nn/struct.VarStore.html#method.load). You can tweak it as per the following to check the variable "a.b" properly gets loaded.
```rust
fn saver() {
    let mut vs = nn::VarStore::new(Device::Cpu);
    let _v = vs.root().sub("a").sub("b").ones("t2", &[3]);
    vs.save("./model.tch").expect("VarStore save failed");
    println!("Saver: {:?}", vs.len());
}

fn loader() {
    let mut vs = nn::VarStore::new(Device::Cpu);
    let v = vs.root().sub("a").sub("b").ones("t2", &[3]);
    vs.load("./model.tch").expect("VarStore load failed");
    println!("Loader: {:?}", vs.len());
    v.print();
}

fn main() {
    saver();
    loader();
}
```
(again this is covered by the tests, so running a `cargo test` should also fail if there are issues with this)
If you want to load all the tensors in a file without creating the varstore variables beforehand, you can give a try to [Tensor::load_multi](https://docs.rs/tch/0.2.1/tch/struct.Tensor.html#method.load_multi).

**Comment by vegapit** [comment]
You are right, tweaked the test and I do get the same value for the variable after the `load` method has been called. The bug is then on my side which is a relief. Thank you.
