### ISSUE TITLE
SIGSEGV at tch::vision::image::resize when tensor is on CUDA

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#286]
I found `tch::vision::image::resize()` segfaults on tensors on CUDA. This is the minimal reproducing code. Perhaps we get the device checked?

```rust
let image = tch::vision::image::load(image_file)?
    .to_device(Device::Cuda(0));
tch::vision::image::resize(image, inner_w, inner_h)?
```

**Comment by LaurentMazare** [comment]
Thanks for pointing this out. I've just pushed some small tweaks so that this is properly check and return an error rather than segfaulting.

**Comment by jerry73204** [comment]
Thanks to your fix. The issue can be closed.

**Comment by dbsxdbsx** [comment]
Seems like this `resize` can not "rescale" image, is there a better way to do so?

**Comment by LaurentMazare** [comment]
Not sure what you mean here, `resize` should actually rescale/stretch the image. You can find other variants that preserve the aspect ratio (e.g. to process images for models expecting imagenet 224x224) in the same [module](https://github.com/LaurentMazare/tch-rs/blob/e260334a81e0d819f380749fe766f3f1922df8ad/src/vision/image.rs#L47).

**Comment by dbsxdbsx** [comment]
> Not sure what you mean here, `resize` should actually rescale/stretch the image. You can find other variants that preserve the aspect ratio (e.g. to process images for models expecting imagenet 224x224) in the same [module](https://github.com/LaurentMazare/tch-rs/blob/e260334a81e0d819f380749fe766f3f1922df8ad/src/vision/image.rs#L47).

Thanks for your reply.   I guess `resize` is what I need, because I need to resize an image to arbitrary size.
I don't know what is wrong before. Yesterday, I tested with `resize`, and it went wrong, popping issue that I need to resize the image with same number of pixels.  But today, this issue disappeared.

But another issue:
```rust
fn main() {
    let buf = include_bytes!(r"D:\MEDIA\PICTURE\girl.jpg");
    // failed to open saved image
    let image_t = tch::Tensor::of_data_size(buf, &[256, 256, 3], tch::Kind::Uint8).to_kind(tch::Kind::Float);
    image_t.save("resize_1.png").unwrap();

    // failed to open saved image
    let image_t = load_and_resize_from_memory(buf, 60, 60).unwrap();
    image_t.save("resize_2.png").unwrap();

    // failed to open saved image
    let image = tch::vision::image::load(r"D:\MEDIA\PICTURE\girl.jpg").unwrap();
    let out_image = tch::vision::image::resize(&image, 60, 60).unwrap();
    out_image.save("resize_3.png").unwrap();
}
```
The saved image of the code can't be opened. I don't know why.

**Comment by LaurentMazare** [comment]
My guess is that the call to `include_bytes!` here gives you the bytes for the jpg version of the file so it's still compressed and not the expected chw format. Using `tch::image::load` or `tch::image::load_and_resize` instead should give a proper tensor.
