### ISSUE TITLE
Setting quantization engine

### ISSUE THREAD

**Issue by calmdown13** [LaurentMazare/tch-rs#287]
Hello,

I am interested in using tch-rs to run inference on arm devices (such as a Raspberry Pi). After working out how to get libtorch to build for aarch64, things are working great! However, I am having a little bit of difficulty getting quantized models to run. When I try to run a quantized torchscript module I get an error saying:
```
RuntimeError: Didn't find engine for operation quantized::conv2d_prepack NoQEngine
```
I believe the solution in python would be to run the following before loading the model:
```python
torch.backends.quantized.engine = 'qnnpack'
```
And I think the equivalent in C++ (according to [this](https://github.com/pytorch/pytorch/issues/28945#issuecomment-549399690) issue) is something like:
```cpp
auto qengines = at::globalContext().supportedQEngines();
  if (std::find(qengines.begin(), qengines.end(), at::QEngine::QNNPACK) != qengines.end()) {
    at::globalContext().setQEngine(at::QEngine::QNNPACK);
  }
``` 
Is there any sort of equivalent I can use in tch-rs? Sorry if its a silly question I'm very new to rust (and even newer to using C++ bindings in rust).
## Getting a quantized model (python)
```python
import torch


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.quant = torch.quantization.QuantStub()
        self.conv = torch.nn.Conv2d(3, 16, 3)
        self.relu = torch.nn.ReLU()
        self.dequant = torch.quantization.DeQuantStub()

    def forward(self, x):
        x = self.quant(x)
        x = self.conv(x)
        x = self.relu(x)
        x = self.dequant(x)
        return x

# Get fp32 model
model_fp32 = Model()
model_fp32.eval()

# Get int8 model
model_fp32.qconfig = torch.quantization.get_default_qconfig('qnnpack')
model_fp32_fused = torch.quantization.fuse_modules(model_fp32, [['conv', 'relu']])
model_fp32_prepared = torch.quantization.prepare(model_fp32_fused)
model_fp32_prepared(torch.randn(1, 3, 224, 224))
model_int8 = torch.quantization.convert(model_fp32_prepared)

# Get and save int8 torchscript model
model_int8_script = torch.jit.script(model_int8)
model_int8(torch.randn(1, 3, 224, 224))
torch.jit.save(model_int8_script, "model_int8.pth")
```
## Running inference (rust)
```rust
use std::time::{SystemTime};

extern crate tch;
use tch::CModule;
use tch::vision::{imagenet};


pub fn main() {
    let module = CModule::load("model_int8.pth").unwrap();
    let image = imagenet::load_image_and_resize224("cat.jpg").unwrap();
    let now = SystemTime::now();
    for _i in 1..10 {
        let _out = module.forward_ts(&[image.unsqueeze(0)]).unwrap();
    }
    println!("{}", now.elapsed().unwrap().as_millis() / 10);
}
```

**Comment by LaurentMazare** [comment]
Hello,
I just merged some code that should make it possible to select the quantization engine, e.g. by using the following:
```rust
tch::QEngine::QNNPACK.set()?;
```
It's very nice that you've been able to get all this to work on arm platforms, could be worth writing some documentation/blog post about it as it might be useful to others.

**Comment by calmdown13** [comment]
Wow amazing, thank you! Sure, once I've got things cleaned up a bit I'd be happy to write it up.

**Comment by calmdown13** [comment]
Raised a [small PR](https://github.com/LaurentMazare/tch-rs/pull/289) to add a quantized JIT model example.

**Comment by LaurentMazare** [comment]
Closing this now that the changes have been merged, feel free to re-open if needed.
