### ISSUE TITLE
How do i iterate over tensor without converting to vec

### ISSUE THREAD

**Issue by FilipAndersson245** [LaurentMazare/tch-rs#292]
How do I iterate over a vector without converting it to intermediate types? The current code I use spends a majority of its time converting the tensor to a vector to iterate over it, but we want to improve its speed.

**Comment by LaurentMazare** [comment]
As with the python version, the general advice is to avoid iterating over elements as much as possible and use "vectorized" operations instead - these are highly optimized, run on your GPU, etc. A very flexible operation is [Einstein summation](https://pytorch.org/docs/stable/generated/torch.einsum.html) ([rust doc](https://docs.rs/tch/0.3.0/tch/struct.Tensor.html#method.einsum)).
That said it's not always possible to avoid iterating over the tensor content, you can probably access elements by their index via [int_64_value](https://docs.rs/tch/0.3.0/tch/struct.Tensor.html#method.int64_value) or [double_value](https://docs.rs/tch/0.3.0/tch/struct.Tensor.html#method.double_value) but it's quite likely to be slower than converting to a vector.

**Comment by famattsson** [comment]
Thanks for the answer, what we are specifically trying to do is the non-max suppression step of YOLO, i.e. compare each element of a tensor to the confidence threshold. Could this be done in a faster manner than through conversion to a vector? (Btw, I am in the same team as the original poster)

**Comment by LaurentMazare** [comment]
Indeed non-max suppression is tricky to implement with vectorized operations. Collecting the bounding boxes above the threshold would be difficult so in the [yolo example](https://github.com/LaurentMazare/tch-rs/blob/7d84a5897373f67f9c8978623f6837e75fdf0851/examples/yolo/main.rs#L47-L96) we used the conversion to a vector.

Fwiw the [implementation from the torchvision package](https://github.com/pytorch/vision/blob/455cd57c9404429448280cd4a0d7f600a51afc54/torchvision/csrc/cpu/nms_cpu.cpp) is also using non-vectorized operations to iterate over bounding boxes.

**Comment by famattsson** [comment]
We managed to create a work-around by extracting the confidences using slicing and then using the max function to extract the instance with the best confidence and the index thereof. Thank you for your help!

**Comment by LaurentMazare** [comment]
Cool, closing this for now then! Feel free to re-open if needed.
(also if at some point you find some time to write some blog post/... on using rust for your computer vision model, that would certainly be of general interest to the community)
