### ISSUE TITLE
Tensor has too many methods

### ISSUE THREAD

**Issue by moshg** [LaurentMazare/tch-rs#295]
`tch::Tensor` has more methods than PyTorch's Tensor, e.g. `tch::Tensor::conv2d`. I think it would be better to have the functions that PyTorch's Tensor doesn't have in separate place.

**Comment by LaurentMazare** [comment]
These methods are automatically generated using some [compilation artefacts](https://github.com/LaurentMazare/tch-rs/blob/master/third_party/pytorch/Declarations-v1.7.0.yaml) from the pytorch C++ library and these artefacts don't include much classification information.
So the idea is to have every method provided on the Tensor class in this crate. It may be an interesting project to provide a more rust idiomatic crate built 'manually' on top of this one, and which could provide better scoping, proper handling of aliasing, adding the element kind to the tensor type, etc, but this has not happened yet.

**Comment by moshg** [comment]
Thank you for the fast response!
Do you meam you don't have plans to make idiomatic wrappers in this crate?

**Comment by LaurentMazare** [comment]
Indeed we don't have plans for doing so in this crate: this crate provides "low-level" bindings that are somewhat idiomatic, these bindings are easy enough to use for a bunch of use cases as per the provided examples or other crates such as [rust-bert](https://github.com/guillaume-be/rust-bert). There might be some space for one or many "high-level" apis, e.g. some equivalent to pytorch-lightning or keras, I'm not aware of any so far.

**Comment by LaurentMazare** [comment]
Closing this for now, as there is no plan no reduce the number of methods and they are all inferred from the C++ api.
Feel free to re-open if this ends up being an issue.
