### ISSUE TITLE
Varstore parameters names in RNN

### ISSUE THREAD

**Issue by lerouxrgd** [LaurentMazare/tch-rs#302]
Hello,

It looks like the names of GRU and LSTM varstore variables are not matching the ones from Pytorch as you can see [here](https://github.com/pytorch/pytorch/blob/815d38395a5081adef6ecec3372474f6f41b2a7c/torch/nn/modules/rnn.py#L106-L112).

Moreover, if there are multiple layers and/or bidirectional is true, as this is not reflected in the variable names like in Python, won't the varstore variables be overwritten continously in the loops ?

https://github.com/LaurentMazare/tch-rs/blob/ae79df5858535bc27eab38a09d3de4ee54d12dcf/src/nn/rnn.rs#L182-L196

**Comment by LaurentMazare** [comment]
Thanks for pointing this out (and for the link to PyTorch), we've just pushed some changes to use the same naming conventions as in the python version. Let us know if you run into any issues with this.

**Comment by lerouxrgd** [comment]
It looks good, thank you for the quick fix !

Besides, I noticed that in PyTorch bias is added only if true in the config (just a few lines above in the code I linked previously).
In `tch-rs` this in not checked in the config and always added.

**Comment by LaurentMazare** [comment]
Thanks for noticing this too, we just merged some changes that should avoid creating these unnecessary biases.

**Comment by lerouxrgd** [comment]
Thank you for your quick actions, everything looks good !
