### ISSUE TITLE
Error loading TorchScript JIT traced model

### ISSUE THREAD

**Issue by mdkozlowski** [LaurentMazare/tch-rs#304]
Good day,
I'm testing the loading of a JIT traced model from a Rust program to serve models in production, and get an error when I try to load the model.
Here is my Rust code:
```rust
use anyhow::{bail, ensure, Result};

pub fn main() -> anyhow::Result<()> {
    let model_path = "C:\\projects\\tchrs_test\\model.pt";
    let model = tch::CModule::load(model_path)?;
    Ok(())
}
```
I get a 'Access violation reading location'. I don't have much experience with C++ but it feels like a null pointer in atm_load on [this line](https://github.com/LaurentMazare/tch-rs/blob/e9168da9ba6865f0c62a07cefebdb364372bb554/src/wrappers/jit.rs#L274)
tch-rs seems to work fine on my system by itself, I can run the `basics` example fine. I'm on a Windows system

Here is my python script to create and save the model (it definitely exists at the location I'm trying to load):
```python

import torch
import torch.nn as nn

class CustomModule(nn.Module):
	def __init__(self):
		super().__init__()
		self.fc1a = nn.Linear(5, 10)
		self.fc1b = nn.Linear(5, 10)

		self.fc2 = nn.Linear(20, 1)
		self.relu = nn.ReLU()

	def forward(self, input_a):
		xa = self.fc1a(input_a)
		xb = self.fc1b(input_a)

		x = torch.cat([xa, xb], dim=0)
		x = self.relu(x)
		return self.fc2(x)

def main():
	mod = CustomModule()
	mod.eval()

	inp_a = torch.arange(0, 5, dtype=torch.float)
	output = mod(inp_a)
	print(output)
	traced_script_module = torch.jit.trace(mod.forward, inp_a)
	traced_script_module.save('model.pt')

if __name__ == '__main__':
	main()

```

**Comment by LaurentMazare** [comment]
Thanks for reporting the issue. I wasn't able to reproduce the problem on my platform (pytorch 1.7.0+cpu, ubuntu 2020.04) and loading the model saved by your python script worked fine. Loading a file which doesn't exist panics with the expected error message too [1] so it's a bit unclear what is going on here.

Could you double check the version of the torch python package that you're using? (though the format should not change between version)
It might also be worth running the crate tests as they load a bunch of JIT modules so it would be interesting to see if these fail too.

[1]
```bash
Error: Internal torch error: open file failed, file path: /tmp/model.pt
```

**Comment by mdkozlowski** [comment]
Hi,
I'm running pytorch 1.7.0 with libtorch 1.7.0
All the tests pass correctly, including `jit_tests`
When I try to open a file that doesn't exist I get the same error (`Exception: Exception 0xc0000005 encountered at address 0x7fff2271a99b: Access violation reading location 0x00000027`). I'm not sure what kind of stack trace I could send you besides a screenshot of the CLion debugger frames:
![image](https://user-images.githubusercontent.com/1402787/103138530-3a4ff480-46dc-11eb-9d16-e55d82cc7cae.png)

I'm sure this is something very obvious that I'm missing but I don't have any experience with C++  or debugging something like this

**Comment by mdkozlowski** [comment]
Hi, I resolved this issue by using libtorch release builds rather than debug. I didn't realise this could be an issue for FFI until I read this in the [Torch docs](https://pytorch.org/cppdocs/installing.html):
`On Windows, debug and release builds are not ABI-compatible. If you plan to build your project in debug mode, please try the debug version of LibTorch. Also, make sure you specify the correct configuration in the cmake --build . line above.`
Thanks for your prompt response

**Comment by LaurentMazare** [comment]
Glad that it's now working, I've added a small note to the main readme in case anyone runs into similar issues.
