### ISSUE TITLE
Would it be possible to release latest changes as version 0.3.1 ?

### ISSUE THREAD

**Issue by lerouxrgd** [LaurentMazare/tch-rs#305]
Hello,

In order to use `tch-rs` additions since 0.3.0 through other crates (I am thinking of `rust-bert`), I think it would be simpler to have a new release.

Does it sound good to you, or do you have a specific release planning ?

**Comment by LaurentMazare** [comment]
Hello,
I just published version 0.3.1 (from the current github tip). Let us know if you see any issue with this.

**Comment by lerouxrgd** [comment]
Everything is good, thank you !
