### ISSUE TITLE
[Feature Request] Clip grad norm

### ISSUE THREAD

**Issue by araffin** [LaurentMazare/tch-rs#306]
Hello,

First of all, thanks a lot for this repo =).

I'm currently experimenting with RL (re-implementing gym and RL algorithms in rust) and I noticed that [clip grad norm](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html) was not available yet.
I know that clip grad value is implemented here:
https://github.com/LaurentMazare/tch-rs/blob/db9fb60f158f9b7a9765ce00fec6d9d5c7b0c007/src/nn/optimizer.rs#L197

but this is not what is normally used in RL...
See [Stable-Baselines3 A2C](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/a2c/a2c.py#L163) implementation for instance.

vs 
https://github.com/LaurentMazare/tch-rs/blob/db9fb60f158f9b7a9765ce00fec6d9d5c7b0c007/examples/reinforcement-learning/a2c.rs#L142

Would it be possible to implement such feature?
(I'm still pretty new to Rust and tch-rs so I cannot unfortunately offer a PR yet...)

**Comment by LaurentMazare** [comment]
Thanks for the suggestion, I just pushed some changes adding a `backward_step_clip_norm` variant which implementation should be similar to the pytorch one (except that it only handles L2). Let us know if you run into any issue using this.

**Comment by araffin** [comment]
Merci pour la réactivité =)
Works like a charm.

I'll probably do a PR at some point to improve A2C/PPO implementations ;)

**Comment by LaurentMazare** [comment]
> Merci pour la réactivité =)
> Works like a charm.
> 
> I'll probably do a PR at some point to improve A2C/PPO implementations ;)

Sure, quite curious to see if the clipping change has some actual impact on model training.
