### ISSUE TITLE
Destructure IValues idiomatically

### ISSUE THREAD

**Issue by ahirner** [LaurentMazare/tch-rs#307]
Hi!

I need to destructure particular tuples from scripted model outputs. The easiest case of 3 `Tensor` became unwieldy to me (as rust novice).
```rust
fn unwrap_m0_is<'a>(
    v: &'a IValue,
) -> Result<(&'a Tensor, &'a Tensor, &'a Tensor), TchError> {
    if let IValue::Tuple(v) = v {
        let (t0, t1, t2) = (&v[0], &v[1], &v[2]);
        if let (IValue::Tensor(t0), IValue::Tensor(t1), IValue::Tensor(t2)) = (t0, t1, t2) {
            Ok((&t0, &t1, &t2))
        } else {
            Err(TchError::Convert(format!("{:?} unexpected IValue", v)))
        }
    } else {
        Err(TchError::Convert(format!("{:?} unexpected IValue", v)))
    }
```
Is there a more idiomatic way that comes to mind? Also when dealing with more complicated structures, say the fourth position is an `Option`.
Thanks for this fantastic piece of work.

**Comment by LaurentMazare** [comment]
I've pushed some changes that should make destructuring of ivalues a bit simpler, however compared to your example they consume the values rather than operating on references, we could probably add a variant to work on references if that's helpful.
As to how you use it, your example would become something like:
```rust
let (v1, v2, v3) = <(Tensor, Tensor, Tensor)>::try_from(myivalue)?;
```
The `Option` type should be supported though not perfectly, e.g. an option on a tensor would work but not an option on a tuple - this is a bit due to some conflict with the `try_from` trait and hopefully can be improved in the future.

**Comment by ahirner** [comment]
Thank you, I'm delighted that `try_from` already works for basic and common `Option` cases.

Exploring your related question: what would be the savings of `&` for such destructuring? AFAIU, moving is the idiomatic way to work with `tch-rs` structs. Hence, you shall use `.shallow_copy` if needed. Refcounts are mandated by ATen regardless. Hence, we could at most safe an atomic inc and little to no memory (some layout info maybe?). Also, copy elision might come in (?). I might be utterly wrong with all this though.

**Comment by ahirner** [comment]
Hmm, I just understood I cannot `.shallow_copy` my way out before `try_from` on an `IValue`, only with `Tensor`. Is there an alternate way to use  `IValue` again except the aforementioned `&` option?

**Comment by LaurentMazare** [comment]
I agree that consuming the value is probably the appropriate thing for most use cases.
Why do you need to copy the value beforehand? Is it that you have to try different types for the destructuring?

**Comment by ahirner** [comment]
Right now, very mundane: debug prints after a bunch of operations (which I was able to reorder).
I don't see any real production case where `try_from` owned isn't applicable for the desired ergonomic wins!

**Comment by LaurentMazare** [comment]
Perfect thanks, let us know if you encounter some use cases where this would be useful.
