### ISSUE TITLE
Exposing low level APIs to write bindings of third-patry libraries 

### ISSUE THREAD

**Issue by Hakuyume** [LaurentMazare/tch-rs#309]
Is it possible to expose an API that converts `*mut torch_sys::C_tensor` <-> `tch::Tensor`?

I'm writing a Rust binding of an existing C++ library. The C++ library depends on libtorch and takes/returns `at::Tensor`(s). in its APIs. I'd like to wrap them by `tch::Tensor`.

The C++ library
```c++
  at::Tensor some_cpp_func(at::Tensor &v);
```

My glue code
```c++
extern "C" at::Tensor *some_func(at::Tensor const *v) {
  return new at::Tensor(some_cpp_func(*v));
}
```

My Rust binding
```rust
fn some_func(v: &tch::Tensor) -> tch::Tensor {
    unsafe { tch::Tensor::from_raw(some_func(v.to_raw_ptr())) } # <- convert raw pointer <-> tch::Tensor
}
```

**Comment by LaurentMazare** [comment]
That sounds indeed useful, I've added a bunch of functions for the conversion in this [commit](https://github.com/LaurentMazare/tch-rs/commit/1261a5e43bfbb098397b50deaafc84805e210e5b).
Note that converting from a pointer is marked as unsafe, getting the pointer is not (but obviously using the pointer will be).
Let me know if you run into any issues using this.

**Comment by Hakuyume** [comment]
Thank you for the quick update.
I've tried the commit and it worked well for me.
