### ISSUE TITLE
Support Exporting to TorchScript

### ISSUE THREAD

**Issue by tiberiusferreira** [LaurentMazare/tch-rs#311]
Hello, thanks for all the time and effort put in this project.

I thought that exporting TorchScript from C++ (and by extension, Rust) was not possible due to https://discuss.pytorch.org/t/how-to-save-torchscript-model-using-cpp/59743.

However, the Haskell binding appear to support it: https://github.com/hasktorch/hasktorch/issues/302

Exporting to TorchScript is important to be able to emit ONNX ([which can be generated from TorchScript](https://pytorch.org/docs/stable/onnx.html)) models which then can be optimized and run in another runtime, such as [TensorRT](https://developer.nvidia.com/Tensorrt), [ONNX Runtime](https://github.com/microsoft/onnxruntime/tree/master/orttraining/orttraining) or used in iOS/Android or any other environment without shipping the entire PyTorch runtime.

Is it something this project would like to support?

**Comment by LaurentMazare** [comment]
Hello,
Thanks for pointing this out, I didn't know that this existed on the C++ side, this seems pretty neat. I'll have a look at whether this is easy to wrap in this crate.

**Comment by LaurentMazare** [comment]
Closing this now that `tch::CModule::create_by_tracing` is available, feel free to re-open if you encounter any issue/missing bits.

**Comment by JinXiaozhao** [comment]
@LaurentMazare, I have no idea when create_by_tracing  should be used. Could you give an example?

**Comment by LaurentMazare** [comment]
There is an example using this in the [jit tests](https://github.com/LaurentMazare/tch-rs/blob/45a0ac884e61d7305e4c6e2fae9497504000fe31/tests/jit_tests.rs#L131).
