### ISSUE TITLE
`Tensor::fft` was deprecated, and tch::fft::fft dose not exists.

### ISSUE THREAD

**Issue by songww** [LaurentMazare/tch-rs#313]

**Comment by LaurentMazare** [comment]
Could you give a bit more details about what the actual error is / what you're trying to do?
Fwiw the `fft` method is deprecated in the C++ api (which this crate is a thin wrapper around), however there is a `fft_fft` method, e.g.:
```rust
let tensor = tensor.fft_fft(1, 1, "ortho");
```

**Comment by songww** [comment]
Thanks.
