### ISSUE TITLE
create tensor from array (Tensor::of_blob)

### ISSUE THREAD

**Issue by doofin** [LaurentMazare/tch-rs#324]
```rust
        let dat = [[1, 2, 3], [1, 2, 3]];
        let pt = &dat as *const _ as *const u8;
        let us = unsafe {
            Tensor::of_blob(
                pt,
                &[2, 3],
                &[1, 1],
                Kind::Int,
                tch::Device::cuda_if_available(),
            )
        };
```
this prints `" 1  2  3\n 2  3  1\n[ CPUIntType{2,3} ]"` and looks not quite right.
BTw,is this the only method to create tensors of any shape by `of_blob`?

**Comment by LaurentMazare** [comment]
`of_blob` is unsafe and should be avoided as much as possible (its main use case is when running code as a Python extension and exchanging tensors between the Python and the Rust side).
Using `of_slice` followed by a reshape is likely to be closer to what you want here. Overall I would suggest having a look at the [tensor tests](https://github.com/LaurentMazare/tch-rs/blob/master/tests/tensor_tests.rs) as well as the `examples/` directory to find about this kind of thing.

**Comment by doofin** [comment]
Thanks!
