### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by cymqqqq** [LaurentMazare/tch-rs#333]
error[E0463]: can't find crate for `tch`
 --> src/main.rs:3:1
  |
3 | extern crate tch;
  | ^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `tch`
 --> src/main.rs:3:1
  |
3 | extern crate tch;
  | ^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
For more information about this error, try `rustc --explain E0463`.
error: could not compile `yolo`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by LaurentMazare** [comment]
Closing this as it lacks any details on how to reproduce the error and running the example seems to work fine.
