### ISSUE TITLE
Make COptimizer publicly accessible

### ISSUE THREAD

**Issue by edlanglois** [LaurentMazare/tch-rs#336]
`nn::OptimizerConfig::build_copt` is a public method that creates a `COptimizer` but since `COptimizer` is ~private~ public but can't be named, the result can't really be used.

I am interested in having access to COptimizer because I prefer its API compared to Optimizer (see #335, also if I know the variables will not change I would rather avoid the overhead of calling `add_missing_variables` on every step).

**Comment by LaurentMazare** [comment]
Just pushed some changes that should expose `COptimizer` so that it's easier to use it. If this still doesn't work for you, could you please provide an example that doesn't compile?

**Comment by edlanglois** [comment]
Thanks for the rapid response and fix!
