### ISSUE TITLE
cargo run yolo error

### ISSUE THREAD

**Issue by cymqqqq** [LaurentMazare/tch-rs#337]
Error: Internal torch error: open file failed, file path: yolo-v3.ot
Exception raised from FileAdapter at ../caffe2/serialize/file_adapter.cc:11 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7faf1dbfdb29 in /home/azureuser/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd2 (0x7faf1dbfaab2 in /home/azureuser/libtorch/lib/libc10.so)
frame #2: caffe2::serialize::FileAdapter::FileAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x25f (0x7faf1ff0faff in /home/azureuser/libtorch/lib/libtorch_cpu.so)
frame #3: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x40 (0x7faf21503a00 in /home/azureuser/libtorch/lib/libtorch_cpu.so)
frame #4: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>) + 0x6f (0x7faf21503b8f in /home/azureuser/libtorch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0xc6193 (0x55d3991a4193 in target/debug/yolo)
frame #6: <unknown function> + 0x4d1e9 (0x55d39912b1e9 in target/debug/yolo)
frame #7: <unknown function> + 0x243e3 (0x55d3991023e3 in target/debug/yolo)
frame #8: <unknown function> + 0x382c6 (0x55d3991162c6 in target/debug/yolo)
frame #9: <unknown function> + 0x399cb (0x55d3991179cb in target/debug/yolo)
frame #10: <unknown function> + 0x5524e (0x55d39913324e in target/debug/yolo)
frame #11: <unknown function> + 0x2e301 (0x55d39910c301 in target/debug/yolo)
frame #12: <unknown function> + 0x105cc7 (0x55d3991e3cc7 in target/debug/yolo)
frame #13: <unknown function> + 0x2e2d7 (0x55d39910c2d7 in target/debug/yolo)
frame #14: <unknown function> + 0x393da (0x55d3991173da in target/debug/yolo)
frame #15: __libc_start_main + 0xf3 (0x7faf1d80a0b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #16: <unknown function> + 0x1b8ee (0x55d3990f98ee in target/debug/yolo)

**Comment by LaurentMazare** [comment]
The example code has some details about the weights to be downloaded for this example to work, see [yolo/main.rs](https://github.com/LaurentMazare/tch-rs/blob/master/examples/yolo/main.rs).
