### ISSUE TITLE
How can we manipulate a tensor's gradient?

### ISSUE THREAD

**Issue by Liby99** [LaurentMazare/tch-rs#352]
Hi, I'm recently working on a project where I need to inject gradients computed by myself. In python I can do something like

``` python
for p in model.parameters():
    p.grad *= C
```

I wonder how we can do this with `tch-rs`? Thanks in advance.

**Comment by LaurentMazare** [comment]
Hi, have you tried something like the following?
```rust
let mut g = param.grad();
g *= C;
```
And to get the parameters from a model, using `trainable_variables` or `variables` on a `VarStore`.

**Comment by Liby99** [comment]
Thx
