### ISSUE TITLE
whats the difference between the ot files and the pth files

### ISSUE THREAD

**Issue by infinite-Joy** [LaurentMazare/tch-rs#36]
in [this example for loading pretrained files](https://github.com/LaurentMazare/tch-rs/blob/master/examples/pretrained-models/main.rs), .ot files are used while the general pytorch convention is to save in .pth files. Whats the difference between the two?

**Comment by LaurentMazare** [comment]
The general pytorch convention is indeed to use `.pt` or `.pth` when [saving models](https://pytorch.org/tutorials/beginner/saving_loading_models.html). These files are usually in pickle format which is very tied to python and not supported by the C++ api or by `tch-rs`.
I used `.ot` for the torch C++ module format (see the serialization functions in [module.h](https://github.com/pytorch/pytorch/blob/master/torch/csrc/api/include/torch/nn/module.h)), I don't know if there is already a convention for this file format. You can find a bunch of weight files in this format for vision models at the top of the script that you referred to. The [tensor-tools](https://github.com/LaurentMazare/tch-rs/blob/master/examples/tensor-tools.rs) example is useful to convert python generated files (using numpy npz) to/from this format.

**Comment by LaurentMazare** [comment]
Is there anything more that you think should be done here ? Otherwise I'll close the issue.

**Comment by infinite-Joy** [comment]
Thanks for replying on this

**Comment by jackpeters667** [comment]
@LaurentMazare  sorry for bringing this up again But I have a `pth` file that I just trained. Am I able to use it in Rust via TorchScript? If so, may you please guide me on how I can go about it or anything I can do to go from `pth` to `ot`
