### ISSUE TITLE
how to translate  t = t[t>0]

### ISSUE THREAD

**Issue by linshuxi** [LaurentMazare/tch-rs#362]
hello,guys
i have a tensor t, and i would like to get the result of the expression: t = t[t > 0]. However, i cannot find a method to do it, any idea is appreciated. :)

**Comment by LaurentMazare** [comment]
Have you tried using [masked_select](https://docs.rs/tch/0.4.1/tch/struct.Tensor.html#method.masked_select)? This should filter the elements of the tensor keeping only the values where it is true. Note that it results in a single dimension tensor even if your original tensor was multi-dimensional.
```rust
let t = t.masked_select(&t.gt(0));
```

**Comment by linshuxi** [comment]
> Have you tried using [masked_select](https://docs.rs/tch/0.4.1/tch/struct.Tensor.html#method.masked_select)? This should filter the elements of the tensor keeping only the values where it is true. Note that it results in a single dimension tensor even if your original tensor was multi-dimensional.
> 
> ```rust
> let t = t.masked_select(&t.gt(0));
> ```

Great, thanks a lot!
