### ISSUE TITLE
function try_from is not working

### ISSUE THREAD

**Issue by linshuxi** [LaurentMazare/tch-rs#363]
Hello, i try to test the try_from funciton, and the code is:
`let nd = ndarray::arr2(&[[1f64, 2.], [3., 4.]]);
 let tensor = Tensor::try_from(nd.clone()).unwrap();`
however, there is an error information:

> let tensor = Tensor::try_from(nd.clone()).unwrap();
    |                              ^^^^^^^^ function or associated item not found in `tch::Tensor`

i am running the tch="0.4.1".
can anyone give me some suggestions on how to solve the problem?

Best

**Comment by LaurentMazare** [comment]
You can find lots of examples of uses of `try_from` in the [tensor tests](https://github.com/LaurentMazare/tch-rs/blob/master/tests/tensor_tests.rs), maybe one of them will match what you're trying to do.

**Comment by LaurentMazare** [comment]
Closing as no update in the last couple months.
