### ISSUE TITLE
Tensor from multi dimensional array

### ISSUE THREAD

**Issue by coreylowman** [LaurentMazare/tch-rs#365]
Hello,

I wrote the following function for creating a tensor from any slice type, do you think it would be good to include?

note I had to copy and paste the internals of kind.c_int() because for some reason it says its private.

```
pub fn tensor<T>(data: &[T], dims: &[i64], kind: tch::Kind) -> Tensor {
    let t = unsafe {
        Tensor::from_ptr(at_tensor_of_data(
            data.as_ptr() as *const c_void,
            dims.as_ptr(),
            dims.len(),
            kind.elt_size_in_bytes(),
            match kind {
                Kind::Uint8 => 0,
                Kind::Int8 => 1,
                Kind::Int16 => 2,
                Kind::Int => 3,
                Kind::Int64 => 4,
                Kind::Half => 5,
                Kind::Float => 6,
                Kind::Double => 7,
                Kind::ComplexHalf => 8,
                Kind::ComplexFloat => 9,
                Kind::ComplexDouble => 10,
                Kind::Bool => 11,
                Kind::QInt8 => 12,
                Kind::QUInt8 => 13,
                Kind::QInt32 => 14,
                Kind::BFloat16 => 15,
            },
        ))
    };
    t
}
```

example:

```
    let q = [[0.0, 1.0, 2.0], [3.0, 4.0, 5.0]];
    let t = tensor(&q, &[2, 3], Kind::Double);
    t.print();
```

**Comment by LaurentMazare** [comment]
Hello,
I think that `Tensor::from_ptr` just uses the pointer that you pass it without copying the data so it's likely for this kind of function to be unsafe as you have to guarantee that `data` lives for at least as long as the returned tensor and this is not captured by any lifetime. But maybe I'm missing something here?

**Comment by coreylowman** [comment]
Ah I see. Does the call to `at_tensor_of_data` not copy data either?

**Comment by LaurentMazare** [comment]
Ah that's right, `at_tensor_of_data` will copy the data around. That said I think it's still unsafe as the length of `data` is never checked. Couldn't this whole thing be achieved in a safe way by combining `Tensor::of_slice` with `.view`?

**Comment by coreylowman** [comment]
Yeah you're right - I was finding that for some reason doing `Tensor::of_slice` and `.view` was much slower than just one call to the above, and was looking to maximize performance. Probably should stick with `view`.

**Comment by LaurentMazare** [comment]
Closing this for now, feel free to re-open if further issues.
