### ISSUE TITLE
Provide a `clone_to_device` method for `Module`

### ISSUE THREAD

**Issue by edlanglois** [LaurentMazare/tch-rs#369]
I'd like to copy a module to another device. In C++ this is the [clone](https://pytorch.org/cppdocs/api/classtorch_1_1nn_1_1_module.html#_CPPv4NK5torch2nn6Module5cloneERK8optionalI6DeviceE) method with an optional device.

While not something I currently need, I think it would also make sense to implement `Clone` for `Module` where it does a deep copy to the same device (and the same for implementing `Clone` for `Tensor`, but maybe that's a separate discussion).

Anyways, for C++ it looks like they have a separate [`Cloneable`](https://pytorch.org/cppdocs/api/classtorch_1_1nn_1_1_cloneable.html?highlight=cloneable) template class so a separate trait for `clone_to_device` would be an option rather than implementing directly on `Module`.

I'd be happy to try making a PR for this.

**Comment by edlanglois** [comment]
I've discovered the strategy you use in the [DDPG example](https://github.com/LaurentMazare/tch-rs/blob/master/examples/reinforcement-learning/ddpg.rs#L130) of constructing a new module instance then using the var store to copy the variables. That should work for me.

Having looked at the [C++ implementation](https://github.com/pytorch/pytorch/blob/09a8f22bf917727bc9179443185fdda875e04147/torch/csrc/api/include/torch/nn/cloneable.h) of Cloneable, doing something analogous would require expanding the `Module` trait to include `parameters`, `buffers`, and `children`. Alternatively it could be something implemented on a per-Module basis using `Tensor::to` / hypothetical `Tensor::clone`.

Those are bigger changes than I'd want to make given the existence of the VarStore approach so I'm no longer planning on making a PR for this at the moment.

**Comment by jerry73204** [comment]
You can see my [tch-tensor-like](https://github.com/jerry73204/tch-tensor-like) macro that derives `.shallow_clone()` on compound tensor structs.

**Comment by LaurentMazare** [comment]
Closing this for now as it has been a while and it feels like support this via some external crate such as tch-tensor-like is probably the best.
