### ISSUE TITLE
Basic examples fail to run OSX: Library not loaded libmklml.dylib

### ISSUE THREAD

**Issue by vegapit** [LaurentMazare/tch-rs#37]
Hi,

I have tried running the basic examples with: `cargo run --example basics` on MacOSX and here is the error message that I am getting:

dyld: Library not loaded: @rpath/libmklml.dylib
  Referenced from: /Users/vegapit/dev/libtorch/lib/libcaffe2.dylib
  Reason: image not found
Abort trap: 6

It seems to be looking for a library that is not available. I downloaded the libtorch 1.1.0 zip file at the following link:

[libtorch 1.1.0 for MacOSX](https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.1.0.zip)

Have I misunderstood the installation process?

**Comment by LaurentMazare** [comment]
Hi,
This seems to be a libtorch issue on macos x, e.g. https://github.com/pytorch/pytorch/issues/14165
Not sure what the proper way to fix it is (as I don't have access to a mac), but you may want to download and install mkl, e.g. https://github.com/intel/mkl-dnn/releases and copy  libiomp5.dylib and libmklml.dylib to .../libtorch/lib/.
If that works for you, we can add a small section at the bottom of the readme for people running into this issue.

**Comment by vegapit** [comment]
> Hi,
> This seems to be a libtorch issue on macos x, e.g. [pytorch/pytorch#14165](https://github.com/pytorch/pytorch/issues/14165)
> Not sure what the proper way to fix it is (as I don't have access to a mac), but you may want to download and install mkl, e.g. https://github.com/intel/mkl-dnn/releases and copy libiomp5.dylib and libmklml.dylib to .../libtorch/lib/.
> If that works for you, we can add a small section at the bottom of the readme for people running into this issue.

It sounds good to me. I will have a go at installing the "mkl-dnn" lib separately and copy the dylib over. I will keep you updated about the results if it helps.

**Comment by quanlou** [comment]
> ... download and install mkl by https://github.com/intel/mkl-dnn/releases and copy libiomp5.dylib and libmklml.dylib to .../libtorch/lib/.
this worked for me on osx, we also need to install the libomp by this `brew install libomp`

**Comment by vegapit** [comment]
Yep, it worked for me too. Easy fix after all.
