### ISSUE TITLE
upsample_bilinear2d requires output_size even if scales are provided

### ISSUE THREAD

**Issue by fuine** [LaurentMazare/tch-rs#377]
If I understand it correctly, the `upsample_bilinear2d` method should either take scale or output size as arguments - see docs for upsample in python: https://pytorch.org/docs/stable/nn.functional.html?highlight=upsample#torch.nn.functional.upsample or this message in the `compute_output_size`: https://github.com/pytorch/pytorch/blob/v1.8.1/aten/src/ATen/native/UpSample.cpp#L15 or this implementation of `upsample_bilinear2d` for cpu: https://github.com/pytorch/pytorch/blob/v1.8.1/aten/src/ATen/native/UpSampleBilinear2d.cpp#L149 I'm not sure why in `tch-rs` the signature looks like this:

```rust
pub fn upsample_bilinear2d(
    &self,
    output_size: &[i64],
    align_corners: bool,
    scales_h: impl Into<Option<f64>>,
    scales_w: impl Into<Option<f64>>
) -> Tensor
```
I could reimplement `compute_output_size` by hand, but I was wondering whether or not `torch` should do that for me. I'm trying to port the following line from `pytorch`: `upsample = nn.Upsample(scale_factor=2, mode="bilinear", align_corners=True)`. I think that #217 is somewhat related, because the `functional.upsample` method calls `interpolate`, which in turn calls `torch._C._nn.upsample_bilinear2d`, but the `output_size` argument there is `None`, as  set in code here: https://github.com/pytorch/pytorch/blob/v1.8.1/torch/nn/functional.py#L3483

**Comment by LaurentMazare** [comment]
The api is automatically generated from the [Declarations yaml file](https://github.com/LaurentMazare/tch-rs/blob/master/third_party/pytorch/Declarations-v1.8.0.yaml). The definition for `upsample_bilinear2d` is given below, I think that the culprit here is that nullable IntArrayRef are not supported in the code generation so we convert this to a mandatory parameter. I'll have a look at tweaking the code generation to support this, this shouldn't be too hard.

```json
- name: upsample_bilinear2d
  operator_name: upsample_bilinear2d
  overload_name: vec
  manual_kernel_registration: false
  category_override: ''
  matches_jit_signature: true
  schema_string: aten::upsample_bilinear2d.vec(Tensor input, int[]? output_size, bool align_corners, float[]? scale_factors) -> Tensor
  arguments:
  - annotation: null
    dynamic_type: Tensor
    is_nullable: false
    name: input
    type: const Tensor &
  - annotation: null
    dynamic_type: IntArrayRef
    is_nullable: true
    name: output_size
    type: c10::optional<IntArrayRef>
  - annotation: null
    dynamic_type: bool
    is_nullable: false
    name: align_corners
    type: bool
  - annotation: null
    dynamic_type: ArrayRef<double>
    is_nullable: true
    name: scale_factors
    type: c10::optional<ArrayRef<double>>
  schema_order_cpp_signature: Tensor (const Tensor &, c10::optional<IntArrayRef>, bool, c10::optional<ArrayRef<double>>)
  schema_order_arguments:
  - annotation: null
    dynamic_type: Tensor
    is_nullable: false
    name: input
    type: const Tensor &
  - annotation: null
    dynamic_type: IntArrayRef
    is_nullable: true
    name: output_size
    type: c10::optional<IntArrayRef>
  - annotation: null
    dynamic_type: bool
    is_nullable: false
    name: align_corners
    type: bool
  - annotation: null
    dynamic_type: ArrayRef<double>
    is_nullable: true
    name: scale_factors
    type: c10::optional<ArrayRef<double>>
  method_of:
  - Type
  - namespace
  mode: native
  python_module: nn
  returns:
  - dynamic_type: Tensor
    name: result
    type: Tensor
  inplace: false
  is_factory_method: false
  abstract: true
  device_guard: true
  with_gil: false
  deprecated: false
  has_math_kernel: false
```

**Comment by fuine** [comment]
Great, I'm willing to help, although my knowledge regarding binding generation is pretty much non-existant :slightly_smiling_face:

**Comment by LaurentMazare** [comment]
I've just merged some changes that expose the `upsample_bilinear2d` variant that has optional `output_size`, you can see it [here](https://github.com/LaurentMazare/tch-rs/blob/0b45aad4e285724d0a29c75b17a79fb9c7ba558d/src/wrappers/tensor_generated.rs#L11198-L11203). Feel free to give it a spin and let us know how it gets (I haven't tried it).

**Comment by LaurentMazare** [comment]
Closing this now as this should be fixed, feel free to re-open if you run into any issue using the new functions.

**Comment by fuine** [comment]
Sorry for the late reply. Works like a charm, thank you!
