### ISSUE TITLE
convert CModule into Module

### ISSUE THREAD

**Issue by infinite-Joy** [LaurentMazare/tch-rs#38]
I have loaded a python saved model using the code

```
let model = tch::CModule::load(model_file)?;
```

how can i convert this to a model so that i can run the below code.

```
let train_images = tch::no_grad(|| image_dataset.train_images.apply_t(&model, false));
```

Currently the error is this

```
error[E0277]: the trait bound `tch::CModule: tch::nn::Module` is not satisfied
  --> src/main.rs:38:65
   |
38 |     let test_images = tch::no_grad(|| image_dataset.test_images.apply_t(&model, false));
   |                                                                 ^^^^^^^ the trait `tch::nn::Module` is not implemented for `tch::CModule`
   |
   = note: required because of the requirements on the impl of `tch::nn::ModuleT` for `tch::CModule`

```

**Comment by LaurentMazare** [comment]
You should be able to call `model.forward` as per the [jit example](https://github.com/LaurentMazare/tch-rs/blob/master/examples/jit/main.rs).
If for some reason you really want to use `apply_t`, you could probably go with something like:

```rust
let m = nn::func(move |xs| { model.forward(xs) });
xs.apply(&model)
```
(I don't have access to a rust compiler right now so there may be some type errors)

**Comment by LaurentMazare** [comment]
I just pushed some changes so that JIT modules now implement the `nn::Module` trait so using `apply` should work out of the box. I also tweaked the [jit example](https://github.com/LaurentMazare/tch-rs/blob/master/examples/jit/main.rs) to reflect this.
Feel free to re-open the issue if you still have problems with this.
