### ISSUE TITLE
Does not compile as dependency when "--target=x86_64-pc-windows-gnu" is specified

### ISSUE THREAD

**Issue by Tiberius202** [LaurentMazare/tch-rs#380]
I'm trying to compile a staticlib with the cargo build argument x86_64-pc-windows-gnu and I get a wall of errors. I need a staticib because I am trying to compile the rust code into a c library, so I can call the functions from c code.

[Errors.txt](https://github.com/LaurentMazare/tch-rs/files/6750235/Errors.txt)

I have tried a couple things to get around this. The main one that worked was removing the "--target=x86_64-pc-windows-gnu", but doing so ruined the c library I want (I think it mangled the names) on both my project and a similiar one. However, removing the target made the project build.

I don't believe this is a problem with rust-bert or my code but caused by libtorch / torch-sys. The build error happens while compiling torch-sys and most of the errors say something about libtorch. I have seen similar errors online when incompatible versions of libtorch and tch are used but I have downloaded libtorch CPU 1.8.1 and am using tch 0.4.1.

Here is a copy of the relevant parts of my cargo.toml.

[lib]
crate-type = ["staticlib"]

[dependencies]
rust-bert = "0.15.1"
anyhow = "1.0.40"
tch = "0.4.1"
libc = "*"

If you need anymore information or have any suggestions, let me know.

Thank You!

**Comment by LaurentMazare** [comment]
This might be caused by `x86_64-pc-windows-gnu` using mingw for which pytorch has no support (and no plan to support). The `__assert_fail` error looks very reminiscent of https://github.com/pytorch/pytorch/issues/42589

**Comment by Tiberius202** [comment]
Yeah, the compiler I am trying to use the rust static library with is mingw. Unfortunately, I have been having trouble getting other compilers besides mingw to work with RTools.

Do you know which compilers the tch / pytorch library supports? Perhaps there is a way to convert the static library into a mingw one?

Thank you for the help so far.

**Comment by LaurentMazare** [comment]
I wouldn't really know as I don't have any windows box, I think msvc might be the default tool chain for lots of things but pretty unclear. I would recommend asking on the pytorch github or discourse as it seems mostly pytorch related.

**Comment by Tiberius202** [comment]
Alright, I'll ask on the pytorch github and see if I can get any help there. If I find a workaround, I'll post about it here.
Thank you
