### ISSUE TITLE
It would be better to get tensor value when debugging

### ISSUE THREAD

**Issue by dbsxdbsx** [LaurentMazare/tch-rs#383]
I am using vscode + rust analyzer in win10x64.  Tch-rs is really convenient ,except that I canot get tensor value when debugging(I tried both debug and release version of pytorch v1.9)---unless I print it like `tensor.print()`.

I am not sure whether this is a problem with tch-rs or an issue with debugger.

**Comment by jerry73204** [comment]
You can call `tensor.i()` to access elements at specified index and perform slicing.

```rust
use tch::IndexOp;

let xs = Tensor::randn(&[8, 3, 16, 16], FLOAT_CPU);
let value = xs.i((4, 0, 2, 3));  // single value
let slice = xs.i((0..4, .., .., ..));  // slicing

dbg!(value);  // print value
let value = f64::from(value);  // convert to f64
```

**Comment by dbsxdbsx** [comment]
I am go on close this issue , as this seems unsolvable at present.
