### ISSUE TITLE
Typo in examples/transfer-learning/readme.md

### ISSUE THREAD

**Issue by km19809** [LaurentMazare/tch-rs#384]
In [examples/transfer-learning/readme.md](https://github.com/LaurentMazare/tch-rs/tree/master/examples/transfer-learning)
` For training, the tensor has shape 211x3x224x224, this corresponds to 211 images of height and width both 211 with 3 channels (PyTorch uses the NCHW ordering for image data). The testing image tensor has dimensions 127 so there are 127 images with the same size as used in training.`
But height and width are both 224.

**Comment by LaurentMazare** [comment]
Right, just pushed a fix to correct this, thanks for reporting it!
