### ISSUE TITLE
Rename `{gru,lstm,rnn_tanh}_data` => `{gru,...}_packed`

### ISSUE THREAD

**Issue by edlanglois** [LaurentMazare/tch-rs#385]
I'm not sure if it's actually documented in the C++ API but the main practical feature of these functions is that they operate on [packed sequence](https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.PackedSequence.html) tensors, unlike `gru`, `lstm`, and `rnn_tanh` where different sequences must be separated by a batch dimension of the input tensor.

Also, I don't think there is any reason not to make these methods of `Tensor` acting on `self` instead of a `data` argument.

**Comment by LaurentMazare** [comment]
These functions are actually automatically generated from the PyTorch [Declarations.yaml file](https://github.com/LaurentMazare/tch-rs/blob/master/third_party/pytorch/Declarations-v1.9.0.yaml), the `operator_name` being one of `gru`, `lstm`, ... and the `overload_name` `data`. This crate is just a thin wrapper around these generated functions so it tries not to change the naming and/or ways the functions are applied. If you believe the name should be tweaked you can probably ask on the PyTorch repo and `tch-rs` will automatically pick up this change on the next PyTorch update.

**Comment by edlanglois** [comment]
Ah ok, I didn't realize that `Declarations.yaml` was part of pytorch. I thought that you might have specified the names for overloaded functions manually.
