### ISSUE TITLE
question: how does the borrow checker work?

### ISSUE THREAD

**Issue by makslevental** [LaurentMazare/tch-rs#396]
Sorry if this is a dumb n00b rust question but how exactly is the borrow checker performing its analysis if the memory associated with each tensor is actually being managed by libtorch, e.g. by [CPUAllocator](https://github.com/pytorch/pytorch/blob/master/c10/core/CPUAllocator.cpp#L102). Don't you, according to my understanding of rust, need `unsafe`s everywhere?

**Comment by LaurentMazare** [comment]
I'm not sure to understand your question properly but it's the case that this crate breaks some of the borrow checker aliasing assumptions, see #33 for more details, and this can lead to unsafe behaviors.
In practice this hasn't been much of an issue but this may still be a good motivation for writing a "safe" api. The tricky bit is that this would have to be written manually as I don't know of a way to know the aliasing behavior of the C++ functions that we bind to here.

**Comment by LaurentMazare** [comment]
Closing as there doesn't seem to be any further questions here, feel free to reopen if needed.
