### ISSUE TITLE
Batch dist

### ISSUE THREAD

**Issue by jafioti** [LaurentMazare/tch-rs#397]
In pytorch, there exists a pdist() function that has the ability to process a B x P x M tensor and a B x R x M tensor for getting batch distances, and outputs a B x P x R tensor. Is there a way to get this function in tch? Essentially to do what the dist() function already does, but on two more batch dimensions. 

If not, do you know of an efficient way to do this? Or even one just involving loops?

**Comment by LaurentMazare** [comment]
I only found this [pdist function](https://pytorch.org/docs/stable/generated/torch.nn.functional.pdist.html) in the PyTorch documentation but it doesn't seem to be the one you're referring to as it has a single tensor argument. This one can be accessed via `tensor.pdist(2.0)` in tch, see [here](https://docs.rs/tch/0.5.0/tch/struct.Tensor.html#method.pdist).
Maybe you're thinking about [PairwiseDistance](https://pytorch.org/docs/stable/generated/torch.nn.PairwiseDistance.html)? This should also be accessible in tch using the [pairwise_distance method](https://docs.rs/tch/0.5.0/tch/struct.Tensor.html#method.pairwise_distance).

**Comment by jafioti** [comment]
Sorry, I meant cdist, which I found in Tensor::cdist(). In the torch documentation, cdist has a compute mode parameter, which takes in a string. The tch binding takes in an Option<i64>. How does this map to the original function?

**Comment by LaurentMazare** [comment]
You can see how the string is mapped to this option in the [python code](https://pytorch.org/docs/stable/_modules/torch/functional.html#cdist) that is linked from the PyTorch documentation page of cdist that you linked at. Here is the relevant bit:
```python
    if compute_mode == 'use_mm_for_euclid_dist_if_necessary':
        return _VF.cdist(x1, x2, p, None)  # type: ignore[attr-defined]
    elif compute_mode == 'use_mm_for_euclid_dist':
        return _VF.cdist(x1, x2, p, 1)  # type: ignore[attr-defined]
    elif compute_mode == 'donot_use_mm_for_euclid_dist':
        return _VF.cdist(x1, x2, p, 2)  # type: ignore[attr-defined]
```

**Comment by jafioti** [comment]
Wow thanks!
