### ISSUE TITLE
how to build a batch tensor from a vector of reference tensor?

### ISSUE THREAD

**Issue by dbsxdbsx** [LaurentMazare/tch-rs#398]
Let me clarify the quesiton.  I am doing reinforcement learning, with a replay buffer storing lots of data, where each data is of struct:
```
pub struct Step {
    // pub struct Step<A> {
    pub obs: Tensor,
    pub action: Tensor,
    pub reward: f64,
    pub next_obs: Tensor,
    pub is_done: bool,
    //
    pub priority: f64, //used for priority sampling
}
```

and the Replay Buffer struct is like this:
```
pub struct Buffer {
    step_queue: VecDeque<Step>, //first in first out
    capacity: usize,            // max element in step_vec
    added_time: usize,
}
```
with the key implementation :
```
    use rand::seq::IteratorRandom;

    pub fn sample_a_batch(&self, batch_size: usize) -> Vec<&Step> {
        //if batch_size is 0, sample whole buffer size
        assert!(self.step_queue.len() > 0);

        if batch_size == 0 {
            self.step_queue.iter().collect()
        } else {
            //TODO:priority sample?
            let mut rng = rand::thread_rng();
            let xx = self.step_queue.iter().choose_multiple(&mut rng, batch_size);
            xx
        }
    }
```
Notice that The return type is  a  vector of reference of type `Step`.  The reason for returning `Step` is inspired by example `\examples\reinforcement-learning\policy_gradient.rs` ; and the reason for returning REFERENCE type is that I hope there is no copy operation AT ALL from sampling.  But here comes trouble when I stack tensor with the returned vector:
```let steps = buffer.sample_a_batch(batch_size);
  
  let actions: Vec<&Tensor> = steps.iter().map(|s| s.action).collect();//not ok,but I hope it could be ok
// it gives error like --- a value of type `Vec<&tch::Tensor>` cannot be built from an iterator over elements of type `tch::Tensor`
//the trait `FromIterator<tch::Tensor>` is not implemented for `Vec<&tch::Tensor>`
  // let actions: Vec<Tensor> = steps.into_iter().map(|s| (*s).action).collect();//not ok
  let batch_action_tensor = Tensor::stack(&actions, 0); // I hope this operator could do without any copy, too;
```
I wonder what is the correct way to construct a batch of say, actions by  a vector of reference tensor like this?
If there is noway to workaround, I guess the best way to do it is just following the implemention of replaybuffer in `examples\reinforcement-learning\ddpg.rs`?    (Besides, referring to this implemention, I think it would be perfect, if using `index_select` of a `Tensor` object could return  a REFERENCE TYPE without any copy）.

**Comment by LaurentMazare** [comment]
Sorry if I miss something obvious, but cannot you just do the following?
```rust
let actions: Vec<&Tensor> = steps.iter().map(|s| &s.action).collect();
let batch_action_tensor = Tensor::stack(&actions, 0);
```

**Comment by dbsxdbsx** [comment]
@LaurentMazare , thanks for your reply. Now it is worked with your suggestion.
By the way, do `Tensor::stack` and `Tensor::concat`  create a copied tensor ? If yes, does it have to ? Is there a way to refer to a stacked tensor by reference to original tensor, then using this stacked tensor to do some tensor calculation?

**Comment by LaurentMazare** [comment]
I would expect these to indeed copy the data around, and wouldn't really know a way to avoid this copy. Fwiw the Rust api is very similar to the Python PyTorch api here so might be worth checking whether this is possible on the Python side and if so trying to adapt how this is done there.

**Comment by dbsxdbsx** [comment]
@LaurentMazare ,I did a little google, and found that in-place concat/stack is not support yet from pytorch. I found this[ link](https://discuss.pytorch.org/t/concatenate-tensors-without-memory-copying/34609/6).  Maybe, this feature could be officially supported in future, [link](https://github.com/pytorch/pytorch/issues/22169).
