### ISSUE TITLE
Building the basic example fails

### ISSUE THREAD

**Issue by ehsanmok** [LaurentMazare/tch-rs#4]
Hi

First of all, thank you for the binding initiations. Rust needs to have it eventually :)

Running `cargo run --example basics` fails using `stable(1.0) cpu libtorch`

```
--- stderr
CMake Error at /home/ehsan/LibTorch/libtorch/share/cmake/Caffe2/public/utils.cmake:17 (add_dependencies):
  add_dependencies Cannot add target-level dependencies to INTERFACE library
  target "caffe2_library".

Call Stack (most recent call first):
  /home/ehsan/LibTorch/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:121 (caffe2_interface_library)
  /home/ehsan/LibTorch/libtorch/share/cmake/Torch/TorchConfig.cmake:39 (find_package)
  CMakeLists.txt:4 (find_package)
```

I think, we should consider adding a CI.

**Comment by LaurentMazare** [comment]
Hi,
Thanks for the feedback, yes CI would certainly be a good thing to add.
Re your compilation error, I haven't encountered it despite trying the pre-built cpu version 1.0.0 and 1.0.1 (as per build-version).
Is it on linux or on another platform ? I only tried linux on my side.

**Comment by ehsanmok** [comment]
Yes, it was on Ubuntu 14.04 with cmake 3.2

**Comment by LaurentMazare** [comment]
Interesting, googling a bit the closest I found to your error is this [issue](https://github.com/facebookarchive/caffe2/issues/2281). Not sure whether it's related but if it's the case updating to cmake 3.5.1 may fix the issue.

Alternatively you can try using the `cc` crate rather than `cmake` to compile. This can be done by replacing `build.rs` with the following. If this works for you we can either switching to `cc` or having an environment variable to decide between `cc` and `cmake`.

```rust
use std::env;
use std::path::PathBuf;
extern crate cc;

fn main() {
    let libtorch = env::var("LIBTORCH").expect("LIBTORCH not defined");
    let libtorch = PathBuf::from(libtorch);
    let libtorch_lib = libtorch.join("lib").into_os_string().into_string().unwrap();
    println!("cargo:rustc-link-search=native={}", libtorch_lib);
    println!("cargo:rustc-link-lib=c10");
    println!("cargo:rustc-link-lib=caffe2");
    println!("cargo:rustc-link-lib=torch");
    cc::Build::new()
        .cpp(true)
        .include(libtorch.join("include"))
        .include(libtorch.join("include/torch/csrc/api/include"))
        .flag(&format!("-Wl,-rpath={}", libtorch_lib))
        .flag("-std=c++11")
        .flag("-D_GLIBCXX_USE_CXX11_ABI=0")
        .file("libtch/torch_api.cpp")
        .warnings(false)
        .compile("libtorch");
}
```
You will also have to add the following line to `Cargo.toml` build-dependencies section:
```
cc = "1.0"
```

**Comment by ehsanmok** [comment]
`cc` worked! also upgraded my `cmake` to the latest v3.14 and it worked as well.

I think, `cc` is more self-contained and can have it as fallback.

**Comment by LaurentMazare** [comment]
Glad that it worked, I've actually already switched the github code to use `cc` by default (this actually was the case a couple days ago) and have the possibility to use `cmake` via some environment variable.

**Comment by ehsanmok** [comment]
I'm working on improving the `build.rs`. I'll send it today.

**Comment by LaurentMazare** [comment]
Cool!
Note that I changed it quite a bit lately: there is now a separate `torch-sys` crate (in the same repo). When the `LIBTORCH` variable is not set the build script will automatically download the binary version of libtorch - this is similar to what the tensorflow crate does for tf. The nice thing is that if you're happy with running the cpu version of libtorch, there is no setup needed anymore.

**Comment by LaurentMazare** [comment]
Closing this now, thanks for your help on this and feel free to re-open if there are further issues!
