### ISSUE TITLE
multiply a scalar with a tensor

### ISSUE THREAD

**Issue by infinite-Joy** [LaurentMazare/tch-rs#40]
I have a tensor T and I would like to make changes in the tensor. One way I can do that is by multiplying the tensor with a scalar. Is there a way to do that?

**Comment by LaurentMazare** [comment]
Not sure to understand exactly what you mean, but if your tensor is mutable you can do things like `t *= 4.2` if not mutable you can create a new tensor via `let u = t * 4.2;`.
There are a bunch of basic tensor operations like this covered in the tests, see [tensor_tests](https://github.com/LaurentMazare/tch-rs/blob/master/tests/tensor_tests.rs#L5-L8).

**Comment by infinite-Joy** [comment]
ah. got the main issue. in my case I was trying t * f32 while multiplication only with f64 is allowed. Thanks for the response.

**Comment by LaurentMazare** [comment]
Closing as I don't think there is much of an issue anymore.

**Comment by infinite-Joy** [comment]
Thanks for replying on this
