### ISSUE TITLE
question: Are there any support for .TIFF files ?

### ISSUE THREAD

**Issue by Tantatorn-dev** [LaurentMazare/tch-rs#400]
Hello
I attempted to load .TIFF image.
```
let image = image::load_and_resize("cat.tiff",224,224).unwrap();
```
and I got the error "unknown image type". So I wonder if there is something I can do to fix this issue ?

**Comment by LaurentMazare** [comment]
I don't think that's supported, we rely on [stb](https://github.com/nothings/stb/) for image decoding and you can see the list of supported formats in this [snippet](https://github.com/LaurentMazare/tch-rs/blob/8b16e2e06740b7038a6a34815699b2afcca8d4fa/torch-sys/libtch/stb_image.h#L19-L33). Your best option is probably to use something like the `convert` command line tool to convert all your images to a supported format.

**Comment by Tantatorn-dev** [comment]
Thanks a lot :)
