### ISSUE TITLE
question: how to assign elements of a `Tensor`

### ISSUE THREAD

**Issue by lostmsu** [LaurentMazare/tch-rs#401]
In PyTorch one can do

```python
t = torch.zeros([2,2])
t[0,0] = 1
```

**Comment by rustrust** [comment]
let tensor = Tensor::arange1(0, 2 * 2, opt).view([2, 2]);
    let index: &[_] = &[0, 0];
    let mut result = tensor.i((.., index));
    result += 1;
    result.print();

**Comment by lostmsu** [comment]
Seems like what I needed, when used with `.copy_`
