### ISSUE TITLE
Removing extern crate in examples

### ISSUE THREAD

**Issue by ravi-maithrey** [LaurentMazare/tch-rs#403]
In the examples, `extern crate tch` is used which is not needed since rust-2018. Is there any reason why this is still being used? I'm sorry if I might have missed something that was obvious. But if there is no reason to have it, I'd be more than happy to submit a pull request with those parts removed. 

My apologies if I asked a question that has already been answered but I tried to look around for closed issues or pull requests which might have dealt with this but I couldn't find any.

**Comment by LaurentMazare** [comment]
There is no good reason that I would know of. I guess it just came from all the examples being started by copying a previous example. Anyway I just pushed some changes to remove these, thanks for reporting this!

**Comment by ravi-maithrey** [comment]
No problem! Glad I could help
