### ISSUE TITLE
Is it possible to interchange a Tensor to an RGB image?

### ISSUE THREAD

**Issue by fgadaleta** [LaurentMazare/tch-rs#404]
It would be nice to have a Tensor to `RgbImage = ImageBuffer<Rgb<u8>, Vec<u8>>` from the image crate

Or is there anything like that already somewhere I am missing?

**Comment by LaurentMazare** [comment]
I'm not familiar with the image crate at all, but I imagine that just converting the tensor to a `Vec<u8>` then creating using `ImageBuffer::from_raw` should work fine. Maybe that's already what you're doing?
We have a bunch of helper functions for images in [imagenet.rs](https://github.com/LaurentMazare/tch-rs/blob/master/src/vision/imagenet.rs), this mostly contains functions to read/write images from file and resize them but we try to get this self contained so rely on the stb header to have a reasonably lightweight way of handling this.

**Comment by fgadaleta** [comment]
Brilliant!
I figured how to transform. Those helper functions are also great. Thank you!
