### ISSUE TITLE
Make the transitive dependency on curl and openssl optional

### ISSUE THREAD

**Issue by drewm1980** [LaurentMazare/tch-rs#407]
I'm encountering some installation friction due to the dependency on openssl headers.

I can't install libssl-dev in my ubuntu based container due to some packaging issue unrelated to this crate.

This is a transitive dependency: tch-rs -> torch-sys -> curl -> openssl-sys.

If this dependency were behind an optional feature, I could work around this by disabling it. It's probably just for downloading libtorch anyway, and that should already be in my container. 

Thanks!

**Comment by LaurentMazare** [comment]
Thanks for the feedback, I've just pushed some changes to move the curl download bits behind a feature gate. Note that this is in the default set of features for the `tch` crate though, so you will need to use `default-features = false` or similar when specifying the dependency.
Let me know if you run into any issue using this.

**Comment by drewm1980** [comment]
Thanks! And thanks for the crate, by the way! Implementing neural networks in rust is no longer totally insane because of this crate :)
