### ISSUE TITLE
support cross compiling with "wasm32-unknown-unknown"

### ISSUE THREAD

**Issue by amiralipour** [LaurentMazare/tch-rs#408]
Thank you for your great work, I really thing this is going to be a break through in high performance ml .
I created an inference crate using this and then tried to compile to web assembly, I tried to manually editing the dependencies but it seems to be an un trivial amount of work to make it compile with ` cargo build --target wasm32-unknown-unknown` target.
Any idea how I can do this or any plans to support making this crate compile-able to the web assembly?
Thanks

**Comment by LaurentMazare** [comment]
Closing this for now as there are no immediate actions.

**Comment by xloem** [comment]
Just a note, from https://github.com/guillaume-be/rust-bert/issues/92#issuecomment-717076016, that nimtorch compiles to wasm, although it is not rust: https://github.com/sinkingsugar/nimtorch . It is also notable that pytorch itself can build in a mobile mode that disables most of the platform-dependent components.
