### ISSUE TITLE
Module-like methods for VarStore

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#415]
Hello,

Based on https://github.com/guillaume-be/rust-bert/issues/183, I am currently thinking of an effective way of implementing module-level conversion to and from half-precision. Pytorch's model are based on an object-oriented approach where a `nn.Module` stores both the model weights and associated forward method. This allows the user to call conversion or device placement method directly at the module level:
```python
class NeuralNet(nn.Module)
    def __init__(self):
        self.layer = nn.Linear(10, 42)

    def forward(self, x):
         return self.layer(x)

model = NeuralNet()
model = model.half()
model = model.cuda(0)
```

This is particularly useful when working with large models, where at prediction-time the process would be to:
1. Instantiate the model on the CPU/memory and load weights in full precision
2. Cast the model to half-precision
3. Move the model to the GPU buffer

In _tch_ the model behaviour (for example implementing `ModuleT`) is separated from the parameter storage (in a `VarStore`). I could not find methods to perform the half-precision conversion at an entire module level or to move a module between devices. I believe this could be done by extending the current `VarStore` or `Path` with additional methods:
1. `to_device(device: Device)`: move a `VarStore` or a `Path` to the given device. possibly extended with `cpu()` and `cuda(usize)` helpers
2. `half()`: converts all registered `Tensor` in a `Path` to half-precision if the tensor is of floating-point type, see https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module)
2. `bloaft16()`: converts all registered `Tensor` in a `Path` to bfloat16 half-precision if the tensor is of floating-point type
3. `float()`: converts all registered `Tensor` in a `Path` to single precision if the tensor is of floating-point type
4. `double()`: converts all registered `Tensor` in a `Path` to double precision if the tensor is of floating-point type

Do you think this would be a reasonable approach to implement the Pytorch's `nn.Module` utilities? If so I'd be happy to work on an update for your review to enable convenient casting to half precision and model device placement.

**Comment by LaurentMazare** [comment]
Thanks for the detailed write-up.
Indeed a var-store is attached to a device, but it's not really attached to a *Kind* (float/double/half) at the moment as mostly everything is done with float. Having only one Kind for a var-store is an interesting idea and probably an improvement over the current setup but I'm wondering how common it is for models to use mixed precision in a way this would be a problem here.
When it comes to moving tensors across devices, `VarStore::load` and `VarStore::copy` let you load some tensor to a device based respectively on a file or another var store. Typically, I would have thought that the workflow you describe would work by loading directly the weights to the gpu in half precision via `VarStore::load` but maybe there is some interest in having the intermediary steps?
Another thing is that tensors get added to a var-store when creating the model (e.g. the `ModuleT`), so if there was a way to move a var-store I'm not really sure how this would be used to then create a model, somehow this would need to re-use the variables rather than to create fresh ones? I think the current implementation of `VarStore::add` would just create fresh tensors with new paths.

**Comment by guillaume-be** [comment]
Thank you for the response. I think my description was misleading, please allow me to clarify.

The extension I would have in mind would not change the `Kind` of an entire `VarStore`. Rather - it would change the `Kind` of the eligible underlying `Tensors` (those that have a _Float-like_ Kind). This would be similar to the behaviour of the `nn.Module` implementation in [Pytorch](https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module):
```python
def half(self: T) -> T:
    r"""Casts all floating point parameters and buffers to ``half`` datatype.

    .. note::
        This method modifies the module in-place.

    Returns:
        Module: self
    """
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
```

Similarly to the existing `freeze()` and `unfreeze()` method of the `vartStore`, I would suggest performing these `half()` and `float()` operations in-place, along the lines of:
```rust
pub fn half(&mut self) {
    let variables = self.variables_.lock().unwrap();
    for (_, variable) in variables.named_variables.iter() {
        if variable.is_floating_point() {
            let _v = variable.to_kind(Kind::Half);
        }

    } 
}
```

Ideally, this method would also be available on a `Path` - this would require having the possibility of being able to iterate through all children of a given `Path` (not sure if this already doable). The `half` method could also be implemented at a `VarStore` level by calling `half()` on its `root`. The value behind this would be to allow having 2 models sharing a VarStore, and just calling `half` on the path used by one of these. 

I would suggest implementing methods to move between devices the same way, this prevents having to `load` or `copy`, but instead changes the tensors and their devices in-place. I believe this would then not break the tensor registration post- model registration.

Finally, regarding your question of loading directly the tensors in half-precision: I believe this would require having multiple version of the weight files based on their precision? This would also possibly make the de-serialization process more complex, since the underlying `Kind` of the model will have to be inferred from loaded weights (this impacts the type of tensors that are created "on-the-fly" during prediction). The intermediary steps allow loading the full-precision model on the CPU, where memory is usually abundant - convert it to half-precision and then only move it to the GPU buffer.

**Comment by LaurentMazare** [comment]
Ah makes sense, your plan of adding these `half` and `float` sounds good, and indeed if it's done in place it should hopefully work well with model creation. If you want to take a stab at it, happy to review a PR.
I certainly like the idea of being able to do it at a path level (and for all subpaths), maybe it's not needed for a first cut though but that would feel pretty convenient.
When it comes to loading in half-precision, I was more thinking that the load function would perform the `to_kind` so it would not really depend on the data to deserialize but more on a parameter of the function (or some characteristic of the var-store).
