### ISSUE TITLE
New `set_kind` and `set_device` method not updating actual tensors

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#418]
Hello,

Following https://github.com/LaurentMazare/tch-rs/pull/416 I have tried to use these new features to move models between devices and change their precision. Unfortunately, it seems the current solution is not working quite as intended yet. While the `VarStore`'s Tensors are updated correctly (checked in unit tests), the tensors used by the layers do not seem to be updated. The following example illustrates the issue:

```rust
use tch::nn::VarStore;
use tch::{nn, Device, Kind};

fn main() {
    let mut var_store = VarStore::new(Device::Cpu);
    let root = var_store.root();

    let layer = nn::linear(&root / "linear", 10, 42, Default::default());

    var_store.set_device(Device::Cuda(0));

    // Returns Cuda(0) for both weights and biases
    for (var_name, tensor) in &var_store.variables_.lock().unwrap().named_variables {
        println!("{} - {:?}", var_name, tensor.device());
    }

    // Returns CPU for both
    println!("ws device: {:?}", layer.ws.device());
    println!("bs device: {:?}", layer.bs.device());

    let dummy_input = tch::Tensor::randn(&[10], (Kind::Float, Device::Cuda(0)));

    // Crashes: dummy_input is on Cuda(0) while `layer` is on CPU
    let _ = dummy_input.apply(&layer);
}
```

I don't believe that the registration of variables in the `Varstore` duplicates the actual tensor data (and the Tensor data is probably moved correctly between devices and/or cast to a new `Kind`). My understanding is that the Rust `Tensor` object are 2 distinct objects in the `VarStore` and in a layer (e.g. a `Linear.ws`), but these share the same underlying memory. When the `VarStore` is updated the metadata and pointer of the layer are not updated, causing an error.

I cannot think of a way to update the `Tensor` object that was registered in the var store (which is the one we are usually interested in), maybe you have an idea on how this could be achieved?

**Comment by LaurentMazare** [comment]
Hi,
Indeed that doesn't seem to work, I would have thought that the C++ versions of `to_kind` and `to_device` actually move/convert the underlying storage but it seems that they create a new copy, so the model continues to use the old version.
I quickly looked at the C++ api and haven't found anything to do the operation in place so I'm pretty unsure about how to get this to work without introducing an additional level of indirection (which seems to be a bit too much added complexity).

**Comment by guillaume-be** [comment]
Hi,
Thank you for the feedback. I also noticed that `Tensors` don't seem to have an in-place method for type casting or device allocation. This actually is also the case for the Pytorch version (see the [pytorch docs](https://pytorch.org/cppdocs/api/classtorch_1_1nn_1_1_module.html#_CPPv4N5torch2nn6Module2toEN5torch6DeviceEN5torch5DtypeEb)) where `type` actually returns a copy of the tensor with a new type. The behaviour seems to be different at the `nn.Module` where methods such as `to([device])` perform the conversion in-place.

Libtorch seems to provide a similar API for its `Module`, allowing for an in-place conversion for both the type and the device, see 
the related [libtorch docs](https://pytorch.org/cppdocs/api/classtorch_1_1nn_1_1_module.html#_CPPv4N5torch2nn6Module2toEN5torch6DeviceEN5torch5DtypeEb). This relies on a [`set_data` mechanism](https://github.com/pytorch/pytorch/blob/2a4d5e4c6d4a7b307b94425f66bbdf727e482080/torch/csrc/jit/api/module.cpp#L184) for variables and tensors. I see `set_data` in the OCaml binding generation file, but can't find the method in the Rust API.

**Comment by LaurentMazare** [comment]
Hello,
I've just pushed some changes to expose `set_data`. Do you think that this wouldn't work? I would have some hope for it to have a chance as it modifies the C++ tensor object in place rather than creating a new object, the [test](https://github.com/LaurentMazare/tch-rs/blob/6fbdbcac852d759c6993be09909f527e67ae7a40/tests/tensor_tests.rs#L496-L501) that I added as part of this addition would not work for `copy_` but would for `set_data`. Could you give a try at using this?

**Comment by guillaume-be** [comment]
Hi,
Thank you very much for exposing `set_data`. I have just tested it and it looks like it is working - I am proposing a small PR that updates the behaviour of the `VarStore` operations for type casting and device migration, along with tests testing that the layers registered on this var store get updated as well. Thanks again!

**Comment by LaurentMazare** [comment]
Thanks, the PR has been merged, let us know if this causes any issue when using in rust-bert.

**Comment by dbsxdbsx** [comment]
@guillaume-be , I just wonder if this modification could help solve this issue:https://github.com/LaurentMazare/tch-rs/issues/423
