### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by skyne98** [LaurentMazare/tch-rs#432]
Hi there! 

First, awesome project! To give some context, I have never used PyTorch before and I have a question related to Vulkan and AMD GPUs. It [seems like](https://pytorch.org/tutorials/prototype/vulkan_workflow.html#c-api) PyTorch supports running using Vulkan compute.

Does it mean it should be possible to enable it in the bindings as well to run models on, let's say, AMD GPUs and maybe even Android?

If it's easy enough and doesn't require any specialized knowledge, I can even try to help!

Thanks!

**Comment by LaurentMazare** [comment]
I just merged some changes to include Vulkan support, that said the Vulkan backend is not included by default so you would need to rebuild libtorch with the appropriate flag to use this.
When it comes to AMD gpus, an alternative would be the ROCm builds which are now officially supported and available on the pytorch website, when using these specifying a cuda device should result in your AMD gpu being used.
