### ISSUE TITLE
Some example build fails on Arm64 environment(Armbian Focal) with Libtorch1.10.1 source build

### ISSUE THREAD

**Issue by ycat3** [LaurentMazare/tch-rs#436]
I am using Rockpro64 SBC with Armbian Focal and I am developing Rust application.
Libtorch1.10.1 native build for Arm64 from pytorch source tree is successful.
I followed the tch-rs instruction and some tch-rs examples work fine.
cargo run --example basics
cargo run --example mnist
Accordingly I believe my Libtorch environment is correct.
However, other example build fails.
cargo test
cargo run  --example pretrained-models

Rust 1.57.0 says
help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified

What kind of native libraries to install ?

------------------------------------------------------------
rock64@rockpro64:~/tch-rs$ cargo run --example pretrained-models
   Compiling tch v0.6.1 (/home/rock64/tch-rs)
error: linking with `cc` failed: exit status: 1
//
 = note: /usr/bin/ld: /home/rock64/tch-rs/target/debug/deps/libtorch_sys-0f95d54be7ee1814.rlib(torch_api.o): in function `torch::jit::Object::type() const':
          /home/rock64/libtorch/include/torch/csrc/jit/api/object.h:37: undefined reference to `torch::jit::Object::_ivalue() const'
          /usr/bin/ld: /home/rock64/tch-rs/target/debug/deps/libtorch_sys-0f95d54be7ee1814.rlib(torch_api.o): in function `torch::jit::slot_iterator_impl<torch::jit::detail::NamedPolicy<torch::jit::detail::ParameterPolicy> >::cur() const':
          /home/rock64/libtorch/include/torch/csrc/jit/api/module.h:370: undefined reference to `torch::jit::Object::_ivalue() const'
          /usr/bin/ld: /home/rock64/libtorch/include/torch/csrc/jit/api/module.h:370: undefined reference to `torch::jit::Object::_ivalue() const'
          /usr/bin/ld: /home/rock64/tch-rs/target/debug/deps/libtorch_sys-0f95d54be7ee1814.rlib(torch_api.o): in function `torch::jit::slot_iterator_impl<torch::jit::detail::NamedPolicy<torch::jit::detail::ParameterPolicy> >::next()':
          /home/rock64/libtorch/include/torch/csrc/jit/api/module.h:386: undefined reference to `torch::jit::Object::_ivalue() const'
          /usr/bin/ld: /home/rock64/libtorch/include/torch/csrc/jit/api/module.h:396: undefined reference to `torch::jit::Object::_ivalue() const'
          /usr/bin/ld: /home/rock64/tch-rs/target/debug/deps/libtorch_sys-0f95d54be7ee1814.rlib(torch_api.o):/home/rock64/libtorch/include/torch/csrc/jit/api/module.h:407: more undefined references to `torch::jit::Object::_ivalue() const' follow
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `tch` due to previous error
------------------------------------------------------------------------------------------------------

**Comment by ycat3** [comment]
Solved
rebuild 1.10.0.a0 from source tree.
It works.
tch-rs example build is OK.
USE_MKLDNN=OFF flag is also important.

**Comment by LaurentMazare** [comment]
Great that you worked it out, indeed the `tch-rs` crate is pinned to an exact libtorch version (usually the last release though it may lag by a few days/weeks).

**Comment by LaurentMazare** [comment]
Closing this for now, feel free to re-open if further issues.
