### ISSUE TITLE
Use meaningful reduction parameter in Tensor API

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#44]
Several Tensor methods, for example [mse_loss()](https://docs.rs/tch/0.0.9/tch/struct.Tensor.html#method.mse_loss), has i64 typed reduction parameter. It's less intuitive for users is suggested to replace it with [existing enum](https://docs.rs/tch/0.0.9/tch/enum.Reduction.html).

It seems this patch requires a patch on auto-generated source. Suppose we can separate the sys API and wrapper api? For now I find the mapping in this [Torch source](https://github.com/pytorch/pytorch/blob/master/torch/nn/_reduction.py).

**Comment by LaurentMazare** [comment]
I just pushed some changes so that the generated wrappers use the `Reduction` type that you mentioned. It works by looking at the parameter name and type when generating the code so it's probably not the most robust thing but it seems to be reasonable on the current operators.

**Comment by jerry73204** [comment]
Thanks!
