### ISSUE TITLE
Unfold

### ISSUE THREAD

**Issue by semtexzv** [LaurentMazare/tch-rs#465]
I'm using your wonderful library to implement RAFT model for some video work, and I've encountered a snag with 

https://pytorch.org/docs/stable/generated/torch.nn.functional.unfold.html?highlight=unfold#torch.nn.functional.unfold

It seems that this function maps to some other function in tch-rs.

https://docs.rs/tch/latest/tch/struct.Tensor.html#method.unfold has a completely different set of arguments.

**Comment by LaurentMazare** [comment]
Looking at the Python implementation of [unfold](https://pytorch.org/docs/stable/_modules/torch/nn/functional.html#unfold), it seems to call the PyTorch `im2col` C++ function under the hood and not the `unfold` one. You can access this function via Rust, see [im2col on docs.rs](https://docs.rs/tch/latest/tch/struct.Tensor.html#method.im2col) which arguments are more in line with the Python version.

**Comment by semtexzv** [comment]
Thank you!. I was able to resolve my issue. Still, It'd be nice to add this function to bring the API closer to the python one.
