### ISSUE TITLE
Error: Internal torch error: Legacy model format is not supported on mobile while loading *.ot weights.

### ISSUE THREAD

**Issue by metobom** [LaurentMazare/tch-rs#469]
I am trying to test this example: "cargo run --example pretrained-models -- resnet18.ot tiger.jpg". but in "vs.load(&args[1])?;" line, I get this error 

`Error: Internal torch error: Legacy model format is not supported on mobile.
Exception raised from deserialize at ../torch/csrc/jit/serialization/import.cpp:267 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7fa5788f80eb in /home/m3/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 0xd1 (0x7fa5788f3c41 in /home/m3/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x35dd53d (0x7fa57c11953d in /home/m3/libtorch/lib/libtorch_cpu.so)
frame #3: torch::jit::load(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x1cd (0x7fa57c11a8ad in /home/m3/libtorch/lib/libtorch_cpu.so)
frame #4: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0xc1 (0x7fa57c11c4c1 in /home/m3/libtorch/lib/libtorch_cpu.so)
frame #5: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>) + 0x6f (0x7fa57c11c5cf in /home/m3/libtorch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0xb3c53 (0x55565335ac53 in target/debug/examples/pretrained-models)
frame #7: <unknown function> + 0x2f452 (0x5556532d6452 in target/debug/examples/pretrained-models)
frame #8: <unknown function> + 0x2fc9a (0x5556532d6c9a in target/debug/examples/pretrained-models)
frame #9: <unknown function> + 0x29900 (0x5556532d0900 in target/debug/examples/pretrained-models)
frame #10: <unknown function> + 0x2c2bb (0x5556532d32bb in target/debug/examples/pretrained-models)
frame #11: <unknown function> + 0x2f8fe (0x5556532d68fe in target/debug/examples/pretrained-models)
frame #12: <unknown function> + 0x2f8d1 (0x5556532d68d1 in target/debug/examples/pretrained-models)
frame #13: <unknown function> + 0xf2210 (0x555653399210 in target/debug/examples/pretrained-models)
frame #14: <unknown function> + 0x2f8a0 (0x5556532d68a0 in target/debug/examples/pretrained-models)
frame #15: <unknown function> + 0x2bfcc (0x5556532d2fcc in target/debug/examples/pretrained-models)
frame #16: __libc_start_main + 0xf3 (0x7fa5785180b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #17: <unknown function> + 0x2870e (0x5556532cf70e in target/debug/examples/pretrained-models)`

I installed tch-rs as follows, I downloaded this
* https://download.pytorch.org/libtorch/cu113/libtorch-cxx11-abi-shared-with-deps-1.11.0%2Bcu113.zip

libtorch .zip file and added these lines to my .bashrc:

* export LIBTORCH=/home/m3/libtorch
* export LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH 

then just built tch-rs repo with
*  cargo build

Am I doing something wrong?

**Comment by LaurentMazare** [comment]
Thanks for reporting this, the model weights had to be re-exported to match the new PyTorch 1.11 version. I've done so for [resnet18.ot](https://github.com/LaurentMazare/tch-rs/releases/download/untagged-eb220e5c19f9bb250bd1/resnet18.ot) and [resnet34.ot](https://github.com/LaurentMazare/tch-rs/releases/download/untagged-eb220e5c19f9bb250bd1/resnet34.ot) and will adapt other files over the next few days.
