### ISSUE TITLE
Copy VarStore over devices

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#47]
I raised this question for multi-GPU. In my scenario, I would run forward step on multiple GPU devices. Then, after computing gradient on one device, I would like to copy the model parameters over.

I seems there's no easy way to copy the model parameters. `VarStore::trainable_variables()` returns vec of tensors does not help much. Also, I did not see demanding method of `tch::nn::Path` to iterate over known variables.

So far the only solution I came up with is to save the `VarStore` to a file, and load them back into multiple devices. However, it implies overhead. Does anyone have suggestion for this?

**Comment by LaurentMazare** [comment]
I imagine that you're creating one `VarStore` per device. In this case writing to a file certainly doesn't sound optimal to synchronise them.
You could imagine copying the tensors returned by `VarStore::trainable_variables` but there are no guarantees on the order so this would be a bit fragile. When I get a chance I'll add a `VarStore::copy` function that would make the copy in a more robust way, this should not be very difficult.

**Comment by LaurentMazare** [comment]
I just added a function `vs.copy(&src)` that should modify all the values from `vs` by copying the associated value in `src`. This returns an error if the name doesn't appear in `src`.

**Comment by jerry73204** [comment]
Nice. It happens that I implement my own [copy](https://github.com/jerry73204/tch-rs/tree/copy-varstore) in the same time. I will adopt your more cleaner code.
