### ISSUE TITLE
Support for model pruning

### ISSUE THREAD

**Issue by aegroto** [LaurentMazare/tch-rs#471]
Hello, does this wrapper already support any toolbox for model pruning? I've stumbled upon this method https://docs.rs/tch/latest/tch/struct.Tensor.html#method.f_internal_rowwise_prune but it seems undocumented.

**Comment by LaurentMazare** [comment]
Hi, this wrapper mostly generates automatically Rust functions around the PyTorch C++ api. There is no specific support for pruning so it would only be available if the C++ api provides it, using the C++ functions marked as internal might be tricky though I would recommend seeing how the Python api implements pruning and trying to replicate this on the Rust side.

**Comment by aegroto** [comment]
Ok, thanks, I will take a look at it!
