### ISSUE TITLE
Convenience methods on tch::jit::IValue to get variants

### ISSUE THREAD

**Issue by neilisaac** [LaurentMazare/tch-rs#491]
For methods returning an IValue, we generally know what it contains, but it's awkward to consume by matching enum variants.

Simple case: 
```rust
// current
let result: IValue = object.method_is(...)?;
let tensor = match result {
  IValue::Tensor(t) => t,
  v => { return Err(...) },
};

// desired
let tensor = object.method_is(...)?.into_tensor().map_err(...)?;
```

This code quickly degenerates if a model returns an IValue::Tuple of tensors for example.

Consider using [EnumAsInner](https://docs.rs/enum-as-inner/0.5.0/enum_as_inner/) or hand-writing extraction methods (`as_variant()`/`into_variant()`) for each IValue enum variant.

**Comment by LaurentMazare** [comment]
Did you try using `try_from` for this, this should make for reasonably simple code, see for example [this test](https://github.com/LaurentMazare/tch-rs/blob/3ef1035d6aca50c03bf53d375ac7e6857ff604e8/tests/jit_tests.rs#L45), though it wouldn't make it as easy to customize the errors.

**Comment by neilisaac** [comment]
`impl TryFrom<IValue> for Tensor` resolves this, thanks!  May want to add `impl TryFrom<IValue> for Object` too.

**Comment by LaurentMazare** [comment]
Ah good catch, this conversion was indeed missing and I just added it in #686. You can see an example using it in [this test](https://github.com/LaurentMazare/tch-rs/blob/abf8240cd41378cede3b59dcbb142e4c5a846b26/tests/jit_tests.rs#L125).

**Comment by neilisaac** [comment]
nice thanks!
