### ISSUE TITLE
Consider publishing 0.8 / Torch 1.12 support to crates.io

### ISSUE THREAD

**Issue by philpax** [LaurentMazare/tch-rs#504]
Hi there! Awesome work with `tch`, it's wonderful being able to work with Torch from Rust.

Just wanted to mention that it might be worth publishing the 1.12 support or otherwise making it clear that the current published version only supports 1.11; I downloaded 1.12-release-with-cuda for Windows last night, and spent more time than I'd like to admit trying to figure out why I was getting compilation errors with 0.7.2.

Switching to a Git dependency on `tch` solved my issue, but that might not be super obvious to others.

Cheers!

**Comment by LaurentMazare** [comment]
The 0.8 version should be available on crates.io now!

**Comment by philpax** [comment]
Brilliant, thank you! ❤️
