### ISSUE TITLE
apple m1 GPU support

### ISSUE THREAD

**Issue by jianshu93** [LaurentMazare/tch-rs#517]
Dear torch rust team,

The newest version of PyTorch (https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/) also support apple M1 devices via the MPS interface provided by apple. I am wondering whether this is also doable here. Libtorch version 1.12 can be installed and compiled on M1 device but I do not know how the GPU was supported (via universal binary or something related to that). 

Thanks,

Jianshu

**Comment by LaurentMazare** [comment]
Closing this now that support for the MPS device has been merged.

**Comment by jianshu93** [comment]
oh Many Thanks！

Jianshu
