### ISSUE TITLE
Interop with ndarray

### ISSUE THREAD

**Issue by grtlr** [LaurentMazare/tch-rs#52]
Continue discussion from #51.

Interoperability with the [`ndarray`](https://docs.rs/ndarray/0.12.1/ndarray/) crate would be very nice. As a first step I think we should be able to convert to/from ndarray using `std::convert::Into`. I'm thinking something along these lines:

```rust
use ndarray::{Array, ArrayD, Dimension, IxDyn};

pub fn to_tensor<D>(arr: Array<f64, D>) -> tch::Tensor
where
    D: Dimension,
{
    let tn = tch::Tensor::of_slice(arr.as_slice().unwrap());
    let shape: Vec<i64> = arr.shape().iter().map(|s| *s as i64).collect();
    tn.reshape(&shape)
}

pub fn from_tensor(tensor: &tch::Tensor) -> ArrayD<f64> {
    let v: Vec<f64> = tensor.into();
    let shape: Vec<usize> = tensor.size().iter().map(|s| *s as usize).collect();
    ArrayD::from_shape_vec(IxDyn(&shape), v).unwrap()
}
```

**Comment by LaurentMazare** [comment]
This would indeed be pretty convenient and I think your implementation looks good. One point I'm not sure is whether tensor.into() first calls tensor.contiguous(). If that's not the case it may be worth doing so (and probably good to have a test where we apply from tensor to a 2d tensor that we've sliced on the second dimension).
Would you want to craft a PR for this ? (if you prefer not to, I can also make the change when I get a chance).

**Comment by grtlr** [comment]
I could definitely create a PR for this. It'll be another week or two before I find the time, though.

**Comment by LaurentMazare** [comment]
Cool, let me know if I can be of any help (also if you happen to be at ICML and want to discuss ML in rust, more than happy to do so!).

**Comment by grtlr** [comment]
I will, thanks for the offer! Unfortunately, I’m not at ICML otherwise this would have been very nice!

**Comment by grtlr** [comment]
So I was thinking about how to integrate this in `tch-rs`. Should we include `ndarray` behind a feature flag?

**Comment by LaurentMazare** [comment]
Maybe we can even have it as a normal dependency for now (without any feature flag) ? The number of dependencies for the `ndarray` crate seems quite small so I would hope for it to get compiled/installed quickly. If that's not the case we can later revisit.

**Comment by LaurentMazare** [comment]
Closing now that #55 has been released.
