### ISSUE TITLE
Installation instructions update

### ISSUE THREAD

**Issue by lumost** [LaurentMazare/tch-rs#525]
Thanks for the hard work on this project!

The current installation instructions can be error prone as the torch developers do not expose the 1.12.0 download link readily, and the instructions direct to the torch website.  Would it be possible to deep link to the download instead? I believe the following links should cover most users.

Linux CUDA: https://download.pytorch.org/libtorch/cu113/libtorch-cxx11-abi-shared-with-deps-1.12.0%2Bcu113.zip

OSX: https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.12.0.zip

**Comment by ChrisBeeson** [comment]
Any idea where we can get an arm64 build from?

**Comment by lumost** [comment]
Does the condo install include packaging and exporting libtorch?  I didn't notice the libtorch headers in any obvious location - but I may not have looked hard enough.

It may be worth wrapping the c library in its own cargo package through CXX-build.  That would take care of both versioning and architecture.

**Comment by LaurentMazare** [comment]
Building libtorch takes a very long time with some complex build system setup so I would rather not vendoring it through cargo. Vendoring the headers only might be a possibility though not a huge fan of handling redistributing these neither. As for the deep links, I would be a bit worried on how they may change between version etc, it feels that the main pytorch website does a good job at having a landing page to pick up the version so maybe the instructions should just be more explicit on how to select the version there?

**Comment by LaurentMazare** [comment]
Closing this for now, feel free to re-open if this prove to still be an issue.
