### ISSUE TITLE
Direct modification of network weights?

### ISSUE THREAD

**Issue by rustrust** [LaurentMazare/tch-rs#533]
If I want to introduce my own direct modification of network weights, what is the recommended method for doing this? We might look at mnist_conv.rs as an example--suppose that I want to modify net.fc1.ws directly. Do I need to lock the varstore as in sparse_adam.rs?

**Comment by LaurentMazare** [comment]
Right, grabbing the lock to access the weights stored in the varstore sounds like the appropriate way to go.

**Comment by rustrust** [comment]
I think this is working for me. For others who come across this, I used the custom-optimizer as an example of how to proceed here and did find it sufficient. But in the event there are lurking footguns, maybe some more documentation is in order?
