### ISSUE TITLE
of_ prefix vs from_ -- Rust naming conventions?

### ISSUE THREAD

**Issue by virtualritz** [LaurentMazare/tch-rs#537]
Sorry if this a stupid question.
Why does this crate use an `of_` prefix rather than the canonical `from_` for (some but not all) type conversion constructors. I.e. `Tensor` uses `from_ptr()` but `of_slice()`.
See [Rust API Guidelines/Naming/Casing conforms to RFC 430 (C-CASE)](https://rust-lang.github.io/api-guidelines/naming.html), first table:

> Conversion constructors -- `from_some_other_type`

**Comment by LaurentMazare** [comment]
This was mostly for historical reasons (this crate started as a port of the ocaml-torch bindings and the convention on the ocaml side leans more towards `of_...` than `from_...`). We've released some similar breaking changes lately and it all went well so I've made the changes for this too in #706.

**Comment by LaurentMazare** [comment]
Closing this now that the functions have been renamed, feel free to reopen if further issues.
