### ISSUE TITLE
Indexing results in different Tensors compared to Python

### ISSUE THREAD

**Issue by ahmed-alhindawi** [LaurentMazare/tch-rs#539]
Hello,

I'm converting a Python library to Rust using tch-rs but I'm having issues with indexing. I've narrowed the problem to indexing a Tensor by another Tensor. The python program:

```python
rand_ts = torch.randn((2, 2, 10, 10))
t1 = torch.Tensor([1, 2, 3]).to(int)
t2 = torch.Tensor([5, 6, 7]).to(int)

out = rand_ts[0, 1, t1, t2]
print(out.size())
```

In Rust:
```rust
fn main() {
    let rand_t = Tensor::randn(&[2, 2, 10, 10], (tch::Kind::Float, tch::Device::Cpu));
    let hindex = Tensor::of_slice(&[0, 1, 2]);
    let windex = Tensor::of_slice(&[5, 6, 7]);

    let subselected = rand_t.i((0, 1, &hindex, &windex));
    println!("{:#?}", subselected.size().as_slice());
}
```

Python results in a Tensor of shape `[3]` whilst tch-rs results in a Tensor of shape `[3, 3]`.

Any thoughts on how to get tch-rs indexing to output something similar to Python's PyTorch?

Many thanks.

**Comment by LaurentMazare** [comment]
You should be able to get the Python behavior by using `tensor.index` rather than `t.i`, e.g.:
```rust
let selected = t.index(&[
        Some(Tensor::from(0i64)),
        Some(Tensor::from(1i64)),
        Some(Tensor::of_slice(&[1i64, 2, 3])),
        Some(Tensor::of_slice(&[5i64, 6, 7])),
    ]);
```
I've put together a small test to examplify this [here](https://github.com/LaurentMazare/tch-rs/blob/640d00a5cdf71cdcc69d6b13e036b63046e57920/tests/tensor_indexing.rs#L145-L150).

**Comment by ahmed-alhindawi** [comment]
That works beautifully. Thank you.

Is there any documentation for the differences between `i(..)` and `index(...)` ?

**Comment by LaurentMazare** [comment]
There is a related comment in the [documentation](https://docs.rs/tch/latest/tch/index/index.html) where it's mentioned that the behavior of `.i` is different from numpy advanced indexing (which would be equivalent to `.index`) though it's certainly hard to discover this documentation before running into issues.

**Comment by ahmed-alhindawi** [comment]
I must say that I _did_ read that documentation before opening this issue but I can't see where it would mention trying to use `.index` instead of `.i` or that their behaviour would be different.

Thank you for all of your kind help and an excellent library otherwise! Phenomenal work.

**Comment by LaurentMazare** [comment]
Ah good point that `.index` is not mentioned there, we should add something about `.index` giving a behavior closer to the numpy advanced indexing. Feel free to make a PR for this if you have the time, if not I'll add something soonish.
