### ISSUE TITLE
Are you interested in moving the Stable Diffusion example to it's own repo?

### ISSUE THREAD

**Issue by siriux** [LaurentMazare/tch-rs#555]
First, thanks for writing the Stable Diffusion example, it seems really cool.

I think it would greatly benefit from being in an independent repository where it can evolve and improve to catch up with the multiple optimizations and features we see in the python world.

Are you interested in creating this repository yourself, or would you prefer that someone else forks your code and keeps working on it?

**Comment by LaurentMazare** [comment]
The code has been moved to a separate repo now, [diffusers-rs](https://github.com/LaurentMazare/diffusers-rs). The very large monolithic file has also been split in a structure which is mostly based on huggingface's [diffusers Python api](https://github.com/huggingface/diffusers).
