### ISSUE TITLE
`f_arange_start_step` does not take step argument

### ISSUE THREAD

**Issue by danieldk** [LaurentMazare/tch-rs#559]
I can't link to the source line, since the generated file is too large, but `master` has the following generated signature for this function:

```
pub fn f_arange_start_step<S: Into<Scalar>>(
        start: S,
        end: S,
        options: (Kind, Device),
    ) -> Result<Tensor, TchError>
```

The `step` argument is missing, giving this the same signature as ` f_arange_start`. This is a regression compared to the current stable version.

**Comment by LaurentMazare** [comment]
Thanks for reporting this, this was caused by the `step` parameter getting a default value and such scalar parameters being omitted currently in `tch`. I've just pushed some changes that should force this parameter to appear.

**Comment by danieldk** [comment]
Thanks! With this change I can now compile [syntaxdot](https://github.com/tensordot/syntaxdot) and pass all tests.
