### ISSUE TITLE
Unit test work but doctest not.

### ISSUE THREAD

**Issue by Tudyx** [LaurentMazare/tch-rs#564]
Hello, I've been using the `0.9.0` version on Linux, and I got some trouble with doctest. 

Here is a minimalist example (lib.rs) to reproduce the bug

```rust
use tch::Tensor;

///  # Example
///
/// ```
/// use bug_tch_doctest::create_tensor;
/// create_tensor();
/// ```
pub fn create_tensor() {
    let _ = Tensor::new();
}

#[test]
fn classic_unit_test() {
    let _ = Tensor::new();
}
```

If I run only the lib test with `cargo test --lib` everything work fine but if I run all the test or only the doc test with ` cargo test --doc` I got an error. Here is the backtrace:

```sh
running 1 test
test src/lib.rs - create_tensor (line 5) ... FAILED

failures:

---- src/lib.rs - create_tensor (line 5) stdout ----
Test executable failed (exit status: 127).

stderr:
/tmp/rustdoctestHp2Bnj/rust_out: error while loading shared libraries: libtorch_cpu.so: cannot open shared object file: No such file or directory



failures:
    src/lib.rs - create_tensor (line 5)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.13s

error: doctest failed, to rerun pass `--doc`
```

For now the only workaround I find is to disable all doctest for my lib but It make me kind of sad.
Please could you help me on this?

**Comment by LaurentMazare** [comment]
Did you install libtorch manually and set `LIBTORCH` and `LD_LIBRARY_PATH` or are you relying on `torch-sys` automatically downloading the library for you? (if you don't know it's likely to be the latter)
My tentative guess is that for some reason doctests are run by copying some binaries in /tmp and this will only work out properly in the "manual" installation setting so you may want to try this.

**Comment by Tudyx** [comment]
I've relied on `torch-sys` to automatically download the library through *curl*. 

Indeed when I downloaded *libtorch* manually, everything works fine. It should be relating to how *doctest* handles some binaries as you said.

Thank you for your help!

> When I tried to install manually on Linux, I first downloaded the `Pre-cxx11 ABI` which didn't work and then the `cxx11 ABI` which worked fine. If you think this problem may not be related to my case only, maybe we could advise in the *README* to download the `cxx11 ABI` one for Linux.
