### ISSUE TITLE
Issues with version upgrade

### ISSUE THREAD

**Issue by Shinkaiika** [LaurentMazare/tch-rs#565]
Hello,

I tried to upgrade from 0.8.0 to 0.9.0 but I face an issue with 0.9.0. The type of one of the parameters of this [function](https://docs.rs/tch/latest/tch/struct.Tensor.html#method.mean_dim) changed and I cannot figure out what I need to change in my code to get it running again. The following code was working with 0.8.0:

```Rust
let mean = &x_dot.mean_dim(&[0], true, Kind::Float);
```

Could you please tell me how I need to pass the dimension index for version 0.9.0?

Thank you very much.

**Comment by LaurentMazare** [comment]
You can see an example that has been adapted to the new version [here](https://github.com/LaurentMazare/tch-rs/blob/fbe70bb1460ccddb73f04695e05d4758c9728557/src/vision/mobilenet.rs#L79), so in your case I would think:
```rust
let mean = &x_dot.mean_dim(Some([0].as_slice()), true, Kind::Float);
```

**Comment by Shinkaiika** [comment]
Yes, this works.

Thank you very much! Have a nice weekend :)
