### ISSUE TITLE
Project build successfully but cargo run throws error on libtorch.so?

### ISSUE THREAD

**Issue by DataPsycho** [LaurentMazare/tch-rs#566]
Hi,
I just tried to use the rust binding or `libtorch` for testing purposes. Just to make sure I did not do any config mistakes I have run a test with CMake which compiles the project successfully as follows:

```
cd build/
datapsycho@dataops  ~/.../build $ cmake -DCMAKE_PREFIX_PATH=/home/datapsycho/libtorch_cpu ..
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Torch: /home/datapsycho/libtorch_cpu/lib/libtorch.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/datapsycho/libtorch_test/build
datapsycho@dataops  ~/.../build $ cmake --build . --config Release
[ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
[100%] Linking CXX executable example-app
[100%] Built target example-app
datapsycho@dataops  ~/.../build $ ./example-app 
 0.7442  0.7542  0.3373
 0.0093  0.3098  0.4929
[ CPUFloatType{2,3} ]
```
Then I added the environment variable `export LIBTORCH=/home/datapsycho/libtorch_cpu` . Then I create a new project and added tch as a dependency and try to run the example from the read-me file. The program compile successfully but with `cargo run` it is throwing the following error:

```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/torch-ml-pipeline`
target/debug/torch-ml-pipeline: error while loading shared libraries: libtorch_cpu.so: cannot open shared object file: No such file or directory
```

Any suggestion? Is there something wrong with the path name `export LIBTORCH=/home/datapsycho/libtorch_cpu` instead? Or really there should be some file libtorch_cpu which It can not find?

**Comment by LaurentMazare** [comment]
Did you also set `LD_LIBRARY_PATH` as per the readme instructions? This should help the binary find the libtorch library.

**Comment by DataPsycho** [comment]
Hi, That works. Though I already had a LD_LIBRARY_PATH for my base cuda setup `export LD_LIBRARY_PATH=/usr/local/cuda/lib` I guess that creates the problem. Can I keep both path? Or do I need to switch between them manually? Closing the Issue. Thanks for your help.

**Comment by LaurentMazare** [comment]
You probably want to use `:` as a separator between the different paths that you put in this environment variable, similar to what is done for `PATH`.
