### ISSUE TITLE
Changes to jit.rs broke compatibility with ARM64 Linux

### ISSUE THREAD

**Issue by anna-hope** [LaurentMazare/tch-rs#567]
https://github.com/LaurentMazare/tch-rs/commit/eae2b4ab9c4ce3fe6bda24f71fb06c1e68427a18 changed `src/wrappers/jit.rs` in a way that made it incompatible with aarch64 (ARM64 Linux) because, on that platform, [`c_char` is unsigned](https://rust-lang.github.io/libc/aarch64-unknown-linux-gnu/doc/libc/type.c_char.html). 

As a result, attempting to compile the library on that platform causes this error:

```
error[E0277]: a value of type `Vec<u8>` cannot be built from an iterator over elements of type `i8`
#10 88.53    --> src/wrappers/jit.rs:270:44
#10 88.53     |
#10 88.53 270 |                 let v: Vec<libc::c_char> = v.iter().map(|&b| i8::from(b)).collect();
#10 88.53     |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ------- required by a bound introduced by this call
#10 88.53     |                                            |
#10 88.53     |                                            value of type `Vec<u8>` cannot be built from `std::iter::Iterator<Item=i8>`
```

Reverting the change allows the compilation to succeed. 

I can submit a quick PR to revert this and restore portability.

**Comment by LaurentMazare** [comment]
Sorry about this and thanks for reporting, I've just pushed a fix that hopefully should work on both platform and not trigger the clippy lint that caused this code to be change.

**Comment by LaurentMazare** [comment]
Closing this as this is hopefully fixed, feel free to re-open if it's still an issue (I don't have an arm64 computer at hand to try it out).
