### ISSUE TITLE
Any way to test on the cloud but develop locally?

### ISSUE THREAD

**Issue by danjavady** [LaurentMazare/tch-rs#568]
So I don't have enough DevOps experience/knowledge nor AI knowledge to know what I'm doing here. I develop on a Mac, so I can't train things locally. I do deep learning on Google Colab but i've only been able to use python with it. Google colab is nice because it is only $13 a month

So my question is... I want to be able to develop locally but train on the cloud. I generally use scala, python, and rust and intellij offers me a lot of tooling that I lose out on relying on google colab. How can I achieve this? How can I get IntelliJ to train my models on some cloud service without having to rely on some web IDE?

**Comment by LaurentMazare** [comment]
I don't have much experience with this, my guess is that you would want to get ssh access to your colab instance and then you can treat it as a standard linux box. Searching for "colab ssh access" will give you pointers on how some people managed to do this.
(It's also possible to run some rust code in your jupyter kernel via [evcxr](https://github.com/google/evcxr) but I never tried this)

**Comment by LaurentMazare** [comment]
Closing as no update in a while.
