### ISSUE TITLE
Enforce `cargo fmt` using Travis CI

### ISSUE THREAD

**Issue by grtlr** [LaurentMazare/tch-rs#57]
We could use TravisCI to ensure that all commit comply with the formatting rules in `rustfmt.toml`. This is just a matter of adding the following lines to `.travis.yml`:

```
before_script:
  - rustup component add rustfmt

script:
- cargo fmt -- --check
```

However, currently there are also some warnings when running `cargo fmt` (some code is not formatted accordingly and it seems like some nightly features are used).

**Comment by LaurentMazare** [comment]
Sorry I should have come back to this. Yes that sounds like a good idea, I'll have a look at this in the next few days.

**Comment by LaurentMazare** [comment]
This has just been added to the main branch, thanks for suggesting this!
