### ISSUE TITLE
Is it possible to slice a tensor with a step?

### ISSUE THREAD

**Issue by laptou** [LaurentMazare/tch-rs#578]
I understand that advanced indexing is not supported by the `.i()` operator, but is there any work around in `tch` that would allow me to translate the Python expression `a[::2]` (where `a` is a tensor)?

**Comment by LaurentMazare** [comment]
Did you try using the [slice method](https://docs.rs/tch/latest/tch/struct.Tensor.html#method.slice) for this, e.g.:
```rust
a.slice(/*dim=*/0, None, None, 2)
```

**Comment by laptou** [comment]
This is perfect. I don't know why it was so hard for me to find this! Thank you :)
