### ISSUE TITLE
Sparse to dense throws error

### ISSUE THREAD

**Issue by esadler-hbo** [LaurentMazare/tch-rs#579]
I am on version "0.9.0" converting a sparse tensor to dense representation. This is the code that I am running

```rust
let co_occurance = t_sparse.transpose(1, 0).internal_sparse_sparse_matmul(&t_sparse);
println!("{:?}", &co_occurance.size());
let X = co_occurance.to_dense(Kind::Int);
```
This is the error.
```sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("dtype argument is not supported by sparse_to_dense\nException raised from sparse_to_dense at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorConversions.cpp:498
```

Would love some help figuring this out. Happy to provide more of the stack trace. It might be my libtorch is the wrong version?

**Comment by LaurentMazare** [comment]
Calling `co_occurance.to_dense(None)` should be supported if you use the current github tip version. That said note that sparse matrixes are generally not well tested in this crate so don't hesitate to open further issues if you run into more problems (or to re-open this issue).
