### ISSUE TITLE
header file not found

### ISSUE THREAD

**Issue by yIllusionSky** [LaurentMazare/tch-rs#582]
According to the Readme.md settings, I found that a strange error will be reported when compiling (if I use clang).

Solve the problem:
export LIBTORCH_INCLUDE=/home/illusion/libtorch/include  =>  export LIBTORCH_INCLUDE=/home/illusion/libtorch/

**Comment by LaurentMazare** [comment]
Thanks for pointing this out, I've tweaked the readme to reflect this properly (somehow the example `export` was wrong but the text was correct).
