### ISSUE TITLE
Connecting tch-rs examples to published paper models

### ISSUE THREAD

**Issue by rustrust** [LaurentMazare/tch-rs#592]
The vae example features a paper citation, but I am looking at some of the other models including the cifar example and am not always finding paper references. For example, the cifar example appears to be a "fast resnet" in the source but I can't find a paper mentioning that model-- is this resnet50?

**Comment by LaurentMazare** [comment]
It's actually not a resnet 50 but rather a custom very lightweight resnet if I remember correctly - I don't think there is a paper describing it properly but the proper resnet-50 architecture can be found in the vision module [here](https://github.com/LaurentMazare/tch-rs/blob/f277babe5ec6701af766aa819325bf262e401248/src/vision/resnet.rs#L161) - with a link to the paper at the top of the file.
