### ISSUE TITLE
Significant of struct repr

### ISSUE THREAD

**Issue by ehsanmok** [LaurentMazare/tch-rs#6]
Could example the significance of using the following pattern over ffi in your code vs. empty struct despite having the same size and alignment?

```
#[repr(C)]
pub struct MyStruct {
    _private: [u8; 0],
}
```

vs. 

```
#[repr(C)]
pub struct MyStruct;
```

**Comment by LaurentMazare** [comment]
This actually comes from the [ffi documentation](https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs). Specifically for the private field, this bit is interesting:

> By including a private field and no constructor, we create an opaque type that we can't instantiate outside of this module. (A struct with no field could be instantiated by anyone.)

**Comment by ehsanmok** [comment]
I see! Thank you. It makes sense. That part must have been added somewhat recently.
