### ISSUE TITLE
Error: Internal torch error: Legacy model format is not supported on mobile while loading efficientnet-* weights

### ISSUE THREAD

**Issue by ghost** [LaurentMazare/tch-rs#603]
Command `cargo run --example pretrained-models -- efficientnet-b1.ot img.png`

Error:
```text
Error: Internal torch error: Legacy model format is not supported on mobile.
Exception raised from deserialize at ../torch/csrc/jit/serialization/import.cpp:276 (most recent call first):
...
```

Similar issue:
* #469

Using:
tch-rs ver commit c0bb7e7325d943dc46e964a5ece7f19505ec7c69

sha256sum:
281d75bb97dab428c003f7ba69a60ca8a04f40e50d40287b7001338ca5dafa8c  efficientnet-b0.ot
1ac0a803455f81aedef8a631b802e4f55a3e629b45eeb5ba48ea7fab94938fff  efficientnet-b1.ot
daf3e07e1e2facbe681229a94a4906bcefd314a4d60739abbfbc7d840613e186  efficientnet-b2.ot
30909974ca657527fd352d5478b63404e15b893f4f5dfc73481bef3600f29f5b  efficientnet-b3.ot
5b1b51e0213139b5c9fd34ce9e5c30a403b802106e005e5a823c5086d76d49d6  efficientnet-b4.ot

**Comment by LaurentMazare** [comment]
This should be fixed now, I've also used this opportunity to switch these models to use the safetensors format which should be stable over time (whereas the `.ot` format was changing which created the issue), the url for the model weights can be found [here](https://github.com/LaurentMazare/tch-rs/blob/f872dbd3b22870be7a4099fab133b00912cf31a5/examples/pretrained-models/main.rs#L16-L20) and the Python script to generate the safetensors weight files [here](https://github.com/LaurentMazare/tch-rs/blob/f872dbd3b22870be7a4099fab133b00912cf31a5/src/vision/export_model.py#L1).

Feel free to re-open if you run into further issues.
