### ISSUE TITLE
failed to run custom build command for `torch-sys v0.10.0` 

### ISSUE THREAD

**Issue by berbomeister** [LaurentMazare/tch-rs#606]
Caused by:
  process didn't exit successfully: `D:\rust\neural_network\target\debug\build\torch-sys-c996c2fe36bdca56\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TORCH_CUDA_VERSION
  cargo:rerun-if-env-changed=LIBTORCH
  cargo:rustc-link-search=native=D:\rust\neural_network\target\debug\build\torch-sys-de25f5a53a39aac9\out\libtorch\libtorch\lib
  cargo:rerun-if-env-changed=LIBTORCH_INCLUDE
  cargo:rerun-if-env-changed=LIBTORCH_LIB
  cargo:rerun-if-changed=libtch/torch_api.cpp
  cargo:rerun-if-changed=libtch/torch_api.h
  cargo:rerun-if-changed=libtch/torch_api_generated.cpp.h
  cargo:rerun-if-changed=libtch/torch_api_generated.h
  cargo:rerun-if-changed=libtch/stb_image_write.h
  cargo:rerun-if-changed=libtch/stb_image_resize.h
  cargo:rerun-if-changed=libtch/stb_image.h
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CXX_x86_64-pc-windows-msvc
  CXX_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CXX_x86_64_pc_windows_msvc
  CXX_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-pc-windows-msvc
  CXXFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_pc_windows_msvc
  CXXFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "D:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtorch\\libtorch\\include" "-I" "D:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtorch\\libtorch\\include/torch/csrc/api/include" "-FoD:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtch/fake_cuda_dependency.o" "-c" "libtch/fake_cuda_dependency.cpp"
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "D:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtorch\\libtorch\\include" "-I" "D:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtorch\\libtorch\\include/torch/csrc/api/include" "-FoD:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtch/torch_api.o" "-c" "libtch/torch_api.cpp"
  fake_cuda_dependency.cpp
  torch_api.cpp
  libtch/torch_api.cpp(1): fatal error C1083: Cannot open include file: 'torch/csrc/autograd/engine.h': No such file or directory
  exit code: 0
  exit code: 2

  --- stderr

  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "D:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtorch\\libtorch\\include" "-I" "D:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtorch\\libtorch\\include/torch/csrc/api/include" "-FoD:\\rust\\neural_network\\target\\debug\\build\\torch-sys-de25f5a53a39aac9\\out\\libtch/torch_api.o" "-c" "libtch/torch_api.cpp" with args "cl.exe" did 
not execute successfully (status code exit code: 2).

**Comment by liutingqin** [comment]
Hello, I would like to ask if this problem is solved now, I also encountered the same problem in the current compilation.Thank you.

**Comment by berbomeister** [comment]
Hi, i managed to fix this issue. Turns out i have to manually download Nvidia cuda from the nvidia website, which fixes this problem, but now i have a different problem when i try to run of the basic examples in github i get this error 
```error: process didn't exit successfully: `target\debug\nnetwork.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)```

**Comment by berbomeister** [comment]
It was an issue with enviroment variables.  if you've set them, try to restart your terminal/ editor.
