### ISSUE TITLE
Consider replacing curl with something like ureq

### ISSUE THREAD

**Issue by LeonKowarschickKenbun** [LaurentMazare/tch-rs#612]
Building tch-rs is (as expected) one of the biggest contributors to compilation time. However, I noticed that the execution of the torch-sys buildscript starts surprisingly late in the compilation graph (-> `cargo build --timings`), seemingly due to the curl crate and its build-script actually taking a good few seconds to build, and moving tch quite late into compilation.
By replacing curl with a smaller dependency such as [ureq](https://github.com/algesten/ureq), I was able to improve clean build time by about 10 seconds. (Through very unscientific testing, of course, but still)

It may be worth considering such a switch. I'd be happy to contribute a PR if you think this is viable!

**Comment by LaurentMazare** [comment]
Closing this now that the change to ureq has been merged.
