### ISSUE TITLE
Tensor::device() does not respect Tensor::to_device(...)

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#62]
I ran into this issue when I'm working with multi-GPU training. Surprisingly, this test failed unexpectedly. The `device()` returns `Cuda(1)` after `to_device(Cuda(0))`. Suppose it an off-by-1 bug?

```rust
use tch::{Tensor, Device};

#[test]
fn test_device() {
    let x = Tensor::from(1).to_device(Device::Cuda(0));
    assert_eq!(x.device(), Device::Cuda(0)); // actually returns Device::Cuda(1)
}
```

**Comment by LaurentMazare** [comment]
Thanks for catching this, I just pushed a fix for it (and will add some test although it won't run on CI as there are no gpus there).

**Comment by jerry73204** [comment]
Many thanks.
