### ISSUE TITLE
Error: Internal torch error: open file failed because of errno 2 on fopen: No such file or directory, file path: .ot

### ISSUE THREAD

**Issue by Ldixuan** [LaurentMazare/tch-rs#622]
I am trying to test this example: "cargo run --example pretrained-models -- resnet18.ot tiger.jpg", but i get this error

**Error: Internal torch error: open file failed because of errno 2 on fopen: No such file or directory, file path: .ot**

I made sure that the files 'resnet18.ot' and 'tiger.jpg' are in the root path of my project.

Am I doing something wrong?

**Comment by LaurentMazare** [comment]
Just tried it out and it worked fine, as the error is "file path: .ot" rather than "file path: resnet18.ot" maybe the command was typed improperly?

**Comment by LaurentMazare** [comment]
Closing this for now, feel free to re-open if further issues.
