### ISSUE TITLE
Request a min/max method accepting a scalar type

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#63]
The current `max1(&self, other: &Tensor)` requires a Tensor argument. It leads to some inconvenience on scalar types. It gets worse if the input tensor varies in devices. To make sure max runs without errors, I have to write:

```rust
let max_val = Tensor::from(6_f32).to_device(xs.device());
xs.max1(&max_val)
``` 

I rather expect a method allowing arbitrary scalar like `maxN<S: Into<Scalar>>(&self, other: S)`. In fact, I discovered #62 issue when I'm trying to implement this feature.

**Comment by LaurentMazare** [comment]
Indeed this doesn't seem very convenient. Maybe using `clamp_max` would make things a bit easier if it works for your use case ?

**Comment by jerry73204** [comment]
Thanks. I really missed it.

**Comment by LaurentMazare** [comment]
Closing the issue now, feel free to re-open if you think it's worth making some additional changes.
