### ISSUE TITLE
How to load a DynamicImage

### ISSUE THREAD

**Issue by oovm** [LaurentMazare/tch-rs#634]
I am trying to load a [DynamicImage](https://creative-coding-the-hard-way.github.io/Agents/image/enum.DynamicImage.html).

Here is my attempt:

```rust
        // to tensor
        let rgb = image.to_rgb32f();
        let in_tensor = Tensor::f_of_data_size(rgb.as_bytes(), &[1, 3, rgb.height() as i64, rgb.width() as i64], Kind::Float)?;
        // back image
        out_tensor.f_copy_data(&mut out, out_tensor.numel())?;
        let rgb = match Rgb32FImage::from_raw(rgb .width(), rgb .height(), out) {
            Some(s) => { s }
            None => { panic!("Failed to convert to rgb image"); }
        };
```

![image](https://user-images.githubusercontent.com/17541209/223117312-148c0539-248d-4f62-8504-3fe959909f0a.png)

The three channels of the result picture seem to be separated, how should it be solved?

**Comment by mdrokz** [comment]
> I am trying to load a [DynamicImage](https://creative-coding-the-hard-way.github.io/Agents/image/enum.DynamicImage.html).
> 
> Here is my attempt:
> 
> ```rust
>         // to tensor
>         let rgb = image.to_rgb32f();
>         let in_tensor = Tensor::f_of_data_size(rgb.as_bytes(), &[1, 3, rgb.height() as i64, rgb.width() as i64], Kind::Float)?;
>         // back image
>         out_tensor.f_copy_data(&mut out, out_tensor.numel())?;
>         let rgb = match Rgb32FImage::from_raw(rgb .width(), rgb .height(), out) {
>             Some(s) => { s }
>             None => { panic!("Failed to convert to rgb image"); }
>         };
> ```
> 
> ![image](https://user-images.githubusercontent.com/17541209/223117312-148c0539-248d-4f62-8504-3fe959909f0a.png)
> 
> The three channels of the result picture seem to be separated, how should it be solved?

you can also use https://docs.rs/cv-convert/latest/cv_convert/#image---tch this library to automatically load image into an tensor

**Comment by LaurentMazare** [comment]
Closing now that #635 has been merged.
