### ISSUE TITLE
Is there any way to compute mel spectogram ?

### ISSUE THREAD

**Issue by mdrokz** [LaurentMazare/tch-rs#637]
Hi im working on a project that requires computation of mel spectogram of wav files, Is there any way to do this in tch-rs like how you can do it with pythons `torchaudio` library

**Comment by LaurentMazare** [comment]
There is no support for `torchaudio` baked in directly in `tch-rs` (neither for torch-distributions). The idea would be to have additional crates provide this but I'm not sure anything like this already exists (if it does or if you build one, please point it out so that we can link to it from the readme).

**Comment by mdrokz** [comment]
> There is no support for `torchaudio` baked in directly in `tch-rs` (neither for torch-distributions). The idea would be to have additional crates provide this but I'm not sure anything like this already exists (if it does or if you build one, please point it out so that we can link to it from the readme).

im working on a crate to compute mel spectogram using `tch-rs` when its done i will provide it here and is there any way to index a tensor like this in rust ?

```python
f_pts[1:] - f_pts[:-1]
down_slopes = slopes[:, :-2]
```

**Comment by LaurentMazare** [comment]
Maybe you want use `slice` along the lines of:
```rust
f_pts.slice(0, 1, None, 1) - f_pts.slice(0, None, -1, 1)
```
The parameters are: `slice(dim, start, stop, step)`.

**Comment by mdrokz** [comment]
> Maybe you want use `slice` along the lines of:
> 
> ```rust
> f_pts.slice(0, 1, None, 1) - f_pts.slice(0, None, -1, 1)
> ```
> 
> The parameters are: `slice(dim, start, stop, step)`.

yeah that works thank you

**Comment by LaurentMazare** [comment]
Closing this for now, feel free to re-open if further issues.
