### ISSUE TITLE
No zero grad for min gpt

### ISSUE THREAD

**Issue by Gadersd** [LaurentMazare/tch-rs#638]
I noticed that the min gpt example is does not have any call to zero_grad(). This leads to the gradients accumulating with each iteration instead of being computed fresh each time.

**Comment by Gadersd** [comment]
Just made a pull request.

**Comment by LaurentMazare** [comment]
Sounds a bit strange, is it something that you actually noticed experimentally? The intent of the `backward_step...` methods is to perform the full step (gradient zeroing, backward pass, weights update) e.g. in the case of the min gpt example this should happen [here](https://github.com/LaurentMazare/tch-rs/blob/main/src/nn/optimizer.rs#L263).

**Comment by Gadersd** [comment]
Oh, does tch's backward functions do the zeroing automatically? PyTorch itself accumulates the gradients with each pass and requires manual zeroing.
