### ISSUE TITLE
Tensor::rand_like fails

### ISSUE THREAD

**Issue by tmvkrpxl0** [LaurentMazare/tch-rs#652]
I'm beginner trying this out, and this code fails to run for very complex reasons.
```rs
fn main() {
    let tensor = Tensor::from([1, 2, 3, 4].as_ref());
    let random = tensor.rand_like();
}
```
Log:
https://hastebin.com/share/awiwanomah.swift (why does it have .swift?)
I've installed torchlib 2.0 manually, would that be the cause?

**Comment by tmvkrpxl0** [comment]
ones_like() works, so I doubt there's issue with specifying lib path

**Comment by LaurentMazare** [comment]
My guess is that the relevant part in your error log is:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("\"check_uniform_bounds\" not implemented for 'Int'
```
Maybe you should use float rather than int in `tensor`, e.g. the following.
```rust
fn main() {
    let tensor = Tensor::from([1.0, 2.0, 3.0, 4.0].as_ref());
    let random = tensor.rand_like();
}
```

**Comment by tmvkrpxl0** [comment]
as a side note, I was actually using downloaded torchlib by build script instead of what I manually downloaded

**Comment by tmvkrpxl0** [comment]
Yes, using Double instead worked

**Comment by tmvkrpxl0** [comment]
> as a side note, I was actually using downloaded torchlib by build script instead of what I manually downloaded, the path specification went wrong somewhere.

So I fixed that and rand_like with i32 is still not working

**Comment by LaurentMazare** [comment]
I'm not sure it's expected to work with i32, these `_like` functions return a tensor with the same shape and element type as the original tensor and using a normal distribution with an integer type doesn't make much sense. I guess your best bet there is to convert to the double/float kind to start with and only then apply `rand_like`.

**Comment by tmvkrpxl0** [comment]
I see
