### ISSUE TITLE
Is it possible to run some of the TTS silero-models?

### ISSUE THREAD

**Issue by ModPhoenix** [LaurentMazare/tch-rs#655]
I am a noob just trying to understand how to run some of TTS silero-models on tch-rs here is a list https://github.com/snakers4/silero-models/blob/master/models.yml#L318

**Comment by LaurentMazare** [comment]
I don't really know about these models, usually the easiest way to run inference on an existing PyTorch model is by saving the PyTorch model to a TorchScript from Python and importing it from the Rust side, you can get an example of this [here](https://github.com/LaurentMazare/tch-rs/tree/main/examples/jit).
Another alternative is to re-implement the whole model in `tch-rs`, there are lots of examples of this in the `examples` directory but this is usually a bit more involved.
