### ISSUE TITLE
Tensor's copy method duplicating weights issue

### ISSUE THREAD

**Issue by HyeokSuLee** [LaurentMazare/tch-rs#657]
I'm using copy grad and copy vars a lot for multithread learning. 
Nothing special, just copy vars(`tensor`) or weights(`tensor`) form other var's.
But here is the issue like below. Duplicating same name paths with number added. 

```{"enc/btnorm1.weight__78": Tensor[[101], Float], "out_proj.bias": Tensor[[495], Float], " fc2.bias__67": Tensor[[495], Float], "out_proj.weight__73": Tensor[[495, 495], Float], "ln2.weight__76": Tensor[[495], Float], "enc/btnorm1.bias": Tensor[[101], Float], "v_proj/weight__92": Tensor[[495, 495], Float], "enc/btnorm2.running_mean__84": Tensor[[101], Float], " fc1.bias__107": Tensor[[1980], Float], " fc2.bias": Tensor[[495], Float], "val.weight": Tensor[[1, 49995], Float], "enc/btnorm1.bias__79": Tensor[[101], Float], "q_proj/weight__90": Tensor[[495, 495], Float], "enc/btnorm1.running_mean": Tensor[[101], Float], "enc/btnorm2.bias": Tensor[[101], Float], "k_proj/weight__91": Tensor[[495, 495], Float], "v_proj/weight": Tensor[[495, 495], Float], " fc2.weight__110": Tensor[[495, 1980], Float], "ln1.bias__96": Tensor[[495], Float], "ln2.bias__77": Tensor[[495], Float], " fc1.bias__44": Tensor[[1980], Float], "k_proj/weight": Tensor[[495, 495], Float], "ln2.weight__55": Tensor[[495], Float], "enc/btnorm1.running_var__102": Tensor[[101], Float], "enc/btnorm2.running_var__64": Tensor[[101], Float], " fc2.weight__89": Tensor[[495, 1980], Float], " fc1.weight__66": Tensor[[1980, 495], Float], "enc/btnorm1.weight__36": Tensor[[101], Float], "q_proj/weight__27": Tensor[[495, 495], Float], "ln1.bias__54": Tensor[[495], Float], "out_proj.weight": Tensor[[495, 495], Float], "ln1.weight__53": Tensor[[495], Float], ...```

**Comment by LaurentMazare** [comment]
Not sure which function you've been using here but `VarStore::var_copy` should indeed create a fresh new variable and use `{name}__{id}` as a way to disambiguate names ([docs](https://docs.rs/tch/latest/tch/nn/struct.Path.html#method.var_copy)).
If you want to copy from a tensor to an existing variable, you should probably either call `VarStore::get` and then `no_grad(|| var.copy_(src))`, or use the `or_var_copy` function in the entry api (the latter would create the variable if it doesn't exist yet), e.g.:
```rust
let _var = vs.entry("myvar").or_var_copy(&src);
```

**Comment by LaurentMazare** [comment]
Closing this now, hopefully this explained the issue feel free to reopen otherwise.
