### ISSUE TITLE
Dump a model defined as FuncT

### ISSUE THREAD

**Issue by apepkuss** [LaurentMazare/tch-rs#659]
Is it possible to dump a model defined as `FuncT`? or convert it to `TrainableCModule`? Thanks!

**Comment by LaurentMazare** [comment]
There is nothing to do this at the moment I'm afraid, mostly because afaik there is no way to convert a graph to a jit module in the libtorch C++ api. It's possible though to serialize the weights without the architecture by saving the `VarStore` used to create the model.

**Comment by apepkuss** [comment]
@LaurentMazare Thanks for your explanation. 

Actually, I'm working on an experimental project, in which use Python to define a NN model and dump it to a `*.pt` file, and then load the model file with `tch` to do the training task. When I experimented the workflow, I found that some models, like `vae`, return more than one tensors from their `forward` method while training. It seems that the relevant `forward` APIs defined in `CModule`, `TrainableCModule`, `FuncT` and etc. do not support returning multiple tensors. Is there a plan for the case? Please correct me if I were wrong. Thanks a lot!

**Comment by LaurentMazare** [comment]
Did you try using the `forward_is` method on `CModule`? This should be able to return an arbitrary `IValue` so a pair of tensors for example. You can see it in use in [this test](https://github.com/LaurentMazare/tch-rs/blob/b3acdbbabd63004647f1f6ed74c20380fe12af00/tests/jit_tests.rs#L39) for example.

**Comment by apepkuss** [comment]
Really thank you! I'll check the test code!

**Comment by LaurentMazare** [comment]
Closing this for now, hopefully the previous answer was helpful.
