### ISSUE TITLE
how to implement Concat<tch::Tensor>?

### ISSUE THREAD

**Issue by 3togo** [LaurentMazare/tch-rs#670]
I got the following error. 
How to fix it?

```
177 |     let a = [t1, t2].concat();
    |                                                  ^^^^^^ the trait `Clone` is not implemented for `tch::Tensor`
    |
    = help: the following other types implement trait `Concat<Item>`:
              <[S] as Concat<str>>
              <[V] as Concat<T>>
    = note: required for `[Vec<tch::Tensor>]` to implement `Concat<tch::Tensor>`
```

**Comment by LaurentMazare** [comment]
Not sure what exactly you want to do here but I would guess that you're looking for something like `Tensor::cat(&[t1, t2], dim_index)`?
You can find plenty of examples using this in the `examples/` directory, e.g. in the [stable diffusion model](https://github.com/LaurentMazare/tch-rs/blob/087a793d85dc7137c2fd01b76c3180c31212d8ac/examples/stable-diffusion/main.rs#L1898).

**Comment by LaurentMazare** [comment]
Closing this as hopefully the previous answer helped.
