### ISSUE TITLE
is it possible now to run yolov5 with tch-rs?

### ISSUE THREAD

**Issue by igor-yusupov** [LaurentMazare/tch-rs#673]
is it possible now to run yolov5 with tch-rs?

**Comment by LaurentMazare** [comment]
I don't know much about yolov5 (we only have yolo-v3 as in the `examples` dir) but if the model is defined in PyTorch, the simplest is probably to export it as a torch script and then it should be easy to run it with `tch`. You can find a tutorial documenting this process [here](https://github.com/LaurentMazare/tch-rs/tree/main/examples/jit).

**Comment by igor-yusupov** [comment]
@LaurentMazare I don't think that jit trace model will work correctly, but I'll try.
info about yolov5: https://github.com/ultralytics/yolov5
they also have export.py script to generate ONNX, TorchScript or TensorRT file.
