### ISSUE TITLE
tch is slower

### ISSUE THREAD

**Issue by igor-yusupov** [LaurentMazare/tch-rs#674]
is it OK that inference using rust with tch is slower than using python with pytorch?

**Comment by zrthxn** [comment]
I think that would defeat the whole purpose of going through the trouble of implementing all this in Rust.
You should provide some more details about your model, setup and system.

**Comment by igor-yusupov** [comment]
@zrthxn I just convert yolov5 model to torchscript and run inference with tch. And the speed of inference with Rust is slower. I'll attach the code later.

**Comment by zrthxn** [comment]
I think it might be because running a model which was exported to torchscript uses JIT and therefore its not as fast as a compiled model. Just a guess though.

**Comment by igor-yusupov** [comment]
@zrthxn it seems you are right. I just run inference JIT model with python and speed is the same in Rust. Thank you! But anyway I expected the speed on the Rust to be higher)

**Comment by zrthxn** [comment]
@igor-yusupov How exactly did you run inference JIT model? I'm trying to use `model.f_set_eval().unwrap();` but it doesn't seem to work.

**Comment by igor-yusupov** [comment]
@zrthxn `model.forward_ts(&[image]).unwrap()`

**Comment by zrthxn** [comment]
To test this I had created a super simple 2 layer model in PyTorch and then exported its TorchScript. When I run that in Python, I get faster performance than Rust somehow, even after using `model.forward_ts(&[image]).unwrap()`

This is my Python runner code.
```python
_S = time()
for _ in range(1000):
    model_int8(torch.randn(1, 5, 10, 12))
_E = time()
print("Time for 1000 iterations", (_E - _S)*1000, "ms")
```
```
Time for 1000 iterations 273.74887466430664 ms
```

This is my Rust runner code. Here `load` is a function that reads the model from a file.
```rust
#[test]
pub fn test_load() {
    let mut model = load("SanityModel.script.pt", 
            Device::Mps, 
            Kind::Float)
        .unwrap();

    model.set_eval();
    let start = Instant::now();
    for _ in 0..1000 {
        model.forward_ts(&[
            &tch::Tensor::rand(&[1, 5, 10, 12], 
            (Kind::Float, Device::Mps))
        ]);
    }
    let duration: Duration = start.elapsed();
    println!("Time for 1000 iterations {:?}", duration);
}
```

```
Time for 1000 iterations 393.7835ms
```

**Comment by zrthxn** [comment]
Okay apparently this was because I was trying to run on MPS. Trying the same thing on CPU gives me
```
Time for 1000 iterations 213.642375ms
```
