### ISSUE TITLE
Support for AMD GPUs?

### ISSUE THREAD

**Issue by brennschlus** [LaurentMazare/tch-rs#688]
I downloaded the ROCm version of PyTorch C++ from the official website and set the necessary environment variables. However, when I try to compile my code, I get an error message stating that there is an undefined reference to c10::detail::torchInternalAssertFail() in the function c10::Device::validate(). Can anyone please help me resolve this issue?

**Comment by LaurentMazare** [comment]
It's a bit hard to tell without more details. Googling a bit it may not be ROCm related but rather a problem of cxx11 abi mismatch so worth trying setting/unsetting `LIBTORCH_CXX11` if you haven't done so already.

**Comment by LaurentMazare** [comment]
Closing this as no further update, hopefully this was a cxx11 abi issue.
