### ISSUE TITLE
ONNX and TensorRT

### ISSUE THREAD

**Issue by igor-yusupov** [LaurentMazare/tch-rs#695]
Do you plan to add the ability to read the model weights formats ONNX and TensorRT? Or maybe there is already such a possibility?

**Comment by LaurentMazare** [comment]
Exporting models to onnx is supported in libtorch so this would probably be easy to add but I don't think there is a good way to do the opposite: running/importing onnx models from the c++ side, see this [pytorch issue](https://github.com/pytorch/pytorch/issues/21683). I don't think there is a current plan to do this. If the goal is just to retrieve the weight and not the architecture, I would suggest writing some one off python script using the `onnx` python package and writing some `safetensors` file. If the goal is to generate a full jit/torch-script model, there seems to be various python libraries doing this but I'm not sure how good they actually are.

**Comment by igor-yusupov** [comment]
@LaurentMazare models with torchscript are slower than the onnx version, so I would like to be able to run inference models with the onnx format. But I hear you, thank you.
