### ISSUE TITLE
Incremental compilation of the C code

### ISSUE THREAD

**Issue by LaurentMazare** [LaurentMazare/tch-rs#7]
It seems that the C wrappers get recompiled on pretty much any change. Using ccache makes it a bit better but we should try to fix this as it makes the development loop a bit slow.
A possibility could be to have a subcrate `torch-sys` which contains the C wrappers so that the C code only gets recompiled when parts of this new crate are modified.

**Comment by ehsanmok** [comment]
I think [`sccache` is the way to go](https://doc.rust-lang.org/cargo/guide/build-cache.html) and can be invoked in the future CI.

**Comment by LaurentMazare** [comment]
Nice, thanks for pointing this out. This will certainly help on the rust side of things too - I also went ahead and split some bits in a second `torch-sys` crate so slow compilation of the C++ code is not an issue anymore.
