### ISSUE TITLE
Cuda not available on linux (paperspace gpu cloud)

### ISSUE THREAD

**Issue by tsuberim** [LaurentMazare/tch-rs#702]
I'm trying to use tch on a paperspace gpu cloud machine, getting cuda not availble even tough I can access it using python just fine. What could be the issue?

GPU: `Quadro M4000`

Environment information:
`$ nvcc --version`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

`$ rustup show` 
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/paperspace/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.71.0-nightly (2a8221dbd 2023-05-11)
```

`$ lsb_release -a`
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

**Comment by LaurentMazare** [comment]
Did you install a cuda enabled version of libtorch? If not by default this will use the CPU version, you can find details about how to install / point tch at your libtorch install in the main readme.

**Comment by LaurentMazare** [comment]
Closing this for now, hopefully installing the cuda enabled version sorted it out, feel free to re-open if there are further issues.
