### ISSUE TITLE
Question: Path / "text"

### ISSUE THREAD

**Issue by bokenator** [LaurentMazare/tch-rs#708]
What does it mean to delimit the variable store path like the following code snippet from AlexNet? From reading the source code it seems to be creating a new Path with a new string, but referencing the same variable store. Does this have any ramification when I am loading the the weights from a pre-trained pth file?

```
fn features(p: nn::Path) -> impl ModuleT {
    nn::seq_t()
        .add(conv2d(&p / "0", 3, 64, 11, 2, 4))
        .add_fn(|xs| max_pool2d(xs.relu(), 3, 2))
        .add(conv2d(&p / "3", 64, 192, 5, 1, 2))
        .add_fn(|xs| max_pool2d(xs.relu(), 3, 2))
        .add(conv2d(&p / "6", 192, 384, 3, 1, 1))
        .add_fn(|xs| xs.relu())
        .add(conv2d(&p / "8", 384, 256, 3, 1, 1))
        .add_fn(|xs| xs.relu())
        .add(conv2d(&p / "10", 256, 256, 3, 1, 1))
        .add_fn(|xs| max_pool2d(xs.relu(), 3, 2))
}
```

Thanks!

**Comment by LaurentMazare** [comment]
This creates 'paths' for the weight names, e.g. if the `features` function is called on the path `"features"`, the weights would be retrieved using full name `features.0.weight`, `features.0.bias`, `features.3.weight`, `features.3.bias` etc (the "weight" and "bias" bits come from the [conv module](https://github.com/LaurentMazare/tch-rs/blob/main/src/nn/conv.rs#L125)).

**Comment by bokenator** [comment]
Will the name of the path affect how the weights are loaded from pth files?

**Comment by LaurentMazare** [comment]
It would expect the tensors within the weight files to be named according to the full path.
Also note that the PyTorch `.pth` format is not supported as it relies on pickle which is hard to replicate outside of python (some files may work though). The supported format are `.ot` and `.safetensors` - the latter being recommended for the interop with Python.

**Comment by bokenator** [comment]
thanks!
