### ISSUE TITLE
Runtime Search Path Unused

### ISSUE THREAD

**Issue by Gadersd** [LaurentMazare/tch-rs#727]
When I try to run any example after building tch I get the following Error: No such file or directory (os error 2).
I tried running with <code>CARGO_LOG=debug cargo run --example min-gpt</code> and cargo outputted the following:
Not including path /home/hermes/libtorch/lib in runtime library search path because it is outside target root /home/hermes/projects/tch-rs/target/debug

**Comment by Gadersd** [comment]
I tried it on my mac and got the same error as in linux. The previous versions of tch worked for me, but now the run fails on all my systems.

**Comment by LaurentMazare** [comment]
Is it possible that the cargo bit is a red herring and the file it's not finding is actually data/input.txt? (might help to put the full error if that's not the case)

**Comment by Gadersd** [comment]
Yes, the missing data/input.txt was the issue.
