### ISSUE TITLE
how to concat Vec<Vec<Tensor>>?

### ISSUE THREAD

**Issue by 3togo** [LaurentMazare/tch-rs#736]
The following script failed with error msg:

```
the trait bound `tch::Tensor: Clone` is not satisfied
the following other types implement trait `Concat<Item>`:
  <[S] as Concat<str>>
  <[V] as Concat<T>>
required for `[Vec<tch::Tensor>]` to implement `Concat<tch::Tensor>`


```
Any help on how to fix it?

```
use tch::Tensor;

fn main() {
    let a = vec![vec![1, 2, 3, 4], vec![10, 20, 30, 40]];
    let mut b: Vec<i32> = Vec::new();
    for v in &a {
        b.extend(v);
    }
    let c = a.as_slice().concat();
    println!("b={:#?}", b);
    println!("c={:#?}", c);
    println!("Hello, world!");

    let t0 = Tensor::from_slice(&[1, 2, 3, 4]);
    let t1 = Tensor::from_slice(&[10, 20, 30, 40]);
    let v0 = vec![t0.copy(), t1.copy()];
    let v1 = vec![t1.copy(), t0.copy()];
    let a = vec![v0, v1];
    let mut b: Vec<_> = Vec::new();
    for v in a {
        b.extend(v);
    }
    let c = a.as_slice().concat();
    println!("b={:#?}", b);
    println!("c={:#?}", c);
}
```

**Comment by LaurentMazare** [comment]
Not sure what you're trying to do exactly here but if you want to concat some `Vec<Tensor>` (and not `Vec<Vec<Tensor>>`) you could do `Tensor::cat(&vec, dim_index)` where `dim_index` is the index of the axis along which the concatenation is performed, and can be positive or negative, e.g. -1 for the last dimension. You can find various examples of this in the example and test directories, e.g. [here](https://github.com/LaurentMazare/tch-rs/blob/8182f25389d8f3641d775c2ce461d3856169a467/tests/tensor_tests.rs#L118).
You could then call `Tensor::cat` on each subslice and make a final call to `Tensor::cat` if your goal is to process a `Vec<Vec<Tensor>>`.

**Comment by 3togo** [comment]
let a: Vec<Vec<i32>> = vec![vec![1, 2, 3, 4], vec![10, 20, 30, 40]];
let v = Tensor::cat(&a, 0);  
 
 will cause the following error.
 
"message": "error: the trait bound `Vec<{integer}>: Borrow<tch::Tensor>` is not satisfied\nlabel: required by a bound introduced by this call",
error: the trait bound `Vec<{integer}>: Borrow<tch::Tensor>` is not satisfied
label: the trait `Borrow<tch::Tensor>` is not implemented for `Vec<{integer}>`
the trait bound `Vec<{integer}>: Borrow<tch::Tensor>` is not satisfied
the trait `Borrow<[T]>` is implemented for `Vec<T, A>`

**Comment by LaurentMazare** [comment]
Closing as this hopefully answered the question.
