### ISSUE TITLE
Failing to cargo run

### ISSUE THREAD

**Issue by arthur19q3** [LaurentMazare/tch-rs#740]
i downloaded the c++ api from  this link. 
https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcu118.zip

then i unzipped it to  $HOME & set the LIBTORCH enviroment variable in fish shell:

`set -Ux LIBTORCH "$HOME/libtorch"`
`set -Ux LIBTORCH_INCLUDE "$HOME/libtorch"`
`set -Ux LIBTORCH_LIB "$HOME/libtorch"`

i can perfectly build tch-rs when i clone it and build from the tch-rs folder or from my project folder, but when i tried `cargo run` i got this

```
cargo run
   Compiling torch-sys v0.13.0
   Compiling tch v0.13.0
   Compiling as-deeplearning v0.1.0 (/home/arthur/Desktop/Rust_Projects/AS-DeepLearning)
    Finished dev [unoptimized + debuginfo] target(s) in 23.23s
     Running `target/debug/as-deeplearning`
target/debug/as-deeplearning: error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory

```

**Comment by LaurentMazare** [comment]
My guess is that you have to set the `LD_LIBRARY_PATH` environment variable, see the readme. Hopefully this should not be necessary anymore when using the GitHub tip.

**Comment by arthur19q3** [comment]
> My guess is that you have to set the `LD_LIBRARY_PATH` environment variable, see the readme. Hopefully this should not be necessary anymore when using the GitHub tip.

okk, i'll look into it.
my LD_LIBRARY_PATH is pointing to /usr/lib it seems, should i install my libtorch in /usr/lib/libtotch instead?

**Comment by arthur19q3** [comment]
tried  that but no luck:
set -Ux LD_LIBRARY_PATH "/usr/lib/"
set -Ux LIBTORCH "/usr/lib/libtorch"
set -Ux LIBTORCH_INCLUDE "/usr/lib/libtorch"
set -Ux LIBTORCH_LIB "/usr/lib/libtorch"

still having the same error
`target/debug/as-deeplearning: error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory`

**Comment by LaurentMazare** [comment]
Shouldn't it be `/use/lib/libtorch/lib`? You want the directory that
contains the `.so` files.

**Comment by LaurentMazare** [comment]
Shouldn't it be `/use/lib/libtorch/lib`? You want the directory that contains the `.so` files.

**Comment by arthur19q3** [comment]
ahh i see. that could be the problem.

**Comment by arthur19q3** [comment]
hello again

unfortunately i tried setting :

```
set -Ux LD_LIBRARY_PATH "/usr/lib/libtorch/lib"
set -Ux LIBTORCH "/usr/lib/libtorch"
set -Ux LIBTORCH_INCLUDE "/usr/lib/libtorch"
set -Ux LIBTORCH_LIB "/usr/lib/libtorch"
```

and 

```
set -Ux LD_LIBRARY_PATH "/usr/lib/libtorch/lib"
set -Ux LIBTORCH "/usr/lib/libtorch/lib"
set -Ux LIBTORCH_INCLUDE "/usr/lib/libtorch/lib"
set -Ux LIBTORCH_LIB "/usr/lib/libtorch/lib"
```

and neither is working for me

**Comment by arthur19q3** [comment]
finnally fixed by adding 
`LIBTORCH=/usr/lib/libtorch;LD_LIBRARY_PATH=/usr/lib/libtorch/lib
`to my Clion compiler configuration's environment variables
