### ISSUE TITLE
Should allow minor/patch versions of PyTorch (2.0.1)

### ISSUE THREAD

**Issue by antimora** [LaurentMazare/tch-rs#742]
I have set LIBTORCH_USE_PYTORCH = "1" and installed the latest Pytorch 2.0.1. However, the torch-sys's build is expecting an exact version of 2.0.0. It's desirable if the installation allowed minor/patch versions of PyTorch.

The error message:

```
error: failed to run custom build command for `torch-sys v0.13.0`

Caused by:
  process didn't exit successfully: `/Users/user/Projects/burn/target/debug/build/torch-sys-2d429dab13d115c0/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=LIBTORCH_USE_PYTORCH
  cargo:rerun-if-env-changed=LIBTORCH_BYPASS_VERSION_CHECK

  --- stderr
  Error: this tch version expects PyTorch 2.0.0, got 2.0.1
```

**Comment by LaurentMazare** [comment]
You can actually bypass the version check by setting the `LIBTORCH_BYPASS_VERSION_CHECK` environment variable. I'm a bit reluctant to assume that minor versions of PyTorch would not break the api as I'm not aware of such a guarantee on the PyTorch side but if you have some pointers mentioning this to be safe, happy to revisit.

**Comment by LaurentMazare** [comment]
Just to mention that I've pushed some small changes so that the error message includes a reference `LIBTORCH_BYPASS_VERSION_CHECK`, this should make it easier to discover. I also extended the check so that it also applies when using `LIBTORCH` (rather than just when using `LIBTORCH_USE_PYTORCH`).

**Comment by rustrust** [comment]
Does tch-rs have a potential dependence on the cuda version (e.g. cuda 11.7) as well?

I tried the mnist example with libtorch 2.0.1+cu118 and it seems to work fine...

To download  libtorch 2.0.0+cu117 I hand-edited the pytorch download url:

https://download.pytorch.org/libtorch/cu117/libtorch-cxx11-abi-shared-with-deps-2.0.0%2Bcu117.zip

Then you can set your paths (don't forget to set both environment variables!):

```
export LD_LIBRARY_PATH=/usr/local/libtorch-2.0.0-cu117:/usr/local/cuda/lib64:
export LIBTORCH=/usr/local/libtorch-2.0.0-cu117
```

**Comment by LaurentMazare** [comment]
@antimora are you happy with using `LIBTORCH_BYPASS_VERSION_CHECK`? If so I would like to close this issue as it may just be a bit confusing.

**Comment by antimora** [comment]
Closing this as we have a working solution using LIBTORCH_BYPASS_VERSION_CHECK.
