### ISSUE TITLE
to_mkldnn() panics if libtorch not built with mkldnn such as on arm

### ISSUE THREAD

**Issue by GaryBoone** [LaurentMazare/tch-rs#743]
[MKL-DNN](https://oneapi-src.github.io/oneDNN/v0/index.html) is an optional Intel-specific library for Pytorch. `tch-rs` has a test [`mkldnn()`](https://github.com/LaurentMazare/tch-rs/blob/main/tests/tensor_tests.rs#L336) that fails in `tests/tensor_tests.rs` if libtorch was not built with `mkldnn` enabled.

    #[test]
    fn mkldnn() {
        let t = Tensor::randn([5, 5, 5], (tch::Kind::Float, Device::Cpu));
        assert!(!t.is_mkldnn());
        assert!(t.to_mkldnn().is_mkldnn());
    }

As might be expected, it appears that `mkldnn` is only valid on Intel chips. Specifically on ARM processors, `to_mkldnn()` fails in the test if the library is not present when `cargo test` is run.

    thread 'mkldnn' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("MKL-DNN build is disabled\nException raised from dense_to_mkldnn at /opt/pytorch/pytorch/aten/src/ATen/native/mkldnn/MKLDNNConversions.cpp:277

To check if libtorch was built against `mkldnn` on Linux:

    $ ldd <path-to-torch-lib>/libtorch.so

If Pytorch is installed in Python, run:

    $ python -c "import torch; print(torch.__config__.show())"

and look for `USE_MKL=`  in the build settings. It will be `ON` or `OFF`.

If Pytorch is installed in Python, `mlkdnn` can be also be tested directly:

[MacBook Pro (Intel)]

    $ python -c 'import torch; a = torch.randn(10); print(a.to_mkldnn().layout)'
    torch._mkldnn

[Jetson and Mac mini (ARM)]

    $ python -c 'import torch; a = torch.randn(10); print(a.to_mkldnn().layout)'
    ... [error]
    RuntimeError: MKL-DNN build is disabled

Is there a way that tch-rs can detect whether `libtorch.so` is compiled with `USE_MKL=ON` before enabling the `mkldnn()` test? If not, should that test be dropped or marked `#ignore` for now?

**Comment by LaurentMazare** [comment]
Thanks for reporting this, there is actually a `tch::utils::has_mkldnn` function that should check for this, I've just merged #744 to only run the test when mkldnn is available. Could you give this a spin?

**Comment by GaryBoone** [comment]
Success!

Closing issue.

Thanks Laurent.
