### ISSUE TITLE
Mutable Indexer 

### ISSUE THREAD

**Issue by AzHicham** [LaurentMazare/tch-rs#753]
Hello, 

I was wondering if there is a way in tch-rs to update partially a tensor (ie a sub tensor). 
My goal here is to translate this python code into rust.
`image[rs : re, cs : ce] = patch` 

Thank you

**Comment by LaurentMazare** [comment]
You can try using the indexer api for this, e.g. to fill with a single value:
```rust
image.i((rs..re, cs..ce)).fill_(v) // fill with a scalar value
image.i((rs..re, cs..ce)).copy_(v) // fill with a tensor
```
However the `.i` indexer does not provide any guarantee that the storage is shared between the source tensor and its results, in some cases (e.g. when the source is strided) it may do some copying and in that case setting the resulting tensor won't affect the `image` original tensor so you will have to give this a try.

**Comment by AzHicham** [comment]
Unfortunately it doesn't work, as you said the Indexer create a new Tensor (not a shallow clone) thus using copy has no effect on the image Tensor
