### ISSUE TITLE
Support automatic precision casting on `VarStore.load(...)`

### ISSUE THREAD

**Issue by guillaume-be** [LaurentMazare/tch-rs#757]
Hello,

The current crate behaviour when loading a set of weights in a `VarStore` is to load the weights in full precision (float32), regardless of the precision of the saved tensors. This differs from the behaviour of Pytorch, where the following is true:
```python
import torch
import tempfile
from pathlib import Path

with tempfile.TemporaryDirectory() as tmpdirname:
    saved_file = Path(tmpdirname) / "pytorch_model.bin"
    
    saved_model = torch.nn.Linear(10,42)
    saved_model.half()
    torch.save(saved_model, saved_file)
    
    reloaded_model = torch.load(saved_file)
    assert reloaded_model.weight.dtype == torch.float16
```

I have looked for a way to load weights in `VarStore` keeping the saved precision, and the workaround I have found was to first cast the varstore to the target precision (e.g., `VarStore.half()`) and then load the half-precision tensors. This requires the user knowing the precision of the model being loaded. With the increasing number of models made available at lower precision (float16, int8 or even int4), I believe this would be a useful mechanism to automate.

I have prepared a proposal for performing automatic casting of the `VarStore` when loading tensors with the different `load_[...]` operators. Since the **tensor** loading keeps precision information, one can lookup the loaded tensor precision and cast the target varstore variable if needed. I am opening a draft PR with the suggested changes, please let me know if you would be open to add this feature and I will mark it as ready for review.

Thank you

**Comment by LaurentMazare** [comment]
Thanks for raising this issue and making the associated PR, the change looks pretty sensible to me as well and its draft implementation looks good so feel free to remove the "draft" part and we can merge it!
