### ISSUE TITLE
Vec<..> from &Tensor

### ISSUE THREAD

**Issue by rustrust** [LaurentMazare/tch-rs#768]
Back in the day, tch-rs had the ability to convert from a Tensor to a Vec, for instance:
```
    let tensor = Tensor::arange_start(0, 6 * 2, opt).view([6, 2]);
    let index: &[_] = &[1, 3, 5];
    let result = tensor.i(index);
    result.print();
    assert_eq!(result.size(), &[3, 2]);
    assert_eq!(Vec::<i64>::from(result), &[2, 3, 6, 7, 10, 11]); // this is the conversion of interest
```

There are some helper functions here which are not part of the tch-rs library but have the same purpose (albeit they take a &Tensor and not a Tensor).

```
https://github.com/LaurentMazare/tch-rs/blob/main/tests/test_utils.rs
```

Would it make sense to add these helper conversion functions to the tch-rs library?

**Comment by LaurentMazare** [comment]
The `From` trait has been replaced with `TryFrom`, see the [changelog](https://github.com/LaurentMazare/tch-rs/blob/main/CHANGELOG.md#v0120---2023-05-10) if you want to check what might have changed compared to old version. You can probably grep the repo for `try_from` to find examples of this being used.

**Comment by rustrust** [comment]
i see, it's a rust langwart nvm
