### ISSUE TITLE
Help setup tch-rs on new repo with local python pytorch

### ISSUE THREAD

**Issue by khangkontum** [LaurentMazare/tch-rs#787]
Hi this is not an issue but I don't know where to ask.
Currently my setup is running perfectly when pulling `tch-rs` to local and run `cargo run --example basics`
```bash
...
[ CPUDoubleType{} ]
1.24
[ CPUDoubleType{} ]
1.24
[ CPUDoubleType{} ]
Grad 1.24
has_mps: false
has_vulkan: false
version_cudnn: 8500
version_cudart: 11070
```

Add this line to `.zshrc` and everything work fine with the `example/basics.rs`
```bash
export LIBTORCH_USE_PYTORCH=1
```

Copy the whole `basics.rs` file into another crate make the below bug
```bash
target/debug/test-tch: error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory
```
Cargo.toml
```toml
[package]
name = "test-tch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.13.0"
```

I just need a way to find the different between the original example and this fresh new crate.

Thank you for any help.

**Comment by LaurentMazare** [comment]
It's likely that the proper rpaths are not passed to the final linking step in your crate. Could you try copying this [build.rs](https://github.com/LaurentMazare/diffusers-rs/blob/main/build.rs) in your crate and see if it helps?
Alternatively you can try setting your `LD_LIBRARY_PATH` to point at the directory with the appropriate shared libarries.

**Comment by khangkontum** [comment]
Hi, thanks for fast response. 

I tried two of your suggestions and none of them fix the issue

1. The first one, I modified the `main.rs` to this:
```rs

use tch::{kind, Tensor};

fn grad_example() {
    let mut x = Tensor::from(2.0).set_requires_grad(true);
    let y = &x * &x + &x + 36;
    println!("{}", y.double_value(&[]));
    x.zero_grad();
    y.backward();
    let mut dy_over_dx = x.grad();
    dy_over_dx.print();
    let t2 = dy_over_dx.clamp_(1.23, 1.24);
    dy_over_dx.print();
    t2.print();
    println!("Grad {}", dy_over_dx.double_value(&[]));
}

fn main() {
    let os = std::env::var("CARGO_CFG_TARGET_OS").expect("Unable to get TARGET_OS");
    match os.as_str() {
        "linux" | "windows" => {
            if let Some(lib_path) = std::env::var_os("DEP_TCH_LIBTORCH_LIB") {
                println!(
                    "cargo:rustc-link-arg=-Wl,-rpath={}",
                    lib_path.to_string_lossy()
                );
            }
            println!("cargo:rustc-link-arg=-Wl,--no-as-needed");
            println!("cargo:rustc-link-arg=-Wl,--copy-dt-needed-entries");
            println!("cargo:rustc-link-arg=-ltorch");
        }
        _ => {}
    }

    println!("Cuda available: {}", tch::Cuda::is_available());
    println!("Cudnn available: {}", tch::Cuda::cudnn_is_available());

    let device = tch::Device::cuda_if_available();
    let t = Tensor::from_slice(&[3, 1, 4, 1, 5]).to(device);
    t.print();
    let t = Tensor::randn([5, 4], kind::FLOAT_CPU);
    t.print();
    (&t + 1.5).print();
    (&t + 2.5).print();
    let mut t = Tensor::from_slice(&[1.1f32, 2.1, 3.1]);
    t += 42;
    t.print();
    println!("{:?} {}", t.size(), t.double_value(&[1]));
    grad_example();
    println!("has_mps: {}", tch::utils::has_mps());
    println!("has_vulkan: {}", tch::utils::has_vulkan());
    println!("version_cudnn: {}", tch::utils::version_cudnn());
    println!("version_cudart: {}", tch::utils::version_cudart());
}
```

2. The second one I export the environment as you suggested:
```
export LIBTORCH_USE_PYTORCH=1
export LD_LIBRARY_PATH="~/.local/lib/python3.10/site-packages/torch"
```

**Comment by LaurentMazare** [comment]
Oh I don't mean to add the code in your executable, but rather add a `build.rs` file at the top of your crate with the content.

**Comment by khangkontum** [comment]
Hi, I brought it to `build.rs` but it still produce the same output, do you have any other build code or other configuration that I need to bring as well

**Comment by LaurentMazare** [comment]
I don't think so, maybe add a line in your Cargo.toml similar to this [one](https://github.com/LaurentMazare/diffusers-rs/blob/f19c33f84599eb7dea3a65e5b0810ea55c4c57c3/Cargo.toml#L6) so as to be sure to use this `build.rs`.
If it doesn't work, I would suggest cloning this diffusers-rs repo and trying to run the examples in there to see if it works fine or not.

**Comment by khangkontum** [comment]
Hi I cloned and run this two example in `diffusers-rs`
```bash
cargo run --example stable-diffusion-img2img --features clap -- --input-image media/in_img2img.jpg
cargo run --example stable-diffusion --features clap -- --prompt "A rusty robot holding a fire torch."
```
produce this output
```bash
Cuda available: false
Cudnn available: false
Error: error opening "data/bpe_simple_vocab_16e6.txt"

Caused by:
    No such file or directory (os error 2)
```

**Comment by LaurentMazare** [comment]
So it works there, it's just missing the data files but accessing the libraries worked fine. So my guess is that somehow you may not have put the `build.rs` at the right place or modified the `Cargo.toml` properly in your crate.

**Comment by khangkontum** [comment]
Recap my current setup:
1. My `tree -I "target/":
```bash
.
├── build.rs
├── Cargo.lock
├── Cargo.toml
└── src
    └── main.rs
```
2. Cargo.toml
```toml
[package]
name = "test-tch"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.13.0"
```
I did try to `cargo clean` every time before `cargo run`

**Comment by khangkontum** [comment]
I pushed my current code to my [repo](https://github.com/khangkontum/test-tch-rs) if you want to take a look

**Comment by LaurentMazare** [comment]
I can indeed replicate the issue, I'll have to investigate a bit more on why the rpath don't work well in this case. In the meantime I got it to work with the following:
```
LD_LIBRARY_PATH=/home/laurent/venvs/pytorch/lib/python3.10/site-packages/torch/lib
```
(obviously you'll have to adapt to the path of your python install)

**Comment by LaurentMazare** [comment]
Ah actually you need an explicit reference to `torch-sys` in your `Cargo.toml` so that things get properly propagated. I.e. the following change made it work for me without needing the `LD_LIBRARY_PATH`.
```
diff --git a/Cargo.toml b/Cargo.toml
index c22358f..abc45b6 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -8,3 +8,4 @@ build = "./build.rs"
 
 [dependencies]
 tch = "0.13.0"
+torch-sys = "0.13.0"
```

**Comment by khangkontum** [comment]
my gosh, thank you so much. Both of your suggests works.
So keypoint here is that I have to:
1. Add [`build.rs`](https://github.com/LaurentMazare/diffusers-rs/blob/main/build.rs)
2. Either add `torch-sys = "0.13.0"` as dependency or export `LD_LIBRARY_PATH`

**Comment by LaurentMazare** [comment]
Yeah sorry it ended up being such a pain, I'll add some details to the readme so as to document this better.
