### ISSUE TITLE
How does Tensor.where_ work?

### ISSUE THREAD

**Issue by vegapit** [LaurentMazare/tch-rs#79]
I can not find an example or a test covering its use

**Comment by LaurentMazare** [comment]
Here is a small test illustrating this. The behavior should be similar to [torch.where](https://pytorch.org/docs/stable/torch.html#torch.where).
```rust
#[test]
fn where_() {
    let t1 = Tensor::of_slice(&[3, 1, 4, 1, 5, 9]);
    let t2 = Tensor::of_slice(&[2, 7, 1, 8, 2, 8]);
    let t = t1.where_(&t1.eq(1), &t2);
    assert_eq!(Vec::<i64>::from(&t), [2, 1, 1, 1, 2, 8]);
}
```

**Comment by vegapit** [comment]
Great, `eq` method was what I was missing

**Comment by LaurentMazare** [comment]
Any boolean tensor can be used for the first argument, so `t1.eq` would work but also `t1.gt`, `t1.lt`, etc.

**Comment by vegapit** [comment]
Understood, thank you.

Also as a general comment, according to the doc, the method `apply_` of the `Tensor` struct takes a function implementing the `nn::Module` trait as argument. Would it be possible to pass to it a function implementing `Fn(&Tensor) -> Tensor` for example?

**Comment by LaurentMazare** [comment]
Fwiw I've added the `where_` test to the standard test suite so that it's easier to discover.
Re using closures directly in `apply_` that's actually not very straightforward: if we would like closure to implement the `Module` trait they would also need to implement the `std::fmt::Debug` trait which is not currently the case. Introducing our own `Debug` trait would probably help but doesn't seem very nice.

An easy solution would be to add a method with a different name than apply, e.g. `map`, but not sure if it would help this much, e.g. we would be able to write something like `xs.apply_(&mymodule).map(|x| x.exp() + 1)`.

**Comment by vegapit** [comment]
Great news about the `where_` test. I think many coming from *PyTorch* would not know the comparison methods (`ge`,`eq`,`lt`,etc...) so best to have a small test showing its use.

Thinking about it, `apply` in *PyTorch* can be replaced in most cases by an explicit `Tensor` calculation so it is more convenient than functionally critical. But one thing *PyTorch* does not seem to support is an `apply_row` function that loops through a tensor row-by-row and stacks the output. Do you think such a function could be useful?

**Comment by LaurentMazare** [comment]
Maybe it would make sense to have such `apply_row` function indeed or some equivalent of `map` or `fold`. I imagine that the reason why it's not there is that this would result in some python loop which would be slow and run on the cpu and you should rather write use some vectorized operations that are more efficient. That said it's not always possible/desirable to use vectorized operations so it could actually be helpful to have this `apply_row` (also the cost of the loop in rust should be far less than in python - even though it's cpu only).

**Comment by vegapit** [comment]
I am not sure why such a function is not available. It is probably the same reason why some of the tensor methods can not be "broadcast". If it was just a performance issue in Python, it would exist in the C++ library, and I am not so sure it does. I will look into it after I have finished writing the next tutorial...
