### ISSUE TITLE
how to set nograd() globally?

### ISSUE THREAD

**Issue by 3togo** [LaurentMazare/tch-rs#808]
In python, it will be something like torch.set_grad_enabled(false).

How to do it in rust?

**Comment by LaurentMazare** [comment]
As most rust libraries, tch tries to avoid having some global states. Instead it's possible to disable gradient tracking either within a closure, [example here](https://github.com/LaurentMazare/tch-rs/blob/dca12b647ade36414c09359bade840d5092087d6/examples/reinforcement-learning/policy_gradient.rs#L48), or for the rest of the block using a RAII style guard, [example here](https://github.com/LaurentMazare/tch-rs/blob/dca12b647ade36414c09359bade840d5092087d6/examples/llama/main.rs#L340).

**Comment by 3togo** [comment]
many thanks.
