### ISSUE TITLE
list all visible devices

### ISSUE THREAD

**Issue by zeroexcuses** [LaurentMazare/tch-rs#81]
I'm trying to list all visible devices from tch-rs.

I did a search:
```
grep "device" . -R | grep fn
./wrappers/tensor.rs:    pub fn device(&self) -> Device {
./wrappers/tensor_fallible_generated.rs:    pub fn f_to(&self, device: Device) -> failure::Fallible<Tensor> {
./wrappers/device.rs:    pub fn device_count() -> i64 {
./wrappers/tensor_generated.rs:    pub fn to(&self, device: Device) -> Tensor {
./wrappers/tensor_generated.rs:    pub fn to4(&self, device: Device, dtype: Kind, non_blocking: bool, copy: bool) -> Tensor {
./data.rs:    pub fn to_device(&mut self, device: Device) -> &mut Iter2 {
./nn/var_store.rs:    pub fn new(device: Device) -> VarStore {
./nn/var_store.rs:    pub fn device(&self) -> Device {
./nn/var_store.rs:    pub fn device(&self) -> Device {
./nn/init.rs:pub fn init(i: Init, dims: &[i64], device: Device) -> Tensor {
./tensor/mod.rs:    pub fn to_device(&self, device: Device) -> Tensor {
./tensor/mod.rs:    pub fn f_to_device(&self, device: Device) -> Fallible<Tensor> {
```

There is an interesting function:
```
impl Cuda {
    /// Returns the number of GPU that can be used.
    pub fn device_count() -> i64 {
        let res = unsafe_torch!({ torch_sys::atc_cuda_device_count() });
        i64::from(res)
    }

```

but I don't see a way to enumerate the devices.

=====

My goal here is to debug the XY problem of why it's taking Cuda 4 seconds to init. My theory is that LibTorch is loading the cuda kernels on _all_ GPUs, and the 980 GTX TI is slowing me down. To test this however, I need a way from Rust to list all visible cuda devices.

**Comment by LaurentMazare** [comment]
Any reason why the output of `Cuda::device_count`` does not work for you ? I would assume that once you get that you can iterate over the device using their ids (from 0 to `device_count-1`) and they hopefully would match what the output of `nvidia-smi`.
Maybe the python api provides more details about device but afaik that's all that is exposed on the C/C++ side.

**Comment by zeroexcuses** [comment]
> I would assume that once you get that you can iterate over the device using their ids (from 0 to device_count-1) and they hopefully would match the output of nvidia-smi.

I'm almost certain they do not match output of nvidia-smi.

According to https://stackoverflow.com/questions/13781738/how-does-cuda-assign-device-ids-to-gpus devices are listed by fastest to slowest. However, when I do `nvidia-smi` I get:

```
nvidia-smi
Tue Jul 23 13:46:06 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 00000000:02:00.0  On |                  N/A |
| 50%   77C    P0    67W / 250W |    870MiB /  6083MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
|  0%   43C    P8     9W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:83:00.0 Off |                  N/A |
|  0%   40C    P8    10W / 250W |      2MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

That said, it's 100% true that since the Cuda devices are 0-(device_count-1), I should be able to just enumerate them. Thanks for the idea -- let me see what info I can do with that.

**Comment by zeroexcuses** [comment]
```
    let r = Cuda::device_count();
    println!("device count: {}", r);

    let d0 = tch::Device::Cuda(0);
    let d1 = tch::Device::Cuda(1);

    let dtype = tch::Kind::Float;

    let start = Instant::now();
    let x0 = Tensor::zeros(&[1, 1], (dtype, d0));
    let time_to_first = Instant::now();

    let x1 = Tensor::zeros(&[1, 1], (dtype, d1));
    let time_to_both = Instant::now();

    println!("time to init 1 GPU: {:?}", time_to_first - start);
    println!("time to init 2 GPU: {:?}", time_to_both - start);
```

results in:

```
device count: 2
time to init 1 GPU: 5.713648972s
time to init 2 GPU: 11.145377009s
```

This is insane. 5 (I thought it used to be 4??) seconds to initialize 1 GPU. If I want to init 2, it's 11 seconds. Not result I was hoping. :-)

===

I was able to test this indeed was using the 1080 gtx's by allocating a 1M array and monitoring nvidia-smi.

**Comment by zeroexcuses** [comment]
Here's the nvidia-smi while running the above (with a `while true {}` to keep it alive)

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 00000000:02:00.0  On |                  N/A |
| 49%   77C    P0    68W / 250W |    898MiB /  6083MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
|  0%   49C    P8    11W / 250W |    653MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:83:00.0 Off |                  N/A |
|  0%   45C    P8    11W / 250W |    653MiB / 11178MiB |      0%      Default |
```

If I'm reading this correctly, both GPUs have loaded 653MB worth of KERNELS ? Does this sound right / reasonable ? The only allocation on either advice is a 1x1 tensor.

**Comment by LaurentMazare** [comment]
If this issue also happens using the python api, maybe you should make it an issue on their [github repo](https://github.com/pytorch/pytorch) ? It doesn't seem very likely to be specific to the rust bindings.

**Comment by zeroexcuses** [comment]
You're right, this belongs over at the libtorch repo. Thanks again for all your help.

**Comment by zeroexcuses** [comment]
Sorry for more basic question: -- what does tch-rs use caffe2 for ?

https://github.com/LaurentMazare/tch-rs/blob/8ac1d9d1494121702e4c09fa1b36cd3b813584f5/torch-sys/build.rs#L156

I don't see caffe2 referred to anywhere else in tch-rs.

The XY problem I'm running into is that I'm building a minimal libtroch with only sm 6.1 (for 1080) and no caffe2. However, tch-rs wants -lcaffe2, but I can't figure out how tch-rs uses caffe2.
