### ISSUE TITLE
pyo3-tch 0.14.0

### ISSUE THREAD

**Issue by calvinleungyk** [LaurentMazare/tch-rs#812]
Hi Laurent, great work on making the bindings available to the community! Appreciate all the effort.

I saw that `pyo3-tch==0.14.0` is already used within the `tch-rs` repo. Was wondering when it would be ready to be released?

Thank you very much for your help!
Calvin

**Comment by LaurentMazare** [comment]
Ah good catch I actually just forgot to release it, should be done now.

**Comment by calvinleungyk** [comment]
Thanks a lot!
