### ISSUE TITLE
random_batch2, index on device vs CPU ?

### ISSUE THREAD

**Issue by zeroexcuses** [LaurentMazare/tch-rs#83]
Is https://github.com/LaurentMazare/tch-rs/blob/ec1e8ff2245065e9f33ade53e103548e9f62807d/src/tensor/mod.rs#L430 a bug ?

if device == CPU, the code works fine.

However, if device == CUDA, then the index tensor is created on the CPU.

For the index_select call, we then end up doing:

(CUDA TENSOR).index_select( CPU_TENSOR ).

^--- I think this is what is causing an exception, but I may be entirely wrong.

**Comment by zeroexcuses** [comment]
In particular, consider call of the form:

```
 pub fn random_batch2(
        t1: &CUDA TENSOR,
        t2: &CUDA TENSOR,
        batch_size: i64,
        device: Device = Cuda(0),
    )
```

**Comment by LaurentMazare** [comment]
Thanks for catching this, it indeed seemed to be an issue so I just pushed a fix for this. We should probably also more tests at some point (although CI doesn't have a gpu so it wouldn't have helped that much in this case).

**Comment by zeroexcuses** [comment]
Thanks for the fix!

1. Sorry for being pedantic, from:

```
        let index = Tensor::randint(len1, &[batch_size], (Kind::Int64, device));
        let batch1 = t1.index_select(0, &index).to_device(device);
        let batch2 = t2.index_select(0, &index).to_device(device);
```

We can infer that `device == tensor1.device == tensor2.device`
Doesn't this make the `device` field redundant?

2. Also, I believe we have the same issue for random_batch:

```
    pub fn random_batch(&self, batch_size: i64) -> Tensor {
        let len: i64 = self.size()[0];
        let index = Tensor::randint(len, &[batch_size], crate::wrappers::kind::INT64_CPU);
        self.index_select(0, &index)
    }
```

where regardless of what device the input tensor is on, the index is always allocated on the CPU, which results in exception at the index_select call.

**Comment by LaurentMazare** [comment]
Right, I've just pushed some changes so that we use the device of the tensor arguments for both functions.

**Comment by zeroexcuses** [comment]
Thanks for fixing both!
