### ISSUE TITLE
Converting tch::Tensor to Python Object leads to panic.

### ISSUE THREAD

**Issue by CallMeMSL** [LaurentMazare/tch-rs#834]
Hello,
I'm currently working on implementing a PyTorch Dataset in Rust. I'm using PyO3 to create the Python package. In essence, I'm keeping a list of tch::tensors and want to return slices of them (that I create with `tensor.i(..)`) as Python objects, but I cant get this minimal example to work:

```rust
#[cfg(test)]
mod tests {
    use pyo3::prelude::*;

    use pyo3_tch::PyTensor;
    use tch::Tensor;

    #[test]
    fn test() {
        let tensor = Tensor::from_slice(&[3, 1, 4, 1, 5]);
        let pyt = PyTensor(tensor);
        let python_tensor: Py<PyAny> = Python::with_gil(|py| pyt.into_py(py).into());
    }
}
```
the conversion to a python object leads to `(signal: 11, SIGSEGV: invalid memory reference)`.
Any Idea if I'm doing something wrong or if this is a bug?

Kind Regards,
David

**Comment by LaurentMazare** [comment]
A common cause for such segfaults is using a libtorch version on the rust side that is not the same as the one used on the python side. Are you using `LIBTORCH_USE_PYTORCH` as the way to detect the libtorch install? That's usually the safest when doing python bindings.

**Comment by CallMeMSL** [comment]
I tried to use `LIBTORCH_USE_PYTORCH` on a fresh google cloud deep learning vm (with an adjusted pytorch version). Which yields the following error:

`error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory`

I rememberded that you had a note about this in the README, so i first did `pip list -v` wich included the line:

```
Package                                  Version         Location                                Installer
---------------------------------------- --------------- --------------------------------------- ---------
...
torch                                    2.1.0+cu121     /opt/conda/lib/python3.10/site-packages pip
...
```

afterwards i did `export LD_LIBRARY_PATH=/opt/conda/lib/python3.10/site-packages/torch/lib/:$LD_LIBRARY_PATH`

now i receive the following error:
`error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`

but this file doesn't seem to exist in the installation:

```bash
(base) david@machine:/opt/conda/lib/python3.10/site-packages/torch$ find . -iname  "*.so"
./lib/libtorch_cuda_linalg.so
./lib/libtorch_python.so
./lib/libc10.so
./lib/libcaffe2_nvrtc.so
./lib/libc10_cuda.so
./lib/libnvfuser_codegen.so
./lib/libtorch.so
./lib/libshm.so
./lib/libtorch_cuda.so
./lib/libtorch_cpu.so
./lib/libtorch_global_deps.so
./_C.cpython-310-x86_64-linux-gnu.so

```

**Comment by CallMeMSL** [comment]
Hi,
I tried to use `LIBTOCH_USE_PYTORCH` before, but I just got this error message: ` error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory`. I tried again with the fix that you mentioned in the README:

First i did `pip list -v` with included this line:
```
Package                                  Version         Location                                Installer
---------------------------------------- --------------- --------------------------------------- ---------
...
torch                                    2.1.0+cu121     /opt/conda/lib/python3.10/site-packages pip
...
```
I then did: ` export LD_LIBRARY_PATH=/opt/conda/lib/python3.10/site-packages/torch/lib/:$LD_LIBRARY_PATH`
which now yield the following error:
`error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory`

So i searched fo the file again: `sudo find / -name libpython3.10.so.1.0` and included this folder aswell.
`export LD_LIBRARY_PATH=/opt/conda/lib/:$LD_LIBRARY_PATH`.

But now i run into the same error as before:
`(signal: 11, SIGSEGV: invalid memory reference)`

**Comment by LaurentMazare** [comment]
Did you check this example

> I think my question in general is, if the 3 lines above are semantically valid code. I didn't find any code examples that create PyTorch tensors from tch tensors.
> The example that is provided for pyo3-tch uses `PyTensor` only as a method parameter

Not entirely sure what you mean here, the `add_one` example returns a tch tensor that gets converted to a PyTorch tensor via this `PyTensor` layer?

**Comment by CallMeMSL** [comment]
Hi,
thank you for being so patient with me. I have taken another look at the example and I found my problem the problem in the code snipped above.
You import torch in the `pymodule` method.

So I did the same and this code now compiles without problems and prints `tensor([3, 1], dtype=torch.int32)`:

```rust
#[cfg(test)]
mod tests {
    use pyo3::prelude::*;
    use pyo3::types::IntoPyDict;

    use pyo3_tch::PyTensor;
    use tch::IndexOp;
    use tch::Tensor;

    #[test]
    fn test() {
        let tensor = Tensor::from_slice(&[3, 1, 4, 1, 5]);
        let slice = tensor.i(0..2);
        let pyt = PyTensor(slice);
        let python_tensor: Py<PyAny> = Python::with_gil(|py| {
            py.import("torch").unwrap(); // this was missing!
            pyt.into_py(py).into()
        });
        Python::with_gil(|py| {
            let _ = py.eval("print(t)", None, Some([("t", python_tensor.as_ref(py))].into_py_dict(py)));
        });
    }
}
```

Thank you for your help!
