### ISSUE TITLE
Can't compile or test tch-rs

### ISSUE THREAD

**Issue by v-espitalier** [LaurentMazare/tch-rs#866]
Hi,

I can't manage to test tch and play with tensors in rust. I spent many hours now, with vscodium & console only, via conda or pytorch.org direct download, followed many tutorials (official one and unofficial)..

I am attempting to use tch-rs 0.15.0 (downloaded automatically by cargo using dependancies), to run the following example program:
(from https://home.futuretim.io/posts/tch_test/ )
""
use tch::{Tensor, Device};

fn main() {
    println!("Hello, world!");

    let device = Device::cuda_if_available();

    let val = Tensor::rand([2, 3], (tch::Kind::Float, device));

    println!("Device info:");
    println!("{:?}", device);
    
    println!("Values:");
    val.print();
}

""

2 "best" solutions I get :

* I manage to compile by unzipping "libtorch-cxx11-abi-shared-with-deps-2.2.0+cu118" from pytorch.org to my "/home/user/" and use these environment variables:
export LIBTORCH=/home/user/libtorch
export LIBTORCH_LIB=/home/user/libtorch/
export LIBTORCH_INCLUDE=/home/user/libtorch/
export LIBTORCH_BYPASS_VERSION_CHECK=1

But I get the following error :
$ target/debug/tch-test
~~~
target/debug/tch-test: error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory
~~~

I know this is not the advised version of cuda (11.8 instead of 11.7) so I tried another solution, with micromamba ( wrapper for conda, much faster ) :
$ micromamba create -n pytorch220_cuda117
$ micromamba activate pytorch220_cuda117
(pytorch220_cuda117) $ micromamba install pytorch==2.2.0 pytorch-cuda=11.7 torchvision -c pytorch -c nvidia -c anaconda

then: 
export LIBTORCH=/home/user/micromamba/envs/pytorch220_cuda117/lib/python3.11/site-packages/torch
export LIBTORCH_LIB=/home/user/micromamba/envs/pytorch220_cuda117/lib/python3.11/site-packages/torch/
export LIBTORCH_INCLUDE=/home/user/micromamba/envs/pytorch220_cuda117/lib/python3.11/site-packages/torch/
export LIBTORCH_BYPASS_VERSION_CHECK=1
export LIBTORCH_USE_PYTORCH=1

and $ target/debug/tch-test
Setting LIBTORCH_USE_PYTORCH=1 was necessary to compile, but activating or not the conda environment was not.
I manage to compile, but I get the same error:
~~~
target/debug/tch-test: error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory
~~~

As well, before going to the console, I tried a third (first actually) way through vscodium, and my usual environment, with pytorch/cuda versions 2.1.2.post303 + cuda 12.0, and get the very same error.

Did I miss something obvious ? Can someone please advises ? Thanks in advance.

**Comment by LaurentMazare** [comment]
With the first of your two solutions you probably want to try setting `LD_LIBRARY_PATH` to the directory that contains this `libtorch_cuda.so` this is not important when compiling but when running the compiled binary.

**Comment by v-espitalier** [comment]
Thank for your quick reply.

I went further in the investigation following your advise, and it works, thanks.

For the records, here are the steps I followed. The pytorch.org / .zip solution worked, but not the conda one.


### Working solution: libtorch from pytorch.org (libtorch 2.2.0 + cuda 11.8)

Download libtorch from pytorch.org, unzip it in your favorite location, and record the 'libtorch' folder path (to your home for instance):
$ wget https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.2.0%2Bcu118.zip
$ unzip libtorch-cxx11-abi-shared-with-deps-2.2.0%2Bcu118.zip -d /home/user

In the following lines, you need to replace '/home/user/libtorch' with the actual location where you unzipped the files to.
If you unzipped to your home, you should see these folders and files for instance :
~~~
/home/user/libtorch/lib
/home/user/libtorch/include
/home/user/libtorch/lib/libtorch.so
/home/user/libtorch/lib/libtorch_cuda.so
~~~

After unzipping, export env variables, compile, and test:
~~~
$ export LIBTORCH="/home/user/libtorch"
$ export LIBTORCH_LIB="$LIBTORCH"
$ export LIBTORCH_INCLUDE="$LIBTORCH"
$ export LIBTORCH_BYPASS_VERSION_CHECK=1    # We installed cuda 11.8 whereas the tchis expecting 11.7
$ export LD_LIBRARY_PATH="$LIBTORCH/lib"
~~~

Checks:
~~~
$ find "$LIBTORCH" | grep libtorch.so
$ find "$LIBTORCH" | grep libtorch_cuda.so
$ find "$LD_LIBRARY_PATH" | grep libtorch_cuda.so
~~~

Compilation and test:
~~~
$ cargo build
$ target/debug/tch-test
~~~

The program runs. In order to make it work permanently, as always, you need to add the 5 export lines at the end of your .bashrc

If you update the version of libtorch, you may need to recompile your tch rust programs. Otherwise, as when you launch them, the dynamicly loaded librairies may have mismatched version from the building-time used ones and you may get weird error message (missing file sth) at running time (happened to me).


### Other test (not working) : libtorch from conda (libtorch 2.2.0 + cuda 11.8)

It may be out of scope at this point, but I tried to go through conda, without success. I don't need to get a solution as the .zip seems to work fine.

But I provide the tests I followed, in case anyone want to dig further. I would still be interested. Otherwise I will wait for the next version of pytorch-gpu.


So, where to find, in conda, the required files (among others) for tch-rs: libtorch.so and libtorch_cuda.so, with version 2.2.0 ?

I tested 3 possible packages: pytorch-gpu, pytorch-cuda or simply pytorch.

* 'pytorch-gpu' is currently built up to 2.1.2 on conda-forge ; not the right version for tch -> Next package !
conda search pytorch-gpu -c pytorch -c conda-forge
pytorch-gpu                    2.1.2 cuda120py38h6767744_301  conda-forge
conda search pytorch-gpu -c pytorch
pytorch-gpu                    1.3.1               0  pkgs/main


* Surprisingly, 'pytorch-cuda' does not seem to provide libtorch_cuda.so (I guess I did sth wrong, but where -see below- ?). -> Next !
~~~
$ micromamba create -n pytorch220_cuda117
$ micromamba activate pytorch220_cuda117
$ micromamba install pytorch==2.2.0 pytorch-cuda=11.7 torchvision -c pytorch -c nvidia -c anaconda
~~~

$ find /home/user/micromamba/envs/pytorch220_cuda117/lib/ | grep libtorch.so$
gives:
/home/user/micromamba/envs/pytorch220_cuda117/lib/python3.11/site-packages/torch/lib/libtorch.so
but
find /home/user/micromamba/envs/pytorch220_cuda117/lib/ | grep libtorch_cuda.so$
returns blank (!!)


* Third package test: 'pytorch' package, with specific cuda-enabled build:

$ conda search pytorch -c pytorch | grep 2.2.0 | grep cuda
py3.10_cuda11.8_cudnn8.7.0_0
py3.10_cuda12.1_cudnn8.9.2_0
$ micromamba search pytorch -c pytorch | grep 2.2.0 | grep cuda
py3.9_cuda12.1_cudnn8.9.2_0
(The 2 commands unexpectedly give different outputs, but at this point, I am ready to hear anything.)

Checked python version:
$ python --version
Python 3.10.9

Then installed the package proposed by conda, using micromamba:
~~~
$ micromamba create -n pytorch220_cuda118
$ micromamba activate pytorch220_cuda118
$ micromamba install pytorch=2.2.0=py3.10_cuda11.8_cudnn8.7.0_0 torchvision -c pytorch -c nvidia -c anaconda
~~~
(The 3 repos specs are required)

In that case, the libtorch path is:
/home/user/micromamba/envs/pytorch220_cuda118/lib/python3.10/site-packages/torch

I exported the 5 environment variables, following the working solution above.

But then, when I  $ cargo build, I get the error:
~~~
$ cargo build
   Compiling torch-sys v0.15.0
   Compiling tch v0.15.0
   Compiling tch-test v0.1.0 (/home/user/Bureau/Bureau2/workarea/test_tch/tch-test)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/user/micromamba/env...
...
...(very long lines or line*)
...
.../user/micromamba/envs/pytorch220_cuda118/lib/python3.10/site-packages/torch/include/ATen/core/function_schema_inl.h:337: undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `tch-test` (bin "tch-test") due to 1 previous error
~~~

Anyway, I will stick to the .zip solution until pytorch-gpu from conda-forge publishes a package with the 2.2.0 torch version..

**Comment by v-espitalier** [comment]
Dear Laurent,
Just to thank you again for your quick help. I managed to go through my (holiday) project involving tch-rs :
https://github.com/v-espitalier/Raytracer-tch-rs

Best Regards,
Vincent.
