### ISSUE TITLE
What if I am not using `pyo3==0.18.3`?

### ISSUE THREAD

**Issue by nleroy917** [LaurentMazare/tch-rs#867]
Hello!

Thank you so much for all the work here! I have a quick question about the extension module.. `pyo3-tch`. My use case is that I just want to return Python-native `torch` tensors from a `pyo3`-built python package/library.

I tried adding `pyo3-tch="0.15.0"` to my `Cargo.toml`, but that conflicts a lot with my requirement for `pyo3` which I have pinned to `0.21.0` for another crate `rust-numpy`.

I'm wondering if you have advice here? I'm pretty new to Rust, still learning a lot and getting my bearings so any help is super appreciated!

**Comment by LaurentMazare** [comment]
Ah that's a good point, I just made #868 to update to pyo3 `0.21` and it seems to work all well based on some simple testing.
I won't do a specific release on crates.io for this as pytorch 2.3 is only a couple days away and the PR to support it in tch-rs is already done, so once this is out I'll release version 0.16 for all the crates which will include this pyo3 update.

**Comment by nleroy917** [comment]
Hey, thanks so much! Not that I anticipate it occurring soon, but wondering what happens if I need to bump my `pyo3` in the future?

**Comment by LaurentMazare** [comment]
We don't have a good story for supporting all combinations of pyo3 and tch. One point to note is that `pyo3-tch` is really small so you can just embed a copy of it in your code if you need some tweaks like this.
