### ISSUE TITLE
GRU::zero_state -> wrong shape

### ISSUE THREAD

**Issue by vegapit** [LaurentMazare/tch-rs#88]
Hey,

The `GRU::zero_state` is missing a dimension which makes the `seq` method fail. According to the PyTorch doc, you can make it work by changing it to:
```rust
   fn zero_state(&self, batch_dim: i64) -> GRUState {
        let dim = if self.config.bidirectional { 2 } else { 1 };
        let shape = [dim * self.config.num_layers, batch_dim, self.hidden_dim];
        GRUState(Tensor::zeros(&shape, (Kind::Float, self.device)))
    }
```
Should be a similar problem with the `LSTM` struct.

Cheers

**Comment by LaurentMazare** [comment]
Would you have some more details on how you're using this? Maybe you want to compare your code with the [seq2seq example](https://github.com/LaurentMazare/tch-rs/blob/master/examples/translation/main.rs) and the [char-rnn example](https://github.com/LaurentMazare/tch-rs/blob/master/examples/char-rnn/main.rs) included in tch-rs. Both examples should work fine with the current `zero_state` implementation (using GRU and LSTM), that said I think they probably only use `num_layers=1`.

**Comment by vegapit** [comment]
Hmmm, the `char-rnn` example fails to run on my setup: Cloned latest repo and linked them to PyTorch C++ 1.1 libraries (libtorch). 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TorchError { c_error: "Expected more hidden states in stacked_rnn (apply_layer_stack at ../aten/src/ATen/native/RNN.cpp:515)
```

**Comment by LaurentMazare** [comment]
Looks like there is some incoherence between `seq` and `step` (maybe this was introduced in the 1.1 release ?). Anway I would suggested using `step` for the time being as does the seq2seq example and everything seems to work well here - and I'll try to fix the `seq` behavior when I get a chance.

**Comment by vegapit** [comment]
The PyTorch 1.1 API doc states that: The `GRUCell` module (used by `step`) take a 2-dimensional input while the `GRU` module ( used by `seq_init`) takes a 3-dimensional one. Maybe they have changed the function signatures in 1.1 as you point out.

For this reason, I find `seq_init` more convenient than `step` for doing the incremental decoding as I can work in 3D all the way through. Making the `GRUState` public is all I needed to do to make everything work as I initialise - a single-layer and unidirectional `GRU` in this case - with:

```rust
let init_state = GRUState( Tensor::zeros(&[1,batch_size,self.hidden_size], (Kind::Float, Device::Cpu)) );
let encoder_output_set = self.encoder.seq_init( &emb_x, &init_state ); 
```

These issues are simple to fix, I am happy to contribute if it helps.

**Comment by LaurentMazare** [comment]
By 'simple to fix', do you mean that it's easy to switch 'zero_state' to work for 'seq_init' ? I agree that this would indeed be easy to change but this would break the current seq2seq example as it relies on 'step' rather than on 'seq', so I would like to think a bit more about what this involves before making the change. 'step' could probably be implemented using 'seq' but I'm a bit unsure of the performance implications of this.
Anyway I'll try to think about it over the next few days, and I think you're right that the 3D case should be well supported - also this is probably the only way to get biderctional or multi-layered RNN to work. Another conclusion is that this part of the API should have some tests so that we catch issues earlier as it's a bit sad that examples that use to run don't work anymore.

**Comment by vegapit** [comment]
Yes, just had a look at the code for the *translation* example. The problem would be on your 2 uses of the `zero_state` (line 127 and 158) that you directly pass to `step`. But the fix is as easy as using `squeeze` on the output of the new 3D 'zero_state' function. That would fix the `seq` call in the *char-rnn* example at the same time.

**Comment by LaurentMazare** [comment]
I'm afraid this would only work in the current situation but wouldn't fix the case where `bidirectional` is true or where `num_layers` is greater than one. As `gru_cell` and `lstm_cell` don't support these options anyway we should probably either not expose them or have a step implementation that supports them (which makes sense for `num_layers` but less for `bidirectional`).

**Comment by vegapit** [comment]
Ok let's look at it this way, taking `GRU` as an example: A `GRU` is simply a vector of `GRUCell`. You have one cell per direction and per layer, so an initial state for the `GRU` is just a stacked vector of the initial 2D state for each cell, hence 3D.

Your `zero_state` function is currently returning the initial 2D state for a single cell but it is a method of the `GRU` struct which is where the inconsistency lies. Why not renaming your function to `zero_state_cell` and make mine as the `zero_state`?

**Comment by LaurentMazare** [comment]
> Your `zero_state` function is currently returning the initial 2D state for a single cell but it is a method of the `GRU` struct which is where the inconsistency lies. Why not renaming your function to `zero_state_cell` and make mine as the `zero_state`?

Sorry I probably wasn't very clear in my previous comment but I think that there is a more profound issue behind this which is that `step` doesn't handle some of the options than `seq` does and I don't think such a change would fix it. So before handling the zero state differently I think we should rationalize the RNN trait and be clear whether or not this supports `bidirectional` (probably hard) and `num_layers` (maybe easier).

**Comment by vegapit** [comment]
From a code architecture perspective, I think having 2 separate traits is best: `RNN` and `RNNCell`. Number of directions and number of layers would not apply to a `Cell` by very definition, so it would make the library very consistent.

**Comment by LaurentMazare** [comment]
Maybe, an other possibility would be to have `RNN` and `RNNBidirectional` as `num_layers` could actually apply to cells if you just stack them.
From an user perspective this may be a bit simpler as when you use `RNN` you would have access to both `step` and `seq`, `seq` is useful for training but `step` is actually pretty useful for inferences e.g. for things like char-rnn or more time series tasks.

**Comment by vegapit** [comment]
After all, why would you want to expose `RNNCell` at all? The user can always create one using an `RNN` and use `seq_init` to go step-by-step if required (that's what I do in my seq2seq implementation). I can not think of a configuration where you would need to stack `RNNCell` and avoid `RNN`.

**Comment by LaurentMazare** [comment]
Yes that's actually what I meant by "'step' could probably be implemented using 'seq' but I'm a bit unsure of the performance implications of this.". I'm not sure how the performance of these compare especially on gpu so this should probably be studied a bit more in depth.
That said `step` doesn't make much sense for bidirectional things hence providing it only for the 'standard' rnn trait and not for the bidirectional one may make sense.

**Comment by vegapit** [comment]
I see what you mean about `step` in a `bidirectional` setting. It can be calculated but hard to see a practical use for it. While we are on the subject, I could not get `GRU` to work at all in a `bidirectional` setting. It could be a bug in the PyTorch C++ API, I am not sure.

**Comment by LaurentMazare** [comment]
Actually PyTorch 1.2 just got released and hopefully include the latest fixes on the C++ side so I'll switch to using it and will give a try at bidirectional at this point.

**Comment by vegapit** [comment]
Yep, and it looks like it has been fixed! 

> C++ Frontend bug fixes
nn::RNN: Fix assertions in bidirectional RNN. (22850).

I will give it a go as well.

**Comment by vegapit** [comment]
> Yep, and it looks like it has been fixed!
> 
> > C++ Frontend bug fixes
> > nn::RNN: Fix assertions in bidirectional RNN. (22850).
> 
> I will give it a go as well.
Unfortunately, I am still getting the same inaccurate error when trying to initialise a bidirectional GRU
```
c_error: "Odd number of params or hiddens given to a bidirectional RNN"
```

**Comment by LaurentMazare** [comment]
> > Yep, and it looks like it has been fixed!
> > > C++ Frontend bug fixes
> > > nn::RNN: Fix assertions in bidirectional RNN. (22850).
> > 
> > 
> > I will give it a go as well.
> 
> Unfortunately, I am still getting the same inaccurate error when trying to initialise a bidirectional GRU
> 
> ```
> c_error: "Odd number of params or hiddens given to a bidirectional RNN"
> ```

What did you use as initial shape, something like `[num_layers*2, batch, hidden]` ?
I should have some time to work on this over the weekend so I'll probably give it a try too + split the bidirectional vs unidirectional rnn traits.

**Comment by vegapit** [comment]
Yep, I followed the PyTorch doc pretty closely. Here is the code snippet:
```rust
let emb_x = self.embedding.forward( &x ); // [batch_size,seq_len,dim]
let init_state = GRUState( Tensor::zeros(&[2,batch_size,self.hidden_size], (Kind::Float, Device::Cpu)) );
let encoder_output_set = self.encoder.seq_init( &emb_x, &init_state );
```
with `self.encoder` initialised with:
```rust
encoder: nn::gru(&p, hidden_size, hidden_size, RNNConfig{ bidirectional: true, ..Default::default() })
```

**Comment by LaurentMazare** [comment]
I just pushed some changes that seem to get bidirectional and multiple layers to work on GRU.
- This does not include any trait change, `step` is implemented in terms of `seq_init`.
- The LSTM hasn't been adapted yet.
You can see some relevant tests at the bottom of [nn_tests.rs](https://github.com/LaurentMazare/tch-rs/blob/master/tests/nn_tests.rs), this should give an idea of how shape works (I haven't tested it on real life examples as I only have access to a small laptop right now).
If this seems reasonable after testing it a bit more I'll adapt the LSTM to work in a similar way.

**Comment by vegapit** [comment]
I have updated my code to use a bidirectional GRU encoder with a 2-layer GRU decoder, and it is training well so far. Also, I have noticed that the load on CPU during training has massively decreased with this version of libtorch. Great work.
