### ISSUE TITLE
error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by t348575** [LaurentMazare/tch-rs#882]
While building my application using tch-rs I get the following error:

The below error was recorded with `LIBTORCH_USE_PYTORCH=1` but I'm getting the same error also by using a local libtorch installation. I'm getting the same error when trying older versions of tch-rs as well. 
```
= note: /usr/bin/ld: /my_path/target/debug/deps/libtorch_sys-22e6ea8ca0c254b2.rlib(19072f24a82f85ae-torch_api_generated.o): undefined reference to symbol '_ZN3c107WarningC1ESt7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEENS_14SourceLocationEPKcb'
          /usr/bin/ld: /my_path/.venv/lib/python3.11/site-packages/torch/lib/libc10.so: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
```

**Comment by LaurentMazare** [comment]
That's odd, I don't run into this issue on my linux box. Could you try running the following as it may help track which is the missing DSO depandancy?
```
ldd /my_path/.venv/lib/python3.11/site-packages/torch/lib/libc10.so
```

**Comment by t348575** [comment]
I think this was some wierd issue with my environment, cleaning and re-installing everything (including CUDA) seems to have fixed it.
