### ISSUE TITLE
get list of vars with their path/name ?

### ISSUE THREAD

**Issue by zeroexcuses** [LaurentMazare/tch-rs#90]
I know about `.trainable_vectors` -- it returns Vec<Tensor>.

What I need is an iterator returning (path/name, Variable/Tensor). The reason I need this is that ".grad()" on some tensor is crashing (kind: 13 -- unsupported). Right now, I can't figure out which vector this is.

Therefore, I want a way to get (path/name, Varaible/Tensor) iterator, so that on failure, I can print the path/name.

**Comment by LaurentMazare** [comment]
Tensor kind ids come from PyTorch [ScalarType.h](https://github.com/pytorch/pytorch/blob/master/c10/core/ScalarType.h). '13' was introduced after PyTorch 1.1 and seems to be `QUInt8`, maybe this helps finding the offending tensor ?
(also note that there is no guarantee of `tch-rs` working with the current development version of PyTorch).

Could you add some details on your problematic use case ? I would have thought that calling `.trainable_vectors` would be fine and then you can iterate over the returned vector, print their name and then print `tensor.grad().defined()`.

**Comment by zeroexcuses** [comment]
> Tensor kind ids come from PyTorch ScalarType.h. '13' was introduced after PyTorch 1.1 and seems to be QUInt8, maybe this helps finding the offending tensor ?
(also note that there is no guarantee of tch-rs working with the current development version of PyTorch).

I don't know what "current development version of PyTorch" means. I cloned PyTorch github repo, created a branch from tag "v1.1.0", and built from that. Am I on "current development version" ?

> Could you add some details on your problematic use case ? I would have thought that calling .trainable_vectors would be fine and then you can iterate over the returned vector, print their name and then print tensor.grad().defined().

I don't have a minimal failure case yet. I have a hand written RNN impl using Adam optimizer where

```
opt.backward_step(&err);
```
runs fine for many iterations

```
opt.backward_step_clip(&err, 0.5);
```
throws an exception.

I "unrolled" the opt.backward_step_clip

```
opt.zero_grad();
err.backward();
for t in vs.trainable_variables().iter() {
  println!("tensor: {:?}", t);
  t.grad().clamp_(-0.5_f64, 0.5_f64);
}
opt.step();
```

Bad things happen on the `t.grad().clamp_` call. I want to know which Tensor it is.

The println! line only giver me (shape + tch::Kind). However, there are all tensors in the "varstore", which means they were created with some tch::nn::Path -- is there a way to print this tch::nn::Path ?

**Comment by LaurentMazare** [comment]
> > Tensor kind ids come from PyTorch ScalarType.h. '13' was introduced after PyTorch 1.1 and seems to be QUInt8, maybe this helps finding the offending tensor ?
> > (also note that there is no guarantee of tch-rs working with the current development version of PyTorch).
> 
> I don't know what "current development version of PyTorch" means. I cloned PyTorch github repo, created a branch from tag "v1.1.0", and built from that. Am I on "current development version" ?

That would be the stable version (though v1.2.0 got released a couple hours ago).
Looking at [ScalarType.h](https://github.com/pytorch/pytorch/blob/v1.1.0/c10/core/ScalarType.h) for this version, there is no scalar type 13 so something seem very wrong here. I would be pretty interested if you can reduce your problematic example to something small enough.

> 
> Bad things happen on the `t.grad().clamp_` call. I want to know which Tensor it is.
> 
> The println! line only giver me (shape + tch::Kind). However, there are all tensors in the "varstore", which means they were created with some tch::nn::Path -- is there a way to print this tch::nn::Path ?

Not out of the box but you can easily tweak the current implementation to get the name back too.

**Comment by zeroexcuses** [comment]
> > The println! line only giver me (shape + tch::Kind). However, there are all tensors in the "varstore", which means they were created with some tch::nn::Path -- is there a way to print this tch::nn::Path ?

> Not out of the box but you can easily tweak the current implementation to get the name back too.

I can solve the problem by marking this field public
https://github.com/LaurentMazare/tch-rs/blob/master/src/nn/var_store.rs#L25

However, I was hoping there was some way to solve this without modifying tch-rs itself. I also think this issue generalizes to anyone building debugging tools -- they'll want a way to access all vars of a VarStore along with it's name.

**Comment by LaurentMazare** [comment]
Fwiw I've added a `variables` function to var-stores so that one can get tensors together with their names.
