### ISSUE TITLE
Update for PyTorch 1.2

### ISSUE THREAD

**Issue by LaurentMazare** [LaurentMazare/tch-rs#91]
In particular this should fix #76.

**Comment by vegapit** [comment]
Bad news for me. Torch-sys fails to compile on MacOSX with this new version. This is the only (unhelpful) error message I am getting:
```
error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/Users/blabla/dev/libtorch/include" "-I" "/Users/blabla/dev/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/Users/blabla/dev/libtorch/lib" "-std=c++11" "-fPIC" "-D_GLIBCXX_USE_CXX11_ABI=0" "-o" "/Users/blabla/dev/tchtut/target/release/build/torch-sys-8d045d293f6a0886/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp" with args "c++" did not execute successfully (status code exit code: 1).
```

**Comment by LaurentMazare** [comment]
That's unfortunate, there is nothing help that could be informative ?
Fwiw the current github tip for `tch-rs` should now work with 1.2.0 (and doesn't work anymore with 1.1.0), I have only tested it on linux with a locally compiled PyTorch as there aren't any precompiled binaries for linux at the moment.
I'm not sure about MacOSX but note that on any recent linux distribution when building PyTorch yourself you need to set the environment variable LIBTORCH_CXX11_ABI=1 in order to get things to work (not setting this will work with the pre-built binaries), if you give this a try you probably want to run a `cargo clean` first.

**Comment by vegapit** [comment]
Ok, it finally compiled. Compilation works with 'libtorch-macosx-1.2.0.zip' and not with 'libtorch-macosx-latest.zip'. A little confusing.

**Comment by LaurentMazare** [comment]
Glad that it worked, this was actually the same for the linux package except that I didn't find the 1.2.0.zip version so I recompiled them from source.
Anyhow once the linux binaries have been released I'll add some more detailed instructions to the main readme to try to make this less confusing.

**Comment by LaurentMazare** [comment]
An issue has been opened on PyTorch github about these confusing version numbers.
https://github.com/pytorch/pytorch/issues/24120

**Comment by jerry73204** [comment]
The 1.2.0 binary is available in nightly link:
https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-1.2.0.zip

The link on official site goes to a 1.3.0-dev nightly build.
https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-latest.zip

Interestingly, the "latest" on stable channel is still 1.1.0, and you get 404 if you change _latest_ to _1.2.0_. Probably it's a mistake.
https://download.pytorch.org/libtorch/cu100/libtorch-shared-with-deps-latest.zip

**Comment by LaurentMazare** [comment]
Thanks for pointing this out. Maybe I'm missing something here but I wasn't able to find the cpu versions which are the ones that would be useful to CI.

**Comment by soumith** [comment]
we screwed up the upload links, we were trying some new infrastructure. will fix tomorrow.

**Comment by vegapit** [comment]
Anyone knows where I could find a 1.2.0 CPU version for Linux ?

**Comment by LaurentMazare** [comment]
I haven't tested them yet but the binaries have just been published, e.g.
https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.2.0.zip

**Comment by LaurentMazare** [comment]
CI now uses the new cpu binaries and seem to work fine so closing this issue for now.
