### ISSUE TITLE
Would `tch-rs` benefit from Torchscript?

### ISSUE THREAD

**Issue by jean-airoldie** [LaurentMazare/tch-rs#92]
To quote from the [doc](https://pytorch.org/tutorials/beginner/deploy_seq2seq_hybrid_frontend_tutorial.html?highlight=torchscript):
> Although the eager interface is a beneficial tool for research and experimentation applications, when it comes time to deploy the model in a production environment, having a graph-based model representation is very beneficial. A deferred graph representation allows for optimizations such as out-of-order execution, and the ability to target highly optimized hardware architectures.

Does `tch-rs` use the same "eager interface" as opposed to a "graph-based" model? Would converting `tch-rs` code to `TorchScript` provide performance benefits when running a model in production? Or is `TorchScript` simply as way to remove the overhead of the python implementation & interpreter?

**Comment by LaurentMazare** [comment]
`tch-rs` indeed uses the "eager interface" but can also run graph-based model produced by torchscript.
There is a small tutorial showing how to do this [here](https://github.com/LaurentMazare/tch-rs/tree/master/examples/jit).
However note that `tch-rs` cannot produce torchscript models at this time, these can only be generated via the python api. I would agree that there shouldn't be much performance benefits when producing torchscript models from rust but maybe it would be worth it for very specific use case where torchscript would be able to fuse multiple operations together but the rust api wouldn't do this optimization.

**Comment by jean-airoldie** [comment]
Gotcha. So we can't know until we try, but the benefits are probably insignificant. I guess the best way to determine if it is worth it would be profile `TorchScript` against a base python script and see were the performance gains come from, and if they could potentially transfer to rust.

I'll keep this in mind thx!
