### ISSUE TITLE
failed to run custom build command for torch-sys v0.1.1

### ISSUE THREAD

**Issue by nazarblch** [LaurentMazare/tch-rs#94]
Caused by:
  process didn't exit successfully: `/home/nazar/cpp/tch-rs/target/debug/build/torch-sys-eb92c133e7ec9131/build-script-build` (exit code: 1)
--- stdout
cargo:rustc-link-search=native=/home/nazar/cpp/libtorch/lib
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/nazar/cpp/libtorch/include" "-I" "/home/nazar/cpp/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/home/nazar/cpp/libtorch/lib" "-std=c++11" "-fPIC" "-D_GLIBCXX_USE_CXX11_ABI=0" "-o" "/home/nazar/cpp/tch-rs/target/debug/build/torch-sys-637eb1483b0e44a9/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp"
cargo:warning=In file included from libtch/torch_api.cpp:6:0:
cargo:warning=libtch/torch_api.cpp: In function ‘void at_save_multi(at::Tensor**, char**, int, char*)’:
cargo:warning=libtch/torch_api.cpp:212:37: error: no matching function for call to ‘torch::serialize::OutputArchive::OutputArchive()’
cargo:warning=     torch::serialize::OutputArchive archive;
cargo:warning=                                     ^
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=In file included from /home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/serialize/archive.h:4:0,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/data/samplers/serialize.h:4,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/data/samplers.h:8,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/data/datasets/chunk.h:6,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/data/datasets.h:4,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/data.h:4,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/all.h:4,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/torch.h:3,
cargo:warning=                 from libtch/torch_api.cpp:2:
cargo:warning=/home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/serialize/output-archive.h:31:3: note: candidate: torch::serialize::OutputArchive::OutputArchive(torch::serialize::OutputArchive&&)
cargo:warning=   OutputArchive(OutputArchive&&) = default;
cargo:warning=   ^~~~~~~~~~~~~
cargo:warning=/home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/serialize/output-archive.h:31:3: note:   candidate expects 1 argument, 0 provided
cargo:warning=/home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/serialize/output-archive.h:28:12: note: candidate: torch::serialize::OutputArchive::OutputArchive(std::shared_ptr<torch::jit::script::CompilationUnit>)
cargo:warning=   explicit OutputArchive(std::shared_ptr<jit::script::CompilationUnit> cu);
cargo:warning=            ^~~~~~~~~~~~~
cargo:warning=/home/nazar/cpp/libtorch/include/torch/csrc/api/include/torch/serialize/output-archive.h:28:12: note:   candidate expects 1 argument, 0 provided
cargo:warning=In file included from libtch/torch_api.cpp:6:0:
cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_conv_dilated2d(at::Tensor**, tensor, tensor, int64_t*, int, tensor, int64_t*, int, int64_t*, int, int64_t*, int)’:
cargo:warning=libtch/torch_api_generated.cpp.h:2142:29: error: ‘conv_dilated2d’ is not a member of ‘torch’
cargo:warning=     auto outputs__ = torch::conv_dilated2d(*self, *weight, torch::IntArrayRef(kernel_size_data, kernel_size_len), (bias ? *bias : torch::Tensor()), torch::IntArrayRef(stride_data, stride_len), torch::IntArrayRef(padding_data, padding_len), torch::IntArrayRef(dilation_data, dilation_len));
cargo:warning=                             ^
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_conv_dilated3d(at::Tensor**, tensor, tensor, int64_t*, int, tensor, int64_t*, int, int64_t*, int, int64_t*, int)’:
cargo:warning=libtch/torch_api_generated.cpp.h:2149:29: error: ‘conv_dilated3d’ is not a member of ‘torch’
cargo:warning=     auto outputs__ = torch::conv_dilated3d(*self, *weight, torch::IntArrayRef(kernel_size_data, kernel_size_len), (bias ? *bias : torch::Tensor()), torch::IntArrayRef(stride_data, stride_len), torch::IntArrayRef(padding_data, padding_len), torch::IntArrayRef(dilation_data, dilation_len));
cargo:warning=                             ^
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_conv_transpose2d1(at::Tensor**, tensor, tensor, int64_t*, int, tensor, int64_t*, int, int64_t*, int, int64_t*, int, int64_t*, int)’:
cargo:warning=libtch/torch_api_generated.cpp.h:2186:69: error: invalid initialization of reference of type ‘const at::Tensor&’ from expression of type ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
cargo:warning=     auto outputs__ = torch::conv_transpose2d(*self, *weight, torch::IntArrayRef(kernel_size_data, kernel_size_len), (bias ? *bias : torch::Tensor()), torch::IntArrayRef(stride_data, stride_len), torch::IntArrayRef(padding_data, padding_len), torch::IntArrayRef(output_padding_data, output_padding_len), torch::IntArrayRef(dilation_data, dilation_len));
cargo:warning=                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=In file included from /home/nazar/cpp/libtorch/include/ATen/ATen.h:12:0,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/profiler.h:12,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/function.h:6,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/engine.h:7,
cargo:warning=                 from libtch/torch_api.cpp:1:
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/Functions.h:1653:22: note: in passing argument 3 of ‘at::Tensor at::conv_transpose2d(const at::Tensor&, const at::Tensor&, const at::Tensor&, c10::IntArrayRef, c10::IntArrayRef, c10::IntArrayRef, int64_t, c10::IntArrayRef)’
cargo:warning= static inline Tensor conv_transpose2d(const Tensor & input, const Tensor & weight, const Tensor & bias, IntArrayRef stride, IntArrayRef padding, IntArrayRef output_padding, int64_t groups, IntArrayRef dilation) {
cargo:warning=                      ^~~~~~~~~~~~~~~~
cargo:warning=In file included from libtch/torch_api.cpp:6:0:
cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_conv_transpose2d_out(at::Tensor**, tensor, tensor, tensor, int64_t*, int, tensor, int64_t*, int, int64_t*, int, int64_t*, int, int64_t*, int)’:
cargo:warning=libtch/torch_api_generated.cpp.h:2193:29: error: ‘conv_transpose2d_out’ is not a member of ‘torch’
cargo:warning=     auto outputs__ = torch::conv_transpose2d_out(*out, *self, *weight, torch::IntArrayRef(kernel_size_data, kernel_size_len), (bias ? *bias : torch::Tensor()), torch::IntArrayRef(stride_data, stride_len), torch::IntArrayRef(padding_data, padding_len), torch::IntArrayRef(output_padding_data, output_padding_len), torch::IntArrayRef(dilation_data, dilation_len));
cargo:warning=                             ^
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_conv_transpose3d1(at::Tensor**, tensor, tensor, int64_t*, int, tensor, int64_t*, int, int64_t*, int, int64_t*, int, int64_t*, int)’:
cargo:warning=libtch/torch_api_generated.cpp.h:2207:69: error: invalid initialization of reference of type ‘const at::Tensor&’ from expression of type ‘c10::IntArrayRef {aka c10::ArrayRef<long int>}’
cargo:warning=     auto outputs__ = torch::conv_transpose3d(*self, *weight, torch::IntArrayRef(kernel_size_data, kernel_size_len), (bias ? *bias : torch::Tensor()), torch::IntArrayRef(stride_data, stride_len), torch::IntArrayRef(padding_data, padding_len), torch::IntArrayRef(output_padding_data, output_padding_len), torch::IntArrayRef(dilation_data, dilation_len));
cargo:warning=                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=In file included from /home/nazar/cpp/libtorch/include/ATen/ATen.h:12:0,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/profiler.h:12,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/function.h:6,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/engine.h:7,
cargo:warning=                 from libtch/torch_api.cpp:1:
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/Functions.h:1657:22: note: in passing argument 3 of ‘at::Tensor at::conv_transpose3d(const at::Tensor&, const at::Tensor&, const at::Tensor&, c10::IntArrayRef, c10::IntArrayRef, c10::IntArrayRef, int64_t, c10::IntArrayRef)’
cargo:warning= static inline Tensor conv_transpose3d(const Tensor & input, const Tensor & weight, const Tensor & bias, IntArrayRef stride, IntArrayRef padding, IntArrayRef output_padding, int64_t groups, IntArrayRef dilation) {
cargo:warning=                      ^~~~~~~~~~~~~~~~
cargo:warning=In file included from libtch/torch_api.cpp:6:0:
cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_conv_transpose3d_out(at::Tensor**, tensor, tensor, tensor, int64_t*, int, tensor, int64_t*, int, int64_t*, int, int64_t*, int, int64_t*, int)’:
cargo:warning=libtch/torch_api_generated.cpp.h:2214:29: error: ‘conv_transpose3d_out’ is not a member of ‘torch’
cargo:warning=     auto outputs__ = torch::conv_transpose3d_out(*out, *self, *weight, torch::IntArrayRef(kernel_size_data, kernel_size_len), (bias ? *bias : torch::Tensor()), torch::IntArrayRef(stride_data, stride_len), torch::IntArrayRef(padding_data, padding_len), torch::IntArrayRef(output_padding_data, output_padding_len), torch::IntArrayRef(dilation_data, dilation_len));
cargo:warning=                             ^
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=libtch/torch_api_generated.cpp.h: In function ‘void atg_pin_memory(at::Tensor**, tensor)’:
cargo:warning=libtch/torch_api_generated.cpp.h:5382:29: error: ‘pin_memory’ is not a member of ‘torch’
cargo:warning=     auto outputs__ = torch::pin_memory(*self);
cargo:warning=                             ^
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=libtch/torch_api_generated.cpp.h:5382:29: note: suggested alternatives:
cargo:warning=     auto outputs__ = torch::pin_memory(*self);
cargo:warning=                             ^
cargo:warning=libtch/torch_api.h:16:5: note: in definition of macro ‘PROTECT’
cargo:warning=     x \
cargo:warning=     ^
cargo:warning=In file included from /home/nazar/cpp/libtorch/include/ATen/core/ivalue_inl.h:7:0,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/ATen/core/ivalue.h:601,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/record_function.h:3,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/profiler.h:18,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/function.h:6,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/engine.h:7,
cargo:warning=                 from libtch/torch_api.cpp:1:
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/core/aten_interned_strings.h:521:9: note:   ‘c10::aten::pin_memory’
cargo:warning= _(aten, pin_memory) \
cargo:warning=         ^
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/core/interned_strings.h:363:35: note: in definition of macro ‘DEFINE_SYMBOL’
cargo:warning=   namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
cargo:warning=                                   ^
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/core/interned_strings.h:162:3: note: in expansion of macro ‘FORALL_ATEN_BASE_SYMBOLS’
cargo:warning=   FORALL_ATEN_BASE_SYMBOLS(_)        \
cargo:warning=   ^~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/core/interned_strings.h:364:1: note: in expansion of macro ‘FORALL_NS_SYMBOLS’
cargo:warning= FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
cargo:warning= ^~~~~~~~~~~~~~~~~
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/core/aten_interned_strings.h:521:9: note:   ‘c10::aten::pin_memory’
cargo:warning= _(aten, pin_memory) \
cargo:warning=         ^
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/core/interned_strings.h:363:35: note: in definition of macro ‘DEFINE_SYMBOL’
cargo:warning=   namespace ns { constexpr Symbol s(static_cast<unique_t>(_keys::ns##_##s)); }
cargo:warning=                                   ^
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/core/interned_strings.h:162:3: note: in expansion of macro ‘FORALL_ATEN_BASE_SYMBOLS’
cargo:warning=   FORALL_ATEN_BASE_SYMBOLS(_)        \
cargo:warning=   ^~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/core/interned_strings.h:364:1: note: in expansion of macro ‘FORALL_NS_SYMBOLS’
cargo:warning= FORALL_NS_SYMBOLS(DEFINE_SYMBOL)
cargo:warning= ^~~~~~~~~~~~~~~~~
cargo:warning=In file included from /home/nazar/cpp/libtorch/include/ATen/Functions.h:10:0,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/ATen/ATen.h:12,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/profiler.h:12,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/function.h:6,
cargo:warning=                 from /home/nazar/cpp/libtorch/include/torch/csrc/autograd/engine.h:7,
cargo:warning=                 from libtch/torch_api.cpp:1:
cargo:warning=/home/nazar/cpp/libtorch/include/ATen/NativeFunctions.h:539:19: note:   ‘at::native::pin_memory’
cargo:warning= CAFFE2_API Tensor pin_memory(const Tensor & self);
cargo:warning=                   ^~~~~~~~~~
exit code: 1

--- stderr

error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/nazar/cpp/libtorch/include" "-I" "/home/nazar/cpp/libtorch/include/torch/csrc/api/include" "-Wl,-rpath=/home/nazar/cpp/libtorch/lib" "-std=c++11" "-fPIC" "-D_GLIBCXX_USE_CXX11_ABI=0" "-o" "/home/nazar/cpp/tch-rs/target/debug/build/torch-sys-637eb1483b0e44a9/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp" with args "c++" did not execute successfully (status code exit code: 1).

**Comment by LaurentMazare** [comment]
Which version of tch-rs and libtorch are you using ?
The error seems to be that you're using the latest github version for tch-rs but maybe you don't have libtorch 1.2.0 installed.
As reported in #91 there are currently no pre-compiled binaries for libtorch 1.2.0 linux/cpu but hopefully these should be available in the next few days. In the meantime you can either compile libtorch 1.2.0 from source (using the github branch v1.2.0 from pytorch/pytorch) or use revision 2de692af4bf1964f7b6c6dde84cde9920eb706f5 of tch-rs github with libtorch 1.1.0.

**Comment by nazarblch** [comment]
I am using the latest tch-rs and recently downloaded https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-latest.zip  --  it should be  libtorch 1.2.0 according to the pytorch web page.

**Comment by LaurentMazare** [comment]
Actually the pytorch webpage may be wrong, see this [issue from the pytorch repo](https://github.com/pytorch/pytorch/issues/24120) for more details.

You can try the following link instead: https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-1.2.0.zip

**Comment by nazarblch** [comment]
resolved, thanks for fast reply!

**Comment by AhmedAAkl** [comment]
Hi @LaurentMazare, @nazarblch,

I have the same error 
error: failed to run custom build command for `torch-sys v0.5.0 (C:\Users\Akl\Projects\examples\torch_rust\tch-rs\torch-sys)`
I cloned this repo and added paths in the toml file 
I am working in Windows 10 and this is a part of my Toml file

[dependencies]
tch = {version="0.5.0", path = "tch-rs"}
torch-sys = { version = "0.5.0", path = "tch-rs/torch-sys" }
anyhow = "1.0.33"

I added LIBTORCH environment variable with libtorch 1.9.0 version

Unfortunately didn't work

any ideas.
Thanks
