### ISSUE TITLE
Linking error tch 0.1.1 & Centos 7

### ISSUE THREAD

**Issue by jean-airoldie** [LaurentMazare/tch-rs#95]
When I try to run a binary using `tch = 0.1.1` on `centos 7`, I get a linking error:
`/usr/bin/ld: warning: libgomp-8bba0e50.so.1, needed by /home/maxence/zezima/market-analytics/target/release/build/torch-sys-c846cc9c89b11e6f/out/libtorch/libtorch/lib/libc10.so, not found (try using -rpath or -rpath-link)`. Note that I'm not installing libtorch manually.

When I look at the content of the `OUT_DIR` of the build script, I can see `libgomp-8bba0e50.so.1`. So the lib is not missing, just not linked.

See the full error output https://gist.github.com/jean-airoldie/c908704722181f2d0dfc27bf64bcf668.

**Comment by LaurentMazare** [comment]
Not really sure what is going on there. Maybe you could try tweaking `LIBRARY_PATH` and `LD_LIBRARY_PATH` to include the path in which `libgomp-8bba0e50.so.1` is to see if this helps ?

**Comment by jean-airoldie** [comment]
The path where libgomp is located is in `lib` where all the other libs are located. To me it seems like a link flag is missing altogether for libgomp.

I'll test on fedora to see if this is specific to centos 7.

**Comment by jean-airoldie** [comment]
Seems to be centos 7 specific. And building with cmake doesnt make a difference.

**Comment by LaurentMazare** [comment]
Did you manage to fix this with any additional flag like `-lgomp` ?
If it's also an issue when building the minimal [C++ example](https://pytorch.org/cppdocs/installing.html#minimal-example) from PyTorch using cmake, it may be worth opening an issue on the pytorch repo too (I'm not sure if this is what you mean by "And building with cmake doesn't make a difference").

**Comment by jerry73204** [comment]
The official shared library has `RUNPATH` set to `$ORIGIN`. (You can check by `readelf -d libtorch.so`) So, I expect the dynamic linker is able to find `libgomp-8bba0e50.so.1` in same directory.

However, ld fail for some reason. Maybe you can check if `DT_RUNPATH` and `DT_RPATH` env vars are set, and check `ldd -v libtorch.so`.

**Comment by jean-airoldie** [comment]
> Did you manage to fix this with any additional flag like -lgomp ?

Adding `lgomp` doesn't work unfortunately, it's the first thing I tried. 

> I'm not sure if this is what you mean by "And building with cmake doesn't make a difference".

Tried building with both make & cmake just in case. But it didn't matter. I thought it might be a building issue, but it doesn't seem to be the case.

Just realized the the output static lib is called `liblibtorch.a`, which seems quite suspicious, so I'll investigate that.

**Comment by jean-airoldie** [comment]
Yep that's indeed the culprit. I'll submit a PR to fix this. I see two potential solutions to this problem:
* We name the library differently depending of the build `TARGET`, which is quite finicky since we have to test with every `OS`.
* We renamed the compiled lib to `libtorch.a` at the end of the build, so we don't have to change behaviour across `OS`. That's probably what I'll do.

**Comment by jean-airoldie** [comment]
Hum, I tested against fedora and I still get `liblibtorch.a`. So I assume that this is the behaviour on all `OS` but that somehow some are resistant to the error.

**Comment by jean-airoldie** [comment]
According to the `cc` doc for the `compile` fn:
> The name output should be the name of the library. For backwards compatibility, the output may start with lib and end with .a. The Rust compilier will create the assembly with the lib prefix and .a extension. MSVC will create a file without prefix, ending with .lib.

From what I understand, this means that the name passed to the `compile` fn should either be `libtorch.a` or `torch`, not but not `libtorch`, like we currently have.

**Comment by vegapit** [comment]
Unfortunately, this fix has broken the project linker on MacOSX:
```
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)  
```
Any suggestions?

**Comment by LaurentMazare** [comment]
Sorry about that, I guess we would need CI for macos too.

I don't have a mac to test this but maybe fixing it is as easy as tweaking the last lines of `torch-sys/build.rs` to look like the following.
```rust
  if !target.contains("msvc") && !target.contains("apple") {
        println!("cargo:rustc-link-lib=gomp");
    }
```
@vegapit would you be able to give this a try ?

**Comment by vegapit** [comment]
I sure can. The good news is that your suggestion does the trick. Feel free to commit.

**Comment by LaurentMazare** [comment]
I just pushed the change, thanks for reporting the issue. I'll also have a look at having macOS supported in our travis CI.

**Comment by vegapit** [comment]
Superb, thanks a lot for the fast update.

**Comment by xiaoniu-578fa6bff964d005** [comment]
Similar error again.
I use latest master branch 49c926737a0e6e9df5a02893ca987fcc9ac4d5d7 on CentOS 7.
I get a linking error:
```
note: /usr/bin/ld: warning: libgomp-753e6e92.so.1, needed by /home/xiaoniu/.cache/cargo/debug/build/torch-sys-26fd490960495512/out/libtorch/libtorch/lib/libtorch.so, not found (try using -rpath or -rpath-link)
```
`-lgoml` has already been passed.
`libgomp-753e6e92.so.1` can be found in 

Manually add `LD_LIBRARY_PATH=/home/xiaoniu/.cache/cargo/debug/build/torch-sys-26fd490960495512/out/libtorch/libtorch/lib/` solve this error, but create another erro: 
`/home/xiaoniu/.cache/cargo/debug/deps/libtorch_sys-adab35afbf0ab68f.rlib(torch_api.o): In function c10::Device::validate():
/home/xiaoniu/.cache/cargo/debug/build/torch-sys-26fd490960495512/out/libtorch/libtorch/include/c10/core/Device.h:93: undefined reference to c10::Error::Error(c10::SourceLocation, std::string const&)`

Build tool:
cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
ldd (GNU libc) 2.17
full error: https://gist.github.com/xiaoniu-578fa6bff964d005/292c906b60912adc9b623d43fa49af4c

**Comment by LaurentMazare** [comment]
I wonder if it could be some gcc C++11 ABI incompatibility rather than the issue described earlier in this thread.
To check this, maybe you could download the pre-cxx11 abi version of libtorch [here](https://download.pytorch.org/libtorch/cu101/libtorch-shared-with-deps-1.3.1.zip).
Once you've extracted the content of the zip file, adjust your environment variables via:
```bash
export LIBTORCH=/path/to/libtorch
export LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH
export LIBTORCH_CXX11_ABI=0
```
And try a `cargo clean` then to recompile.

**Comment by xiaoniu-578fa6bff964d005** [comment]
@LaurentMazare Solved. Thank you!
